### ISSUE TITLE
Invalid query raises 500 Internal Server Error.

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1131]
_From [namusyaka](https://code.google.com/u/118268004209826564673/) on December 13, 2013 23:38:35_

When you go `/?q=%` in my app, Passenger returns response code 500.
I'd expect to get `400 bad request`.

error.log: https://gist.github.com/namusyaka/1eef2e3211cb7bb5c1f5 Environment:
Passenger: passenger-4.0.27
(Not Rails but) Padrino: 0.11.3
OS: CentOS 

Thank you.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1032_

**Comment by aganov** [comment]
Invalid requests are reaching our application too, causing error log to be clogged with `Rack::Utils::InvalidParameterError: invalid %-encoding (%s)`. I think passenger should return `400 Bad Request`, and the rack app should never been reached... More information can be found here: https://github.com/rack/rack/issues/337

**Comment by OnixGH** [comment]
@aganov What requests are those? What is your setup? Do you have a log file with passenger log level set to 7?

The link you gave just shows a list of rack issues, which one are you talking about?

**Comment by OnixGH** [comment]
I can't reproduce the original issue with Passenger 5.0.24. With both Passenger/Apache as well as Passenger/Nginx I get a HTTP 400 reply (ultimately coming from the application) as expected.

**Comment by aganov** [comment]
@OnixGH Just upadted to 5.0.24 issue still exists

```
curl -I https://example.com/qsonhs.aspx\?q\=%s\&form\=MO0014\&mkt\=%s

HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Content-Length: 1477
Connection: keep-alive
Status: 500 Internal Server Error
X-Runtime: 0.004224
X-Request-Id: 4d7ccca0-c16a-4553-8f9f-f57fff9f492d
Date: Thu, 04 Feb 2016 11:39:10 GMT
X-Powered-By: Phusion Passenger
Server: nginx + Phusion Passenger
```

**Comment by OnixGH** [comment]
@aganov do you have a log with level set to 7 with that? What is your setup? I don't get the error.

```
curl -I https://localhost:3000/qsonhs.aspx\?q\=%s\&form\=MO0014\&mkt\=%s

HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=utf-8
Content-Length: 0
Connection: keep-alive
Status: 400 Bad Request
X-Runtime: 0.063933
X-Request-Id: 66e34878-ff9b-4377-9d1f-85413b03dd07
Date: Thu, 04 Feb 2016 11:52:54 GMT
X-Powered-By: Phusion Passenger 5.0.24
Server: nginx/1.8.1 + Phusion Passenger 5.0.24
```

**Comment by aganov** [comment]
@OnixGH I've set error log to 7, but nothing is written to the nginx's error log, Here is the trace from our app

```
ruby 2.2.3
nginx 1.9.10
passenger 5.0.24
rails 4.2.4
```

```
F, [2016-02-04T14:14:22.093112 #9768] FATAL -- : 
Rack::Utils::InvalidParameterError (invalid %-encoding (%s)):
  rack (1.6.4) lib/rack/utils.rb:127:in `rescue in parse_nested_query'
  rack (1.6.4) lib/rack/utils.rb:117:in `parse_nested_query'
  rack (1.6.4) lib/rack/request.rb:371:in `parse_query'
  rack (1.6.4) lib/rack/request.rb:191:in `GET'
  rack (1.6.4) lib/rack/request.rb:230:in `params'
  remotipart (1.2.1) lib/remotipart/middleware.rb:12:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.2.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  passenger (5.0.24) src/ruby_supportlib/phusion_passenger/rack/out_of_band_gc.rb:48:in `call'
  passenger (5.0.24) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.0.24) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  passenger (5.0.24) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  passenger (5.0.24) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.0.24) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by OnixGH** [comment]
If you're not getting log output, then there must be something wrong with your setup, maybe you haven't restarted or you're configuring/watching the wrong file. Maybe you have `passenger_log_file` set to something else.

The application error doesn't help really. If it's just that rack/rails can't handle an invalid encoding then that is not a Passenger issue (although as I said I don't get the 500 response here, also tried with nginx 1.9.10 + Passenger 5.0.24 + rails 4.2.4 + ruby 2.2.3 + rack 1.6.4).

**Comment by ixti** [comment]
From my observations nginx does not care about queries. So request uri is passed as is to backend.
So, for example if you will have `nginx -> webrick -> rack` then request will be downstreamed to webrick which will respond with 400 Bad Request without passing such request to rack.

In case of `nginx -> passenger -> rack`, passenger also seems like passes request uri as is to downstream backend.
