### ISSUE TITLE
invalid byte sequence in UTF-8 with passenger 4.0.40 and rack-1.4.5 multipart data

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1169]
_From [fwoeck](https://code.google.com/u/103287677640703009186/) on March 21, 2014 14:17:23_

When I send a binary file in a multipart form rack interprets the @buf (form data) as being UTF-8. When I force this to binary, things work: @buf.force_encoding('BINARY') (see stack trace below). This works also, if I use puma as server.

Versions are ubuntu 13.10, rbx 2.2.6, passenger 4.0.40 and rack-1.4.5 

~~~
App 3217 stderr: [ 2014-03-21 12:55:30.6343 3217/0x4e7a0(Worker 16) utils.rb:52 ]: *** Exception ArgumentError in Rack application object (invalid byte sequence in UTF-8) (process 3217, thread 0x4e7a0(Worker 16)):
App 3217 stderr:        from kernel/common/string.rb:103:in `=~'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/multipart/parser.rb:92:in `get_current_head_and_filename_and_content_type_and_name_and_body'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/multipart/parser.rb:19:in `parse'
App 3217 stderr:        from kernel/common/kernel.rb:460:in `loop'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/multipart/parser.rb:17:in `parse'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/multipart.rb:25:in `parse_multipart'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/request.rb:336:in `parse_multipart'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/request.rb:201:in `POST'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:26:in `method_override'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:14:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-ssl-1.3.3/lib/rack/ssl.rb:27:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:143:in `pass'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:155:in `invalidate'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:71:in `call!'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/railties-3.2.17/lib/rails/engine.rb:484:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in `call (method_missing)'
App 3217 stderr:        from /home/dkm/.rvm/gems/ruby-2.1.1@global/gems/passenger-enterprise-server-4.0.40/lib/phusion_passenger/rack/thread_handler_extension.rb:58:in `process_request'
App 3217 stderr:        from /home/dkm/.rvm/gems/ruby-2.1.1@global/gems/passenger-enterprise-server-4.0.40/lib/phusion_passenger/request_handler/thread_handler.rb:126:in `accept_and_process_next_request'
App 3217 stderr:        from /home/dkm/.rvm/gems/ruby-2.1.1@global/gems/passenger-enterprise-server-4.0.40/lib/phusion_passenger/request_handler/thread_handler.rb:94:in `main_loop'
App 3217 stderr:        from /home/dkm/.rvm/gems/ruby-2.1.1@global/gems/passenger-enterprise-server-4.0.40/lib/phusion_passenger/request_handler.rb:471:in `start_threads'
App 3217 stderr:        from kernel/bootstrap/proc.rb:20:in `call'
App 3217 stderr:        from /opt/dokmatic1/vendor/bundle/rbx/2.1/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `create_with_logging_context'
App 3217 stderr:        from kernel/bootstrap/proc.rb:20:in `call'
App 3217 stderr:        from kernel/bootstrap/thread.rb:391:in `__run__'
~~~

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=1070_

**Comment by PratheepV** [comment]
Hey,

I am facing similar issue. will the https://github.com/whitequark/rack-utf8_sanitizer helps us in this?

Thanks,
Pratheepv

**Comment by FooBarWidget** [comment]
@PratheepV Maybe, but the underlying bug is in Rubinius and JRuby, so you should upgrade your Ruby interpreter.

Seeing that both Rubinius and JRuby have fixed this bug, I'm closing this issue.
