### ISSUE TITLE
Show an error page when the Rack app object returns a nil body

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1218]
The Rack app object returning a nil body could indicate a bug in one of the Rack middlewares, but it could also indicate an error in Rails. For example, if Rails is configured to use memcache, but the memcache daemon isn't running, then Rails sometimes returns a nil body on all requests, instead of throwing an exception during startup. This behavior is extremely confusing, and it doesn't leave any proper error messages in the logs. The Ruby request handler (rack/thread_handler_extension.rb) should output an appropriate error message if it detects a nil body.

**Comment by FooBarWidget** [comment]
Test again w/ Passenger 5.3. The browser receives an "Incomplete response received from application" error message, while the following is logged:

~~~
[ W 2018-09-17 08:58:35.9364 62139/Tc age/Cor/Con/InternalUtils.cpp:96 ]: [Client 3-1] Sending 502 response: application did not send a complete response
App 62177 output: [ 2018-09-17 08:58:35.9372 62177/0x00007fef9c007858(Worker 1) utils.rb ]: *** Exception NoMethodError (undefined method `[]' for nil:NilClass) (process 62177, thread 0x00007fef9c007858(Worker 1)):
App 62177 output: 	from /Users/hongli/Projects/passenger/src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:126:in `process_request'
App 62177 output: 	from /Users/hongli/Projects/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
App 62177 output: 	from /Users/hongli/Projects/passenger/src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 62177 output: 	from /Users/hongli/Projects/passenger/src/ruby_supportlib/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 62177 output: 	from /Users/hongli/Projects/passenger/src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
~~~

I think this is good enough, so closing this issue.
