### ISSUE TITLE
TimeOut and Rack critical error

### ISSUE THREAD

**Issue by jcalonsoh** [phusion/passenger#1236]
``` ruby

2014/07/11 12:39:18 [error] 11222#0: *2 upstream prematurely closed connection while reading response header from upstream, client: 10.200.206.64, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.11202/generation-0/request:", host: "10.200.206.19"
App 11244 stderr: /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/rack/thread_handler_extension.rb:106:in `block in process_request'
App 11244 stderr: : 
App 11244 stderr: undefined method `each' for 1405096758:Fixnum
App 11244 stderr:  (
App 11244 stderr: NoMethodError
App 11244 stderr: )
App 11244 stderr:   from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/rack/thread_handler_extension.rb:98:in `each'
App 11244 stderr:   from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/rack/thread_handler_extension.rb:98:in `process_request'
App 11244 stderr:   from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
App 11244 stderr:   from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
App 11244 stderr:   from /usr/lib64/ruby/gems/2.1.0/gems/passenger-4.0.45/lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'
[ 2014-07-11 12:39:22.0328 11206/7f7b7da8f700 Pool2/Pool.h:777 ]: Process (pid=11283, group=/usr/share/nginx/api#default) no longer exists! Detaching it from the pool.
App 11297 stdout:

```

**Comment by FooBarWidget** [comment]
This issue has been open for a long time, and I haven't seen any updates since, neither by the original poster nor by other users. The logs indicate that this is an error in one of the Rack middlewares, so not a problem in Passenger. The Rack middleware returns an integer as a body, but Passenger expects (per the Rack spec) an array of strings.

Since this is not a Passenger problem, closing this issue.
