### ISSUE TITLE
"Could not find rubygems" for Rails 3.2 + Ruby 2.0 (Passenger 4.0.46)

### ISSUE THREAD

**Issue by ZipoKing** [phusion/passenger#1245]
I'm getting following error message at the top of nginx error.log (having custom Ruby installation under /opt, app is working fine and paths to Passenger/Ruby are set correctly in nginx.conf):

```
[ 2014-07-18 07:15:24.3624 1019/7f2a96a14720 agents/Watchdog/Main.cpp:538 ]: Options: { 'analytics_log_user' => 'nobody', 'default_group' => 'nogroup', 'default_python' => 'python', 'default_ruby' => '/opt/ruby/bin/ruby', 'default_user' => 'nobody', 'log_level' => '0', 'max_pool_size' => '10', 'passenger_root' => '/opt/ruby/lib/ruby/gems/2.0.0/gems/passenger-4.0.46', 'passenger_version' => '4.0.46', 'pool_idle_time' => '5', 'temp_dir' => '/tmp', 'union_station_gateway_address' => 'gateway.unionstationapp.com', 'union_station_gateway_port' => '443', 'user_switching' => 'true', 'web_server_passenger_version' => '4.0.46', 'web_server_pid' => '1013', 'web_server_type' => 'nginx', 'web_server_worker_gid' => '33', 'web_server_worker_uid' => '33' }
[ 2014-07-18 07:15:24.3925 1022/7f90e40f0720 agents/HelperAgent/Main.cpp:649 ]: PassengerHelperAgent online, listening at unix:/tmp/passenger.1.0.1013/generation-0/request
[ 2014-07-18 07:15:24.4090 1030/7f65af62f740 agents/LoggingAgent/Main.cpp:321 ]: PassengerLoggingAgent online, listening at unix:/tmp/passenger.1.0.1013/generation-0/logging
[ 2014-07-18 07:15:24.4093 1019/7f2a96a14720 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
App 1060 stdout: 
App 1060 stderr: /opt/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/shared_helpers.rb:2:in `require'
App 1060 stderr: :                                                                                                                                                                  
App 1060 stderr: no such file to load -- rubygems                                                                                                                                   
App 1060 stderr:  (                                                                                                                                                                 
App 1060 stderr: LoadError                                                                                                                                                          
App 1060 stderr: )                                                                                                                                                                  
App 1060 stderr:        from /opt/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/shared_helpers.rb:2                                                            
App 1060 stderr:        from /opt/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/setup.rb:1:in `require'                                                        
App 1060 stderr:        from /opt/ruby-2.0.0-p353/lib/ruby/gems/2.0.0/gems/bundler-1.3.5/lib/bundler/setup.rb:1                                                                     
[ 2014-07-18 07:15:44.0283 1022/7f90e178c700 Pool2/SmartSpawner.h:298 ]: Preloader for /srv/www/webapp started on PID 1060, listening on unix:/tmp/passenger.1.0.1013/generation-0/backends/preloader.1060 
```

**Comment by FooBarWidget** [comment]
It's been a long time since this issue was opened. I haven't seen any further complaints, either from the original poster or from other users. So closing this issue for now. If you still experience this problem please feel free to request a reopen.
