### ISSUE TITLE
Make Watchdog more resillient to out-of-memory conditions (was: No recovery from 502 Bad Gateway when PassengerWatchdog dies)

### ISSUE THREAD

**Issue by JasonBarnabe** [phusion/passenger#1257]
Passenger 4.0.37
nginx 1.4.4

I've had a few situations recently where my server runs low on resources due to my Rails processes consuming too much. In some cases, this causes PassengerWatchdog to crash. When PassengerWatchdog crashes, it takes down the Rails processes with it, effectively fixing the low resource issue, but then nginx serves up 502 errors with this in the log:

```
2014/08/06 11:17:45 [error] 9455#0: *1 connect() to /tmp/passenger.1.0.9435/generation-0/request failed (111: Connection refused) while connecting to upstream, client: 1.2.3.4, server: example.com, request: "GET / HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.9435/generation-0/request:", host: "example.com"
```

nginx doesn't seem to be able to recover from this. My external monitoring of the nginx service doesn't see anything wrong, because nginx is still running. (I've since added monitoring for the Passenger processes.)

I would like nginx to (attempt to) restart the Passenger processes if it sees none are running. If this is something that would be the nginx team's responsibility, let me know and I will file an issue with them.

**Comment by mfazekas** [comment]
We have similiar issue with nginx/1.8.1 Phusion_Passenger/5.0.26
```
App 18926 stderr: /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:70:in `fork'
App 18926 stderr: : 
App 18926 stderr: Cannot allocate memory - fork(2)
App 18926 stderr:  (
App 18926 stderr: Errno::ENOMEM
App 18926 stderr: )
App 18926 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:70:in `accept_and_process_next_client'
App 18926 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/preloader_shared_helpers.rb:140:in `run_main_loop'
App 18926 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:157:in `<module:App>'
App 18926 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
App 18926 stderr:       from /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
[ 2016-03-07 19:20:19.0750 25699/7fd2c40f6700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/apps/cambeo/current: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
  Error ID: e3988f6e
  Error details saved to: /tmp/passenger-error-wM9wuc.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
<h2>Raw process output:</h2>
(empty)
```

....
```
[ 2016-03-07 19:21:45.3845 25699/7fd2cb47e700 age/Cor/App/Poo/AnalyticsCollection.cpp:61 ]: ERROR: Cannot fork() a new process: Cannot allocate memory (errno=12)
  Backtrace:
     in 'void Passenger::ApplicationPool2::Pool::realCollectAnalytics()' (AnalyticsCollection.cpp:183)
     in 'static void Passenger::ApplicationPool2::Pool::collectAnalytics(Passenger::ApplicationPool2::PoolPtr)' (AnalyticsCollection.cpp:56)

terminate called after throwing an instance of 'Passenger::SystemException'
  what():  Cannot fork a new process: Cannot allocate memory (errno=12)
ERROR: cannot fork a process for executing 'tee'
[ pid=25699, timestamp=1457378520 ] Process aborted! signo=SIGABRT(6), reason=SI_TKILL, signal sent by PID 25699 with UID 0, si_addr=0x6463, randomSeed=1457097677
[ pid=25699 ] Could not create crash log file, so dumping to stderr only.
[ pid=25699 ] Could fork a child process for dumping diagnostics: fork() failed with errno=12
[ 2016-03-07 19:22:01.1384 25696/7ff41fccc700 age/Wat/AgentWatcher.cpp:97 ]: Passenger core (pid=25699) crashed with signal SIGABRT, restarting it...
[ 2016-03-07 19:22:13.3023 25696/7ff41fd0f7c0 age/Wat/WatchdogMain.cpp:324 ]: Error in Passenger core watcher:
  Cannot fork a new process: Cannot allocate memory (errno=12)
     (empty)

[ 2016-03-07 19:22:29.6757 25696/7ff41fd0f7c0 age/Wat/WatchdogMain.cpp:1357 ]: ERROR: Cannot fork a new process: Cannot allocate memory (errno=12)
     in 'void cleanup(const WorkingObjectsPtr&)' (WatchdogMain.cpp:1257)
     in 'int watchdogMain(int, char**)' (WatchdogMain.cpp:1348)
```
then we get 502

strange that on first log files memory error /tmp/passenger-error-wM9wuc.html:

```
RAM total         :<wbr>   3952 MB
RAM used          :<wbr>    845 MB (21%)
RAM free          :<wbr>   3106 MB
```

in later log files:
```
RAM total         :<wbr>   3952 MB
RAM used          :<wbr>   3821 MB (97%)
RAM free          :<wbr>    130 MB
```
so we're short on memory eventually, but why we start to see it when we've not yet ran out of memory?

**Comment by OnixGH** [comment]
The memory errors are sent by the OS so there's no reason not to believe them really.

I could imagine for example that the free memory is fragmented and as memory conditions get tighter certain allocations will start being denied because contiguous blocks of sufficient size are no longer available.

**Comment by mfazekas** [comment]
@OnixGH i don't dubt that the errors are genue. 

I just find it strange to have them and then your log file shows RAM use as (20%).
I don't think fragmentation can be an issue. These memory is reported by kernel. So i assume 3106  M free means we have 795136 pages (with 4K/page) avail. Because of virtual memory they visible can be mapped as continues area if needed.

**Comment by CirrusThink** [comment]
We are seeing the same issue on 5.0.28, and all calls end up in 502 bad gateway

**Comment by OnixGH** [comment]
@CirrusThink I'm not sure what you want us to do; when your system runs out of memory, it will start to kill processes and you'll have a lot more issues than just with Passenger.

Actually if the Passenger process can run as root on your system, then the watchdog will automatically set its OOM score to unkillable and it shouldn't be killed at all, but your webserver might still die, which we cannot solve.

**Comment by CirrusThink** [comment]
The issue is that the system is not running out of memory or if there are memory related issues, they are being caused by running passenger processes that are not able to shutdown even after a time limit is applied

**Comment by OnixGH** [comment]
@CirrusThink sorry, but that is way too vague to do anything with. Please post output from `passenger-status` and `passenger-memory-stats` around the time of the 502's to verify whether it's a memory related issue or something completely different. And also a passenger log that contains the 502's so we can check what is going on.

It should be easy to see if your processes are in fact increasing in memory use (upwards trend without halt), and if so, you can analyze whether the configuration you have in place is sufficient (e.g. passenger can limit based on memory use, request time, number of requests, etc. but it's up to you to decide how to use them, by default Passenger doesn't kill processes)

You can use our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for any questions about configuration.

**Comment by clreddy21** [comment]
We are facing a similar problem with rails, passenger, apache on ubuntu 14 on digitalocean. Following are the apache logs files,

`App 7451 stderr: Cannot render console from 71.193.196.76! Allowed networks: 220.227.243.41, 127.0.0.0/127.255.255.255, ::1
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >'
  what():  boost::thread_resource_error: Resource temporarily unavailable
ERROR: cannot fork a process for executing 'tee'
[ pid=690, timestamp=1468218019 ] Process aborted! signo=SIGABRT(6), reason=SI_TKILL, signal sent by PID 690 with UID 0, si_addr=0x2b2, randomSeed=1468148237
[ pid=690 ] Could not create crash log file, so dumping to stderr only.
[ pid=690 ] Could fork a child process for dumping diagnostics: fork() failed with errno=12
[ 2016-07-11 02:20:19.9898 687/7fddd928b700 age/Wat/AgentWatcher.cpp:97 ]: Passenger core (pid=690) crashed with signal SIGABRT, restarting it...
[ 2016-07-11 02:20:20.3201 687/7fddd92ce7c0 age/Wat/WatchdogMain.cpp:348 ]: Error in Passenger core watcher:
  Cannot fork a new process: Cannot allocate memory (errno=12)
     (empty)

[ 2016-07-11 02:20:22.0900 696/7ff85607f700 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2016-07-11 02:20:22.0906 696/7ff85c88c7c0 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-07-11 02:20:22.0914 696/7ff85607f700 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2016-07-11 02:20:22.0915 696/7ff85587e700 Ser/Server.h:817 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2016-07-11 02:20:22.0915 696/7ff85587e700 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2016-07-11 02:20:22.0927 696/7ff85c88c7c0 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2016-07-11 02:20:27.3359 722/7f6cdac5d780 apa/Hooks.cpp:690 ]: Unexpected error in mod_passenger: Cannot connect to the Passenger core at unix:/tmp/passenger.R15fYDR/agents.s/core
  Backtrace:
     in 'Passenger::FileDescriptor Hooks::connectToCore()' (Hooks.cpp:306)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:561)

[ 2016-07-11 02:20:27.3465 9036/7f6cdac5d780 apa/Hooks.cpp:690 ]: Unexpected error in mod_passenger: Cannot connect to the Passenger core at unix:/tmp/passenger.R15fYDR/agents.s/core
  Backtrace:
     in 'Passenger::FileDescriptor Hooks::connectToCore()' (Hooks.cpp:306)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:561)

[ 2016-07-11 02:20:27.3361 5365/7f6cdac5d780 apa/Hooks.cpp:690 ]: Unexpected error in mod_passenger: Cannot connect to the Passenger core at unix:/tmp/passenger.R15fYDR/agents.s/core
  Backtrace:
     in 'Passenger::FileDescriptor Hooks::connectToCore()' (Hooks.cpp:306)
     in 'int Hooks::handleRequest(request_rec*)' (Hooks.cpp:561)
`

I had to restart my server 3 times in the span of last 30 days.
There are no answers for the issue on SO or any other sites. Is there a workaround so that server doesn't crash.

**Comment by OnixGH** [comment]
@clreddy21 the solution is to not let the system run out of memory. You should monitor what is taking the memory and then fix that.

If it happens to be a memory leak in your application, then Passenger has several options (for example, [PassengerMemoryLimit](https://www.phusionpassenger.com/library/config/apache/reference/#passengermemorylimit) and [PassengerMaxRequests](https://www.phusionpassenger.com/library/config/apache/reference/#passengermaxrequests)) to help work around this until you fix the application.
