### ISSUE TITLE
Passenger install fails on CentOS 6.5

### ISSUE THREAD

**Issue by d-snp** [phusion/passenger#1292]
It gives the following exception:

```
This installer will guide you through the entire installation process. It
shouldn't take more than 3 minutes in total.

Here's what you can expect from the installation process:

 1. The Apache 2 module will be installed for you.
 2. You'll learn how to configure Apache.
 3. You'll learn how to deploy a Ruby on Rails application.

Don't worry if anything goes wrong. This installer will advise you on how to
solve any problems.

Press Enter to continue, or Ctrl-C to abort.


--------------------------------------------

Which languages are you interested in?

Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Ruby
   ⬢  Python
   ⬡  Node.js
   ⬡  Meteor

--------------------------------------------

Checking for required software...

 * Checking for C compiler...
      Found: yes
      Location: /usr/bin/cc
 * Checking for C++ compiler...
      Found: yes
      Location: /usr/bin/c++
 * Checking for Curl development headers with SSL support...
--------------------------------------------
*** EXCEPTION: parent directory is world writable, FileUtils#remove_entry_secure does not work; abort: "/tmp/passenger.1gdd4oe" (parent directory mode 40777) (ArgumentError)
    /usr/lib/ruby/1.8/fileutils.rb:695:in `remove_entry_secure'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/utils/tmpio.rb:72:in `mktmpdir'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info.rb:159:in `create_temp_file'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/compiler.rb:218:in `find_header'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/depcheck_specs/libs.rb:30:in `load'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/depcheck.rb:77:in `call'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/depcheck.rb:77:in `check'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/depcheck.rb:321:in `check_all'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/depcheck.rb:317:in `each'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/platform_info/depcheck.rb:317:in `check_all'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/abstract_installer.rb:150:in `check_dependencies'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/bin/passenger-install-apache2-module:126:in `run_steps'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/lib/phusion_passenger/abstract_installer.rb:72:in `run'
    /usr/local/rvm/gems/ruby-2.0.0-p481/gems/passenger-4.0.53/bin/passenger-install-apache2-module:866
    /usr/local/rvm/gems/ruby-2.0.0-p481/bin/passenger-install-apache2-module:23:in `load'
    /usr/local/rvm/gems/ruby-2.0.0-p481/bin/passenger-install-apache2-module:23

--------------------------------------------

Oops, something went wrong :-(

We're sorry, but it looks like this installer ran into an unexpected problem.
Please visit the following website for support. We'll do our best to help you.

  https://www.phusionpassenger.com/documentation_and_support

When submitting a support inquiry, please copy and paste the entire installer
output.
```

**Comment by acosonic** [comment]
@asqard chmod o+t -R /tmp didn't work for me on Ubuntu 14.04 but what eventually worked is:

sudo chmod 1777 /tmp
