### ISSUE TITLE
Passenger doesn't accept Ruby file with `__END__` section

### ISSUE THREAD

**Issue by hauleth** [phusion/passenger#1303]
It is useful feature for minimal Sinatra applications.

```
=============== Phusion Passenger Standalone web server started ===============
PID file: /home/hauleth/Workspace/raptor-unicorn/tmp/pids/passenger.3000.pid
Log file: /home/hauleth/Workspace/raptor-unicorn/log/passenger.3000.log
Environment: development
Accessible via: http://0.0.0.0:3000/

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/documentation/Users%20guide%20Standalone.html#troubleshooting
===============================================================================
App 21450 stdout: 
App 21450 stdout: 
[ 2014-11-25 18:56:13.8058 21402/7fb0c807e700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /home/hauleth/Workspace/raptor-unicorn: An error occured while starting up the preloader.
  Error ID: 39a02d4a
  Error details saved to: /tmp/passenger-error-rAiHN5.html
  Message from application: app.rb:26: syntax error, unexpected end-of-input, expecting ')'
__END__
 ^ (SyntaxError)
  /home/hauleth/Workspace/raptor-unicorn/vendor/bundle/gems/passenger-4.0.53/helper-scripts/rack-preloader.rb:112:in `eval'
  /home/hauleth/Workspace/raptor-unicorn/vendor/bundle/gems/passenger-4.0.53/helper-scripts/rack-preloader.rb:112:in `preload_app'
  /home/hauleth/Workspace/raptor-unicorn/vendor/bundle/gems/passenger-4.0.53/helper-scripts/rack-preloader.rb:158:in `<module:App>'
  /home/hauleth/Workspace/raptor-unicorn/vendor/bundle/gems/passenger-4.0.53/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
  /home/hauleth/Workspace/raptor-unicorn/vendor/bundle/gems/passenger-4.0.53/helper-scripts/rack-preloader.rb:28:in `<main>'


[ 2014-11-25 18:56:13.8144 21402/7fb0c5f63700 agents/HelperAgent/RequestHandler.h:2306 ]: [Client 20] Cannot checkout session because a spawning error occurred. The identifier of the error is 39a02d4a. Please see earlier logs for details about the error.
Stopping web server... done
```

**Comment by FooBarWidget** [comment]
I agree it's a useful feature, but I'm afraid we cannot support it due to the way the Rackup DSL works.

**Comment by FooBarWidget** [comment]
In particular, using the Rackup DSL requires us to evaluate the file as a string. Ruby does not support __END__ markers in such a situation.
