### ISSUE TITLE
Passenger 5.0.0-beta2 crash on Heroku

### ISSUE THREAD

**Issue by SebastianEdwards** [phusion/passenger#1329]
Log below. Heroku stack is cedar-14 (the default). Ruby is MRI 2.1.5.

```
2014-12-20T13:58:13.359737+00:00 heroku[web.1]: State changed from crashed to starting
2014-12-20T13:58:18.919860+00:00 heroku[web.1]: Starting process with command `bundle exec passenger start -p 47119 --max-pool-size 3`
2014-12-20T13:58:20.649546+00:00 app[web.1]:  --> Downloading a Phusion Passenger agent binary for your platform
2014-12-20T13:58:21.049173+00:00 app[web.1]:
2014-12-20T13:58:21.049184+00:00 app[web.1]:  --> Installing Nginx 1.6.2 engine
2014-12-20T13:58:21.147891+00:00 app[web.1]:
2014-12-20T13:58:21.147903+00:00 app[web.1]: --------------------------
2014-12-20T13:58:21.147905+00:00 app[web.1]:
2014-12-20T13:58:21.156832+00:00 app[web.1]:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
2014-12-20T13:58:21.156839+00:00 app[web.1]:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
2014-12-20T13:58:24.837144+00:00 app[web.1]:      Compilation succesful. The logs are here:
2014-12-20T13:58:24.837151+00:00 app[web.1]:      /tmp/passenger_native_support-fmisb.log
2014-12-20T13:58:24.838239+00:00 app[web.1]:  --> passenger_native_support.so successfully loaded.
2014-12-20T13:58:24.918791+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/start_command/builtin_engine.rb:86:in `getgrgid': can't find group for 31893 (ArgumentError)
2014-12-20T13:58:24.918797+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/start_command/builtin_engine.rb:86:in `build_daemon_controller_options'
2014-12-20T13:58:24.918799+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/start_command/builtin_engine.rb:37:in `start_engine_real'
2014-12-20T13:58:24.918802+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/start_command.rb:506:in `start_engine'
2014-12-20T13:58:24.918804+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/start_command.rb:66:in `run'
2014-12-20T13:58:24.918806+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/lib/phusion_passenger/standalone/main.rb:50:in `run!'
2014-12-20T13:58:24.918808+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/gems/passenger-5.0.0.beta2/bin/passenger:44:in `<top (required)>'
2014-12-20T13:58:24.918810+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bin/passenger:23:in `load'
2014-12-20T13:58:24.918812+00:00 app[web.1]:    from /app/vendor/bundle/ruby/2.1.0/bin/passenger:23:in `<main>'
2014-12-20T13:58:25.736081+00:00 heroku[web.1]: Process exited with status 1
2014-12-20T13:58:25.747409+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by cwoodcox** [comment]
Is this gonna get released in another beta? I just updated to beta2 and it's totally busted on Heroku.

**Comment by FooBarWidget** [comment]
Yes it is. It's slated for beta 3, which isn't out yet.
