### ISSUE TITLE
Invalid argument - SIGKILL

### ISSUE THREAD

**Issue by surfi2000** [phusion/passenger#1362]
I'm using nginx/1.6.0 and passenger-4.0.38

I'm repeatedly getting the below error. When trying to access the web application I get a "502 Bad Gateway". In the error log the below repeats itself every couple of seconds

```

[ 2015-01-28 06:27:52.0600 20322/7f52328eb700 Pool2/Implementation.cpp:1045 ]: New process count = 1, remaining get waiters = 0
[ 2015-01-28 06:27:52.0600 20322/7f52328eb700 Pool2/Implementation.cpp:1070 ]: Spawn loop done
[ 2015-01-28 06:27:52.0601 20322/7f5235e1f700 Pool2/Pool.h:684 ]: Garbage collection time...
[ 2015-01-28 06:27:52.0601 20322/7f5235e1f700 Pool2/Pool.h:733 ]: Garbage collection done; next garbage collect in 299.948 sec
App 20348 stderr: [ 2015-01-28 06:27:52.0603 20529/0x00000000b3f3d0(Main thread) request_handler.rb:184 ]: Entering request handler main loop
App 20348 stderr: /opt/passenger/passenger-4.0.38/lib/phusion_passenger/request_handler.rb:363:in `trap'
App 20348 stderr: : 
App 20348 stderr: Invalid argument - SIGKILL
App 20348 stderr:  (
App 20348 stderr: Errno::EINVAL
App 20348 stderr: )
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/lib/phusion_passenger/request_handler.rb:363:in `block in reset_signal_handlers'
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/lib/phusion_passenger/request_handler.rb:361:in `each_key'
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/lib/phusion_passenger/request_handler.rb:361:in `reset_signal_handlers'
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/lib/phusion_passenger/request_handler.rb:185:in `main_loop'
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/helper-scripts/rack-preloader.rb:161:in `<module:App>'
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/helper-scripts/rack-preloader.rb:29:in `<module:PhusionPassenger>'
App 20348 stderr: 	from /opt/passenger/passenger-4.0.38/helper-scripts/rack-preloader.rb:28:in `<main>'
[ 2015-01-28 06:27:52.1081 20322/7f5235d7c700 Pool2/Implementation.cpp:1253 ]: Checking whether any of the 1 detached processes have exited...

```

**Comment by FooBarWidget** [comment]
This bug has already been fixed in a later version. Please upgrade to 4.0.58.

**Comment by lzap** [comment]
Which commit fixes it please? I can't find this... Grepping for `reset_signal_hander` gives me:

```
commit 92cd18e21d0e0ccc10e83e5446f919d15f8c965f
Author: Hongli Lai (Phusion) <hongli@phusion.nl>
Date:   Thu Feb 12 17:04:21 2015 +0100

    Use standard Ruby indenting style for Ruby source files

commit 030dcf825ab8994504b374bb8c16b871536268e4
Author: John Leach <john@johnleach.co.uk>
Date:   Wed Oct 24 20:16:29 2012 +0100

    Imported Upstream version 4.0.0~beta1

commit a87b1c8e677886de6d8621896ef8aa1fcbeed74f
Author: Hongli Lai (Phusion) <hongli@phusion.nl>
Date:   Wed Aug 1 13:28:22 2012 +0200

    Refactor Ruby request handler.

commit f99018a9c9a598b680f439a4a9492de19b5061b8
Author: John Leach <john@brightbox.co.uk>
Date:   Wed Jul 25 22:14:13 2012 +0100

    Imported Upstream version 4.0.0~e59e543

commit 58da925b103eb73f964d1e3ff478f0563e1c277d
Author: Hongli Lai (Phusion) <hongli@phusion.nl>
Date:   Sun Feb 26 00:33:27 2012 +0100

    Begin removing the old ApplicationPool and ApplicationSpawner code.

commit 3cc571eed88c91764dd1abafc54a257a946b5f72
Author: John Leach <john@brightbox.co.uk>
Date:   Tue Jul 6 14:35:35 2010 +0100

    Imported upstream version 2.2.15

commit 2ae21c0cfc88cba6d2dd2e433dd5b065b6b3c0e1
Author: John Leach <john@brightbox.co.uk>
Date:   Tue Jul 6 14:35:09 2010 +0100

    New upstream version, 2.2.15
```

**Comment by PaulSD** [comment]
https://github.com/phusion/passenger/commit/f9b9130ef3af46eeb3dcf4adc822edb81fed339f#diff-5026ad402256378368fcc43ef6b7e73a
