### ISSUE TITLE
POSTing file returns Exception NoMethodError in Rack application object (undefined method `force_encoding' for nil:NilClass)

### ISSUE THREAD

**Issue by whatasunnyday** [phusion/passenger#1374]
Hi,

I have an endpoint where our mobile application sends mobile logs. Every time someone posts a file to this endpoint, our application crashes.

We're on ruby 2.2.0, rails 4.2, passenger 4.0.57 on Heroku.The endpoint is grape mounted on rails. We're using paperclip to manage the endpoint.

This is our code:
```ruby
      resource :mobile_logs do
        desc 'Upload mobile logs to this end point.'
        post do
          ml = resource_owner.mobile_logs.build
          ml.log = params[:log] # The file should be under the log param.
          if ml.save
            ml
          else
            # Error handling logic.
          end
        end
```

This is the stacktrace:

```
2015-02-12T04:20:06.984428+00:00 app[web.1]: App 5486 stderr: [ 2015-02-12 04:20:06.9840 5508/0x007f5f21a005c8(Worker 1) utils.rb:84 ]: *** Exception NoMethodError in Rack application object (undefined method `force_encoding' for nil:NilClass) (process 5508, thread 0x007f5f21a005c8(Worker 1)):
2015-02-12T04:20:06.984472+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:194:in `tag_multipart_encoding'
2015-02-12T04:20:06.984494+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:74:in `block (2 levels) in parse'
2015-02-12T04:20:06.984516+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:249:in `get_data'
2015-02-12T04:20:06.984542+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:73:in `block in parse'
2015-02-12T04:20:06.984597+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:56:in `loop'
2015-02-12T04:20:06.984624+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart/parser.rb:56:in `parse'
2015-02-12T04:20:06.984665+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/multipart.rb:25:in `parse_multipart'
2015-02-12T04:20:06.984727+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/request.rb:373:in `parse_multipart'
2015-02-12T04:20:06.984767+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/request.rb:207:in `POST'
2015-02-12T04:20:06.984834+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:39:in `method_override_param'
2015-02-12T04:20:06.984840+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:27:in `method_override'
2015-02-12T04:20:07.014627+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:15:in `call'
2015-02-12T04:20:07.014639+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/runtime.rb:18:in `call'
2015-02-12T04:20:07.014641+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2015-02-12T04:20:07.014643+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
2015-02-12T04:20:07.014645+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/sendfile.rb:113:in `call'
2015-02-12T04:20:07.014648+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
2015-02-12T04:20:07.014649+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
2015-02-12T04:20:07.014652+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.57/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
2015-02-12T04:20:07.014654+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
2015-02-12T04:20:07.014655+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.57/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
2015-02-12T04:20:07.014657+00:00 app[web.1]: App 5486 stderr: 	from /app/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.57/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
2015-02-12T04:20:07.014661+00:00 app[web.1]: 2015/02/12 04:20:06 [error] 93#0: *1109 upstream prematurely closed connection while reading response header from upstream, client: 10.38.131.237, server: _, request: "POST /mobile_logs HTTP/1.1", upstream: "passenger:/tmp/passenger.1.0.73/generation-0/request:", host: "removed.com"
```

**Comment by whatasunnyday** [comment]
Sorry, I forgot to mention, the problem does not occur with Webrick on development.

**Comment by whatasunnyday** [comment]
Also, the average file size is under 10 kilobytes. I don't know if that matters.

**Comment by siruguri** [comment]
On further investigation we realized this was an issue on our side - sorry for the interruption!

**Comment by jhollida24** [comment]
Can you please elaborate!? We've started seeing this exact same issue in production all of a sudden.

**Comment by siruguri** [comment]
erk. @whatasunnyday - do you at all recollect what we found? It looks like I helped you debug but I have no memory of that :)

**Comment by whatasunnyday** [comment]
It was something very silly like us POSTing the wrong end point or wrong parameter name. Can't exactly recall tho.

**Comment by jhollida24** [comment]
We never did track it down, but a rollback to a previous revision seems to have stopped the bleeding. Thanks for the help.
