### ISSUE TITLE
Cannot use passenger-config restart-app

### ISSUE THREAD

**Issue by tirdadc** [phusion/passenger#1413]
No applications get listed when I run the command, and I get an error:
``` sh
passenger-config restart-app
Please select the application to restart.
Tip: re-run this command with --help to learn how to automate it.
If the menu doesn't display correctly, press '!'

*** ERROR: You are not authorized to query the status for this
```

when I try sudoing it:
``` sh
sudo passenger-config restart-app
[sudo] password for johndoe:
/home/johndoe/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:298:in `to_specs': Could not find 'passenger' (>= 0) among 5 total gem(s) (Gem::LoadError)
	from /home/johndoe/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:309:in `to_spec'
	from /home/johndoe/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb:47:in `gem'
	from /home/johndoe/.rvm/gems/ruby-1.9.3-p194/bin/passenger-config:22:in `<main>'
	from /home/johndoe/.rvm/gems/ruby-1.9.3-p194/bin/ruby_executable_hooks:15:in `eval'
	from /home/johndoe/.rvm/gems/ruby-1.9.3-p194/bin/ruby_executable_hooks:15:in `<main>'
```

I upgraded to 5.0.1 using the [Rubygems method](https://www.phusionpassenger.com/documentation/Users%20guide%20Apache.html#rubygems_generic_install). I'm sticking to using tmp/restart.txt anyway because of Capistrano integration, but it would be good to figure this out.

**Comment by dmitry** [comment]
@tirdadc use `rvmsudo` instead of plain `sudo` command.

**Comment by tirdadc** [comment]
Perfect, that worked, thank you!
