### ISSUE TITLE
[5.0.2] All workers stuck in Rack Exception

### ISSUE THREAD

**Issue by felixbuenemann** [phusion/passenger#1414]
After upgrading one of our servers to 5.0.2 we are seeing the following errors:
```
App 15686 stderr: [ 2015-03-09 11:23:55.6927 16170/0x000000027c5400(Worker 1) utils.rb:85 ]: *** Exception RuntimeError in Rack body object #each method (can't modify frozen String) (process 16170, thread 0x000000027c5400
(Worker 1)):
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:264:in `force_encoding'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:264:in `force_binary'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:178:in `block in process_body'
App 15686 stderr:       from /srv/www/schomburg-gmbh-frontend/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
App 15686 stderr:       from /srv/www/schomburg-gmbh-frontend/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
App 15686 stderr:       from /srv/www/schomburg-gmbh-frontend/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
App 15686 stderr:       from /srv/www/schomburg-gmbh-frontend/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
App 15686 stderr:       from /srv/www/schomburg-gmbh-frontend/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:177:in `process_body'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:103:in `process_request'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:414:in `block (3 levels) in start_threads'
App 15686 stderr:       from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
```

After some time this blocks up all workers and the server starts throwing 503 errors:
```
[ 2015-03-09 11:33:52.1094 11159/7fc999d83700 agents/HelperAgent/RequestHandler/CheckoutSession.cpp:236 ]: [Client 1-552] Returning HTTP 503 due to: Request queue full (configured max. size: 100)
[ 2015-03-09 11:33:53.9685 11159/7fc999582700 agents/HelperAgent/RequestHandler/CheckoutSession.cpp:236 ]: [Client 2-552] Returning HTTP 503 due to: Request queue full (configured max. size: 100)
[ 2015-03-09 11:33:57.1930 11159/7fc998d81700 agents/HelperAgent/RequestHandler/CheckoutSession.cpp:236 ]: [Client 3-552] Returning HTTP 503 due to: Request queue full (configured max. size: 100)
```

Pool status in stuck state:
```
Version : 5.0.2
Date    : 2015-03-09 11:51:35 +0100
Instance: W3sT24zH (nginx/1.6.2 Phusion_Passenger/5.0.2)

----------- General information -----------
Max pool size : 6
Processes     : 6
Requests in top-level queue : 0

----------- Application groups -----------
/srv/www/appname/web/staging/current/public (staging)#default:
  App root: /srv/www/appname/web/staging/current
  Requests in queue: 0
  * PID: 15657   Sessions: 0       Processed: 16      Uptime: 34m 51s
    CPU: 0%      Memory  : 242M    Last used: 29m 16s ago

/srv/www/appname/web/production/current/public (production)#default:
  App root: /srv/www/appname/web/production/current
  Requests in queue: 100
  * PID: 11217   Sessions: 1       Processed: 1416    Uptime: 1h 45m 9s
    CPU: 2%      Memory  : 309M    Last used: 27m 41s a
  * PID: 15709   Sessions: 1       Processed: 9       Uptime: 34m 29s
    CPU: 0%      Memory  : 145M    Last used: 27m 41s ago
  * PID: 15850   Sessions: 1       Processed: 1       Uptime: 31m 28s
    CPU: 0%      Memory  : 107M    Last used: 27m 41s ago
  * PID: 16158   Sessions: 1       Processed: 0       Uptime: 27m 44s
    CPU: 0%      Memory  : 94M     Last used: 27m 41s ago
  * PID: 16170   Sessions: 1       Processed: 0       Uptime: 27m 40s
    CPU: 0%      Memory  : 94M     Last used: 27m 40s ago
```

For now I've switched to the v4 PPA and downgraded to 4.0.59 which is not affected.

**Comment by FooBarWidget** [comment]
In Passenger 5 we call `force_encoding("binary")` on body strings in order to prevent encoding problems. But looks like some apps return frozen strings and so we can't do that. :(

But maybe we don't have to force the string to binary. Maybe it works OK even if we write the string directly over the socket.

**Comment by felixbuenemann** [comment]
If it matters the app is running on rails 4.1.9 with the following middleware stack:
```ruby
use Airbrake::UserInformer
use Rack::Sendfile
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x00000008605b50>
use Rack::Runtime
use Dragonfly::CookieMonster
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Airbrake::Rails::Middleware
use ActionDispatch::RemoteIp
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::Deflater
use Rack::ETag
use HttpAcceptLanguage::Middleware
run Appname::Application.routes
```
Middleware gems:
```
airbrake (4.1.0)
dragonfly (1.0.7)
rack (1.5.2)
rack-cache (1.2)
rack-contrib (1.1.0)
rack-test (0.6.3)
rails (4.1.9)
```

**Comment by FooBarWidget** [comment]
Fixed.

**Comment by felixbuenemann** [comment]
Great! I'll test it as soon as 5.0.3 is released.
