### ISSUE TITLE
meteor error with passenger

### ISSUE THREAD

**Issue by xurwxj** [phusion/passenger#1449]
we got a error with passenger on meteor app:
```
App 11522 stdout: I20150322-21:55:33.168(8)? Exception from task: Error: ENOENT, open '../web.browser/head.html'
App 11522 stdout: I20150322-21:55:33.170(8)?     at Object.Future.wait (/Users/victor/.meteor/packages/meteor-tool/.1.0.44.1d3casd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
App 11522 stdout: I20150322-21:55:33.170(8)?     at packages/meteor/helpers.js:119:1
App 11522 stdout: I20150322-21:55:33.170(8)?     at readUtf8FileSync (packages/boilerplate-generator/boilerplate-generator.js:6:1)
App 11522 stdout: I20150322-21:55:33.170(8)?     at packages/boilerplate-generator/boilerplate-generator.js:81:1
App 11522 stdout: I20150322-21:55:33.171(8)?     at Array.forEach (native)
App 11522 stdout: I20150322-21:55:33.171(8)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
App 11522 stdout: I20150322-21:55:33.171(8)?     at [object Object].Boilerplate._generateBoilerplateFromManifestAndSource (packages/boilerplate-generator/boilerplate-generator.js:63:1)
App 11522 stdout: I20150322-21:55:33.171(8)?     at new Boilerplate (packages/boilerplate-generator/boilerplate-generator.js:16:1)
App 11522 stdout: I20150322-21:55:33.172(8)?     at Object.WebAppInternals.generateBoilerplateInstance (packages/webapp/webapp_server.js:285:1)
App 11522 stdout: I20150322-21:55:33.172(8)?     at packages/webapp/webapp_server.js:553:1
App 11522 stdout: I20150322-21:55:33.172(8)?     - - - - -
```
passenger run as:

```
passenger start --port 8000 --min-instances 2 --sticky-sessions
```

same app runs no error with meteor's run command.

env:
meteor: 1.0.4.2
Phusion Passenger version 4.0.59
osx 10.10
node: v0.12.0

**Comment by FooBarWidget** [comment]
Maybe this is related to the working directory.  Where did you invoke 'passenger start', and where is 'web.browser/head.html' located?

**Comment by xurwxj** [comment]
i run 'passenger start' directly under project directory which no problem with meteor's run command.

**Comment by FooBarWidget** [comment]
But where is your project direct located? What is its path? What is the full path to web.browser/head.html?

**Comment by xurwxj** [comment]
project directory: /Users/victor/WebstormProjects/3dker
run with above directory.

get error

**Comment by FooBarWidget** [comment]
What is the full path to web.browser/head.html?

**Comment by xurwxj** [comment]
/Users/victor/WebstormProjects/3dker/.meteor/local/build/programs/web.browser/head.html

**Comment by xurwxj** [comment]
happen when client modified to refreshing under development envir.
