### ISSUE TITLE
Passenger 5.0.6 Standalone --nginx-version flag crashes passenger start

### ISSUE THREAD

**Issue by mikechau** [phusion/passenger#1490]
Hi, I'm trying to the pass the `--nginx-version` flag to `passenger start`, like so:

```
bundle exec passenger start --nginx-version 1.7.9
```

Immediately, I get back:

```
The Phusion Passenger agent is already installed.

 --> Installing Nginx 1.7.9 engine
     The Nginx engine (version 1.6.2) is already installed.

/Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:620:in `spawn': No such file or directory - -c (Errno::ENOENT)
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:620:in `run_command'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:426:in `spawn_daemon'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:360:in `block in start_without_locking'
  from /Users/workstation-01/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
  from /Users/workstation-01/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `call'
  from /Users/workstation-01/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:358:in `start_without_locking'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:220:in `block in start'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller/lock_file.rb:68:in `block in exclusive_lock'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller/lock_file.rb:63:in `open'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller/lock_file.rb:63:in `exclusive_lock'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/vendor/daemon_controller.rb:219:in `start'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/standalone/start_command/nginx_engine.rb:44:in `start_engine_real'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/standalone/start_command.rb:557:in `start_engine'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/standalone/start_command.rb:67:in `run'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/lib/phusion_passenger/standalone/main.rb:50:in `run!'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/gems/passenger-5.0.6/bin/passenger:44:in `<top (required)>'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/bin/passenger:23:in `load'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/bin/passenger:23:in `<main>'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/bin/ruby_executable_hooks:15:in `eval'
  from /Users/workstation-01/.rvm/gems/ruby-2.2.0@app/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by FooBarWidget** [comment]
This has been fixed. Thanks for reporting.
