### ISSUE TITLE
Permission problems with rails directory on NFS

### ISSUE THREAD

**Issue by mdj2** [phusion/passenger#1567]
When mod_passenger is used in an environment where the user starting the apache process (typically root) does not have full file system privileges (e.g. on NFS mounts), it cannot change to the directory where the app lives (in certain circumstances).

For example:

1. `/foo` is an NFS mount owned and grouped to foo:foo. The privileges are 770
1. There is a `User foo` and `Group foo` directive in the Apache configuration file
1. The rails app is located in /foo

When you try to start Apache (as root), and load the application, you get something like:

```
*** Exception Errno::EACCES in spawn manager (Permission denied - /vol/www/foo/htdocs) (process 17162, thread #<Thread:0x7f054c31d370>):
        from /usr/lib/ruby/1.8/pathname.rb:441:in `lstat'
        from /usr/lib/ruby/1.8/pathname.rb:441:in `realpath_rec'
        from /usr/lib/ruby/1.8/pathname.rb:474:in `realpath'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/utils.rb:58:in `canonicalize_path'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/classic_rails/application_spawner.rb:120:in `initialize'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:201:in `new'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:201:in `spawn_rails_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:215:in `call'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:215:in `spawn_rails_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server_collection.rb:132:in `lookup_or_add'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:214:in `spawn_rails_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server_collection.rb:82:in `synchronize'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server_collection.rb:79:in `synchronize'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:213:in `spawn_rails_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:132:in `spawn_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/spawn_manager.rb:275:in `handle_spawn_application'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server.rb:357:in `__send__'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server.rb:357:in `server_main_loop'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/lib/phusion_passenger/abstract_server.rb:206:in `start_synchronously'
        from /usr/lib/ruby/gems/1.8/gems/passenger-3.0.21/helper-scripts/passenger-spawn-server:102
```

It seems like mod_passenger should switch users before changing directories, because the user it switches to may have more privileges.

I'm using mod_passenger 3.0.21.

<a href="https://github.com/GrahamDumpleton/mod_wsgi/issues/56">I reported a similar problem in mod_wsgi</a>

**Comment by OnixGH** [comment]
Please try with a newer version of Passenger, which has many improvements. Versions below 4 are not supported anymore anyway (current stable version is 5).
