### ISSUE TITLE
Incompatibility with 'packable' gem

### ISSUE THREAD

**Issue by al3x-edge** [phusion/passenger#1599]
Tried looking around for something similar, but not able to determine possible issues.  Application run fine with Thin using `bundle exec thin -R config.ru -p 9000` -- Only thing I notice is that deprecations are displayed from Packable.

```
$ passenger-config about version
Phusion Passenger 5.0.16
```
```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
```

```
App 2817 stderr: [ 2015-09-02 10:22:32.5501 2834/0x007fdbbf43e1d8(Worker 1) utils.rb:85 ]: *** Exception TypeError in Passenger RequestHandler's client socket (Expected a class or symbol: 4) (process 2834, thread 0x007fdbbf43e1d8(Worker 1)):
App 2817 stderr: 	from /var/www/asdfzxy/shared/bundle/ruby/2.2.0/gems/packable-1.3.6/lib/packable/packers.rb:56:in `to_class_option_list'
App 2817 stderr: 	from /var/www/asdfzxy/shared/bundle/ruby/2.2.0/gems/packable-1.3.6/lib/packable/extensions/io.rb:67:in `read_with_packing'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/unseekable_socket.rb:188:in `read'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/message_channel.rb:177:in `read_scalar'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:217:in `parse_session_request'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:143:in `accept_and_process_next_request'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:415:in `block (3 levels) in start_threads'
App 2817 stderr: 	from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:111:in `block in create_thread_and_abort_on_exception'
[ 2015-09-02 10:22:32.5504 1947/7f4e3d6de700 age/Cor/Req/Utils.cpp:95 ]: [Client 1-3] Sending 502 response: application did not send a complete response
``

**Comment by FooBarWidget** [comment]
This is not a Passenger problem. It is a bug in the [packable](https://github.com/marcandre/packable) gem, which your application uses. Passenger calls `IO#read(number_of_bytes, buffer)`, but packable does not support this variant of the read call:

~~~
$ irb -rpackable
>> a, b = IO.pipe
=> [#<IO:fd 5>, #<IO:fd 6>]
>> b.write('hi')
=> 2
>> buffer = ''
=> ""
>> a.read(1, buffer)
TypeError: Expected a class or symbol: 1
~~~

Please report this bug to the packable author.

**Comment by al3x-edge** [comment]
Thanks for the report @FooBarWidget -- Appreciate it. We'll track down further from here.
