### ISSUE TITLE
Union Station Ruby hooks: make initializer check non-fatal

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#1639]
Passenger currently refuses to spawn a Ruby application if Union Station support is turned on, but the application does not call `UnionStationHooks.initialize!`. We should make this check non-fatal in order to avoid downtime. Instead of aborting on startup, a message should be sent to Union Station so that the user is presented with a warning message in the UI.

This message should be sent under a new `internal_information` category. An internal_information should contain a machine-treatable type name as well as a user-facing message (which may or may not be honored by Union Station) that is generated by Passenger. Example:

~~~json
{ "type": "HOOKS_NOT_INITIALIZED", "message": "Please ensure that config/initializers/union_station.rb exists", "data": { "app_type": "ruby", "framework_type": "rails" } }
~~~

See also Union Station indexer issue 11.

**Comment by OnixGH** [comment]
I still get a fatal error, using the latest stable + submodules: "can't modify frozen Array".

If I add the file, the warning and error disappear.
Ruby 2.2.1, Rails 4.1.4.

```
App 6933 stdout: 
App 6933 stderr:  *** WARNING: The Union Station hooks are not initialized. Please ensure that you have an initializer file `config/initializers/union_station.rb` in which you call this:
App 6933 stderr: 
App 6933 stderr:   if defined?(UnionStationHooks)
App 6933 stderr:     UnionStationHooks.initialize!
App 6933 stderr:   end
App 6933 stderr: 
App 6933 stdout: 
[ 2015-11-28 17:12:58.0521 6886/7f1088767700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/onix/apps/rails/railsgirls: An error occurred while starting up the preloader.
  Error ID: edir0-JWnb0YfyXDl
  Error details saved to: /tmp/passenger-error-2epM9D.html
  Message from application: can't modify frozen Array (RuntimeError)
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:90:in `insert'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:90:in `insert'
  /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.1.4/lib/action_dispatch/middleware/stack.rb:97:in `insert_after'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_rails/lib/union_station_hooks_rails/exception_logger.rb:54:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `block in require'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:232:in `load_dependency'
  /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.1.4/lib/active_support/dependencies.rb:247:in `require'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_rails/lib/union_station_hooks_rails.rb:148:in `require_lib'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_rails/lib/union_station_hooks_rails.rb:94:in `initialize!'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core/api.rb:184:in `block in initialize_other_union_station_hooks_gems'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core/api.rb:183:in `each'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core/api.rb:183:in `initialize_other_union_station_hooks_gems'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core.rb:169:in `initialize!'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/vendor/union_station_hooks_core/lib/union_station_hooks_core.rb:302:in `check_initialized'
  /home/onix/git/passenger/src/ruby_supportlib/phusion_passenger/loader_shared_helpers.rb:316:in `after_loading_app_code'
  /home/onix/git/passenger/src/helper-scripts/rack-preloader.rb:113:in `preload_app'
  /home/onix/git/passenger/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /home/onix/git/passenger/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /home/onix/git/passenger/src/helper-scripts/rack-preloader.rb:29:in `<main>'
```
