### ISSUE TITLE
Upgrade to El Capitan and passenger won't start

### ISSUE THREAD

**Issue by phedinkus** [phusion/passenger#1644]
I upgraded my Mac OS today to El Capitan and now I can't start my local passenger server. At first I had problems with openssl but was able to fix them from comments on issue https://github.com/phusion/passenger/issues/1630.

The following is the error output I get:

```
▶ passenger start
 --> Downloading Phusion Passenger support binaries for your platform
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/4.0.58/support-x86_64-macosx-10.11.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/4.0.58/support-x86_64-macosx-10.11.tar.gz: The requested URL returned error: 403 Forbidden
     No binaries are available for your platform. Will compile them from source
 --> Downloading web helper for your platform
     Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/4.0.58/webhelper-1.6.2-x86_64-macosx-10.11.tar.gz: The requested URL returned error: 404 Not Found
     Trying next mirror...
     Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/4.0.58/webhelper-1.6.2-x86_64-macosx-10.11.tar.gz: The requested URL returned error: 403 Forbidden
     No binary is available for your platform. Will compile it from source.

Checking for required software...

 * Checking for C compiler...
      Found: yes
      Location: /usr/bin/cc
 * Checking for C++ compiler...
      Found: yes
      Location: /usr/bin/c++
 * Checking for GNU make...
      Found: yes
      Location: /usr/bin/make
 * Checking for OpenSSL support for Ruby...
      Found: yes
 * Checking for RubyGems...
      Found: yes
 * Checking for Rake (associated with /Users/kt/.rbenv/versions/2.0.0-p451/bin/ruby)...
      Found: yes
      Location: /Users/kt/.rbenv/versions/2.0.0-p451/bin/ruby /Users/kt/.rbenv/versions/2.0.0-p451/bin/rake
 * Checking for rack...
      Found: yes
 * Checking for Curl development headers with SSL support...
      Found: yes
      curl-config location: /usr/bin/curl-config
      Header location: /usr/include/curl/curl.h
      Version: libcurl 7.43.0
      Usable: yes
      Supports SSL: yes
 * Checking for OpenSSL development headers...
      Found: yes
      Location: /usr/local/opt/openssl/include/openssl/ssl.h
 * Checking for Zlib development headers...
      Found: yes
      Location: /usr/include/zlib.h
 * Checking for PCRE development headers...
      Found: yes
      Location: /usr/local/include/pcre.h
 * Checking for daemon_controller >= 1.1.0...
      Found: yes
      Installed version: 1.2.0

Installing Phusion Passenger Standalone...
Downloading web helper source code...
[********************************             ] Compiling Phusion Passenger...
*** ERROR: the following command failed:
rake aborted!
Command failed with status (2): [cd /Users/kt/.passenger/standalone/4.0.58/...]
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `call'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils.rb:57:in `sh'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:37:in `sh'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/passenger-4.0.58/build/common_library.rb:143:in `block in <top (required)>'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/kt/.rbenv/versions/2.0.0-p451/lib/ruby/gems/2.0.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/kt/.rbenv/versions/2.0.0-p451/bin/rake:23:in `load'
/Users/kt/.rbenv/versions/2.0.0-p451/bin/rake:23:in `<main>'
Tasks: TOP => nginx_without_native_support => /Users/kt/.passenger/standalone/4.0.58/support-x86_64-macosx-10.11/agents/PassengerHelperAgent => /Users/kt/.passenger/standalone/4.0.58/support-x86_64-macosx-10.11/libev/.libs/libev.a
```

**Comment by FooBarWidget** [comment]
@katie 4.0.45 did not have binaries for os x yosemity or later. Try 5.0.20.

I am trying to upgrade to el capitan in an effort to reproduce the problem.
Unfortunately the el capitain installer crashes midway, so i am forced to
restore my system from backup which will take a day. This is already my
second attempt.

To be continued...

**Comment by phedinkus** [comment]
@FooBarWidget That did it! Thanks!
