### ISSUE TITLE
Passenger Standalone with unix socket and passenger_pre_start

### ISSUE THREAD

**Issue by zerbons** [phusion/passenger#1668]
Using Passenger Standalone and while listening on unix socket, there seems to be a routing error on startup:

```
vagrant@vagrant-ubuntu-trusty-64:~/rails_app/current$ RAILS_ENV=production bundle exec passenger start -S rails_1.socket
=============== Phusion Passenger Standalone web server started ===============
PID file: /home/vagrant/rails_app/current/tmp/pids/passenger.pid
Log file: /home/vagrant/rails_app/current/log/passenger.log
Environment: production
Accessible via: unix:/home/vagrant/rails_app/current/rails_1.socket

You can stop Phusion Passenger Standalone by pressing Ctrl-C.
Problems? Check https://www.phusionpassenger.com/library/admin/standalone/troubleshooting/
===============================================================================
App 16787 stdout: 
App 16803 stdout: 
I, [2015-11-15T04:27:57.128558 #16803]  INFO -- : Started HEAD "/home/vagrant/rails_app/current/rails_1.socket" for unix: at 2015-11-15 04:27:57 +0000
F, [2015-11-15T04:27:57.147248 #16803] FATAL -- : 
ActionController::RoutingError (No route matches [HEAD] "/home/vagrant/rails_app/current/rails_1.socket"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  passenger (5.0.21) src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  passenger (5.0.21) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
  passenger (5.0.21) src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  passenger (5.0.21) src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
  passenger (5.0.21) src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

If you make subsequent requests everything seems to be fine. Does `passenger_pre_start` work when listening on unix sockets or is it not needed?

**Comment by kriansa** [comment]
This is not related to unix socket itself. I used to use passenger standalone listening to a socket and I had no problem then.

This routing error is due to the `passenger_pre_start` directive. The way that Passenger pre-starts you application is doing a HTTP `HEAD /` request in your app. If your app does not know how to handle this route, it will fail, just like any routing error.

You should create a route in your Rails app, like:

```ruby
  root to: 'index#healthcheck', via: :head
```

Read more in https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_pre_start

**Comment by OnixGH** [comment]
Thanks for the reply on this @kriansa, a good answer to @zerbons question! (closing due to not-a-passenger-issue)
