### ISSUE TITLE
Cannot download passenger for ruby 2.2.3

### ISSUE THREAD

**Issue by obfuscoder** [phusion/passenger#1684]
After upgrading to ruby 2.2.3 and deploying to my server, the web application running on Passenger does not start up.

In the apache logs I get the following:

```
App 12697 stdout: 
App 12697 stderr:  --> Compiling passenger_native_support.so for the current Ruby interpreter...
App 12697 stderr: 
App 12697 stderr:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 12697 stderr:      Warning: compilation didn't succeed. To learn why, read this file:
App 12697 stderr: 
App 12697 stderr:      /tmp/passenger_native_support-kzuaky.log
App 12697 stderr:  --> Downloading precompiled passenger_native_support.so for the current Ruby interpreter...
App 12697 stderr:      (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
App 12697 stderr:      Could not download https://oss-binaries.phusionpassenger.com/binaries/passenger/by_release/5.0.21/rubyext-ruby-2.2.3-x86_64-linux.tar.gz: The requested URL returned error: 404 Not Found
App 12697 stderr:      Trying next mirror...
App 12697 stderr:      Could not download https://s3.amazonaws.com/phusion-passenger/binaries/passenger/by_release/5.0.21/rubyext-ruby-2.2.3-x86_64-linux.tar.gz: The requested URL returned error: 403 Forbidden
App 12697 stderr:  --> Continuing without passenger_native_support.so.
App 12697 stdout: 
[ 2015-11-30 11:20:09.8661 12535/7f869f01c700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/flohmarkthelfer/www/current: An error occured while starting up the preloader.
  Error ID: 22586c50
  Error details saved to: /tmp/passenger-error-qXXp7V.html
  Message from application: cannot load such file -- bundler/setup (LoadError)
  /home/flohmarkthelfer/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /home/flohmarkthelfer/.rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:430:in `activate_gem'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:297:in `block in run_load_path_setup_code'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:435:in `running_bundler'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:296:in `run_load_path_setup_code'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:100:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ 2015-11-30 11:20:09.8813 12535/7f86935fe700 age/Cor/Req/CheckoutSession.cpp:253 ]: [Client 2-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 22586c50. Please see earlier logs for details about the error.
```

It seems the passenger binaries are not available.

**Comment by OnixGH** [comment]
@obfuscoder it looks like you're confusing two separate error messages. Native support is good to have but not required for passenger to work. The spawn error is something else, it means there's something wrong with your application, you should check out `/tmp/passenger-error-qXXp7V.html`.

**Comment by OnixGH** [comment]
Just as a hint: after going to 2.2.3 you probably needed to `gem install bundler` and `bundle install` in your app folder.
