### ISSUE TITLE
Compilation Problem on Solaris

### ISSUE THREAD

**Issue by daqo** [phusion/passenger#1691]
Running passenger-install-apache2-module results in an error: 

```
Which languages are you interested in?

Use <space> to select.
If the menu doesn't display correctly, press '!'

 ‣ ⬢  Ruby
   ⬡  Python
   ⬡  Node.js
   ⬡  Meteor

--------------------------------------------

Checking for required software...

 * Checking for C compiler...
      Found: yes
      Location: /usr/local/bin/cc
 * Checking for C++ compiler...
      Found: yes
      Location: /usr/local/bin/c++
 * Checking for Curl development headers with SSL support...
      Found: yes
      curl-config location: /usr/local/bin/curl-config
      Header location: /usr/local/include/curl/curl.h
      Version: libcurl 7.31.0
      Usable: yes
      Supports SSL: yes
 * Checking for Zlib development headers...
      Found: yes
      Location: /usr/local/include/zlib.h
 * Checking for Apache 2...
      Found: yes
      Location of httpd: /usr/local/bin/httpd
      Apache version: 2.2.15
 * Checking for Apache 2 development headers...
      Found: yes
      Location of apxs2: /usr/local/bin/apxs
 * Checking for Rake (associated with /tools/stow/ruby-1_9_3-p551.ssl.4.i386.solaris.5_10/bin/ruby)...
      Found: yes
      Location: /tools/stow/ruby-1_9_3-p551.ssl.4.i386.solaris.5_10/bin/ruby /usr/local/bin/rake
 * Checking for OpenSSL support for Ruby...
      Found: yes
 * Checking for RubyGems...
      Found: yes
 * Checking for Ruby development headers...
      Found: yes
      Location: /tools/stow/ruby-1_9_3-p551.ssl.4.i386.solaris.5_10/include/ruby-1.9.1/ruby.h
 * Checking for rack...
      Found: yes
 * Checking for Apache Portable Runtime (APR) development headers...
      Found: yes
      Location: /usr/local/bin/apr-1-config
      Version: 1.3.12
 * Checking for Apache Portable Runtime Utility (APU) development headers...
      Found: yes
      Location: /usr/local/bin/apu-1-config
      Version: 1.3.9

--------------------------------------------
....
....
....
src/apache2_module/Hooks.cpp:1730: warning: visibility attribute not supported in this configuration; ignored
src/apache2_module/Hooks.cpp:1730: warning: visibility attribute not supported in this configuration; ignored
c++ -shared buildout/apache2/mod_passenger.o buildout/apache2/Configuration.o buildout/apache2/Bucket.o buildout/apache2/Hooks.o -fPIC -o buildout/apache2/mod_passenger.so buildout/apache2/module_libpassenger_common/Logging.o buildout/apache2/module_libpassenger_common/Exceptions.o buildout/apache2/module_libpassenger_common/Utils/SystemTime.o buildout/apache2/module_libpassenger_common/Utils/StrIntUtils.o buildout/apache2/module_libpassenger_common/Utils/StrIntUtilsNoStrictAliasing.o buildout/apache2/module_libpassenger_common/Utils/IOUtils.o buildout/apache2/module_libpassenger_common/Utils.o buildout/apache2/module_libpassenger_common/vendor-modified/modp_b64.o buildout/apache2/module_libpassenger_common/AppTypes.o buildout/apache2/module_libboost_oxt.a -L/usr/local/lib -R/usr/local/lib -fPIC -DSOLARIS2=10 -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D_LARGEFILE64_SOURCE -I/usr/local/include/apr-1 -I/usr/local/include/apr-1 -fPIC -g -I/usr/local/include/apache2 -L/usr/local/lib -lapr-1 -L/usr/local/lib -laprutil-1 -lxnet -lsocket -lnsl -lpthread -lrt
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_alloc_>()::ep: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol boost::exception_ptr boost::exception_detail::get_static_exception_object<boost::exception_detail::bad_exception_>()::ep: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_exception_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol guard variable for boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol boost::exception_detail::exception_ptr_static_exception_object<boost::exception_detail::bad_alloc_>::e: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
ld: fatal: relocation error: R_386_GOTOFF: file buildout/apache2/Configuration.o: symbol Passenger::serverConfig: a GOT relative relocation must reference a local symbol
collect2: ld returned 1 exit status
rake aborted!
Command failed with status (1): [c++ -shared buildout/apache2/mod_passenger.o buildout/apache2/Configuration.o buildout/apache2/Bucket.o buildout/apache2/Hooks.o -fPIC -o buildout/apache2/mod_passenger.so buildout/apache2/module_libpassenger_common/Logging.o buildout/apache2/module_libpassenger_common/Exceptions.o buildout/apache2/module_libpassenger_common/Utils/SystemTime.o buildout/apache2/module_libpassenger_common/Utils/StrIntUtils.o buildout/apache2/module_libpassenger_common/Utils/StrIntUtilsNoStrictAliasing.o buildout/apache2/module_libpassenger_common/Utils/IOUtils.o buildout/apache2/module_libpassenger_common/Utils.o buildout/apache2/module_libpassenger_common/vendor-modified/modp_b64.o buildout/apache2/module_libpassenger_common/AppTypes.o buildout/apache2/module_libboost_oxt.a -L/usr/local/lib -R/usr/local/lib -fPIC -DSOLARIS2=10 -D_POSIX_PTHREAD_SEMANTICS -D_REENTRANT -D_LARGEFILE64_SOURCE -I/usr/local/include/apr-1 -I/usr/local/include/apr-1 -fPIC -g -I/usr/local/include/apache2 -L/usr/local/lib -lapr-1 -L/usr/local/lib -laprutil-1 -lxnet -lsocket -lnsl -lpthread -lrt]
/tools/stow/rb_passenger-5_0_21.ruby-1_9_3-ssl.i386.solaris.5_10/lib/ruby/gems/gems/passenger-5.0.21/build/cplusplus_support.rb:52:in `run_compiler'
/tools/stow/rb_passenger-5_0_21.ruby-1_9_3-ssl.i386.solaris.5_10/lib/ruby/gems/gems/passenger-5.0.21/build/cplusplus_support.rb:147:in `create_shared_library'
/tools/stow/rb_passenger-5_0_21.ruby-1_9_3-ssl.i386.solaris.5_10/lib/ruby/gems/gems/passenger-5.0.21/build/apache2.rb:100:in `block in <top (required)>'
Tasks: TOP => apache2 => buildout/apache2/mod_passenger.so
(See full trace by running task with --trace)
```

Specs:

Ruby version 1.9.3.
Passenger version 5.0.21.

Any advice.

**Comment by FooBarWidget** [comment]
That looks like a problem with your compiler toolchain. Can you try using GCC instead of Sun Studio to compile Passenger?

**Comment by daqo** [comment]
I am using GCC.
```
* Checking for C compiler...
      Found: yes
      Location: /usr/local/bin/cc
 * Checking for C++ compiler...
      Found: yes
      Location: /usr/local/bin/c++
```

and running /usr/local/bin/cc -v returns:
```
# /usr/local/bin/cc -v
Using built-in specs.
Target: i386-pc-solaris2.10
Configured with: /remediation/build/5.10-x86/compile/gcc-4.3.6/configure --prefix=/usr/local --with-gnu-as --with-as=/usr/local/bin/as --without-gnu-ld --with-ld=/usr/ccs/bin/ld --enable-languages=c,c++,objc,obj-c++,fortran --disable-shared --with-pic --with-gmp=/usr/local --with-mpfr=/usr/local
Thread model: posix
gcc version 4.3.6 (GCC)
```

**Comment by FooBarWidget** [comment]
Then I am afraid I do not know how to solve your problem. The error indicates an issue in the compiler toolchain. Maybe a Solaris support forum can help you.

**Comment by daqo** [comment]
Thank you and no problem. If I find a fix for the problem, will post it here.

**Comment by daqo** [comment]
Quick question, how can I force passenger to compile without gcc visibility attribute? Like `./configure disable-visibility`

**Comment by FooBarWidget** [comment]
There isn't. But why do you want to disable the visibility attribute? Is that the cause of the compilation problem?

**Comment by daqo** [comment]
Yes. 
It’s because our corporate's gcc is designed to use the gnu as but the solaris ld and that affects how the visibility stuff works, but if I can force passenger to compile with disable-visibility probably it's gonna work.

**Comment by FooBarWidget** [comment]
You could try setting the environment variables `EXTRA_CFLAGS` and `EXTRA_CXXFLAGS` to `-fvisibility=default`, in order to override the visibility that Passenger tries to set by default.

**Comment by daqo** [comment]
Thank you. It worked!
Last week I tried to supply -fvisibility=default to CFLAGS and CPPFLAGS but it didn't work. Apparently I needed to use EXTRA_CFLAGS and EXTRA_CXXFLAGS.

Just for the records, after disabling visibility=hidden everything passed through but other problems did raise. 

* Apparently in Solaris mkdtemp function is not defined. I defined my own and used it in src/agent/Core/SpawningKit/Spawner.h.
* posix_memalign was not declared in Solaris 10. As a result I switched to memalign.

**Comment by OnixGH** [comment]
@daqo would you be willing to submit a pull request with your adjustments (mkdtemp and memalign switch)?

To limit the effect to your Solaris version you can:
- set `-D` flag(s) in `src/ruby_supportlib/phusion_passenger/platform_info/cxx_portability.rb`
(see `default_extra_c_or_cxxflags` for examples)
- `#ifdef` on the flags to select the alternate code

**Comment by daqo** [comment]
@OnixGH For sure. I am a little busy right now but I will open some slot during the weekend to submit a pull request.

**Comment by OnixGH** [comment]
:+1:

**Comment by OnixGH** [comment]
@daqo any update?

**Comment by OnixGH** [comment]
Closing due to inactivity.
