### ISSUE TITLE
Unable to compile support libraries for passenger open source 4.0.60 on OSX 10.10.5

### ISSUE THREAD

**Issue by PikachuEXE** [phusion/passenger#1696]
I am trying to run passenger open source 4.0.60 on OSX 10.10.5

The [4.x source code of libev extension](https://github.com/phusion/passenger/blob/stable-4.0/ext/libev/ev.c#L772) contains the following code:
```
#if ECB_C11
  #define ecb_noreturn   _Noreturn
#else
  #define ecb_noreturn   ecb_attribute ((__noreturn__))
#endif
```
If I change the code manually to the following, the error will disappear when compiling again
```
#define ecb_noreturn   ecb_attribute ((__noreturn__))
```
I have also found another similar code for [4.x source code of libeio extension](https://github.com/phusion/passenger/blob/stable-4.0/ext/libeio/ecb.h#L277)

I have also tried this on OSX 10.11.1 (on another computer)

Some info that might be useful:
```
$ which cc
/usr/bin/cc

$ which gcc
/usr/bin/gcc

$ cc -v
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by OnixGH** [comment]
Can you post the error message(s) as well?

**Comment by PikachuEXE** [comment]
```
Installing Phusion Passenger Standalone...
Downloading web helper source code...
[*********************************            ] Compiling Phusion Passenger...
*** ERROR: the following command failed:
rake aborted!
Command failed with status (2): [cd /Users/PikachuEXE/.passenger/standalone...]
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:66:in `block in create_shell_runner'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:57:in `call'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils.rb:57:in `sh'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/file_utils_ext.rb:37:in `sh'
/Users/PikachuEXE/.rvm/gems/ruby-2.2.3/gems/passenger-4.0.60/build/common_library.rb:198:in `block in <top (required)>'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/PikachuEXE/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/PikachuEXE/.rvm/gems/ruby-2.2.3/bin/rake:23:in `load'
/Users/PikachuEXE/.rvm/gems/ruby-2.2.3/bin/rake:23:in `<main>'
Tasks: TOP => nginx_without_native_support => /Users/PikachuEXE/.passenger/standalone/4.0.60/support-x86_64-macosx-10.10/agents/PassengerHelperAgent => /Users/PikachuEXE/.passenger/standalone/4.0.60/support-x86_64-macosx-10.10/libeio/.libs/libeio.a
```

**Comment by FooBarWidget** [comment]
Looks like I forgot to apply the ecb change from #1673.

**Comment by kriansa** [comment]
It looks like this issue has been resolved, as states #1673.

**Comment by PikachuEXE** [comment]
@kriansa 
I am aware of that issue.
And this issue is reproducible even now (I have just tried again)

**Comment by OnixGH** [comment]
@PikachuEXE @kriansa yes, like @FooBarWidget said, the patch fixes it but it's not in stable yet. Should be at the next release.

**Comment by OnixGH** [comment]
The patch is in 4.x stable, that can be used from source or whenever there is another 4.x release (low priority).
