### ISSUE TITLE
Passenger python wsgi loader uses _socketobject and _fileobject in incompatible with PyPy way 

### ISSUE THREAD

**Issue by msva** [phusion/passenger#1731]
Hi!

When using passenger with app under PyPy, there is a warning in passenger global log file:
```
App 18286 stdout:
App 18286 stderr: [ pid=18286, time=2016-01-23 10:58:49,126 ]: /usr/libexec/passenger/helper-scripts/wsgi-loader.py:222: RefCountingWarning: '_socketobject' object has no _reuse/_drop methods
App 18286 stderr: {{
App 18286 stderr:     You make use (or a library you are using makes use) of the internal
App 18286 stderr:     classes '_socketobject' and '_fileobject' in socket.py, initializing
App 18286 stderr:     them with custom objects.  On PyPy, these custom objects need two
App 18286 stderr:     extra methods, _reuse() and _drop(), that maintain an explicit
App 18286 stderr:     reference counter.  When _drop() has been called as many times as
App 18286 stderr:     _reuse(), then the object should be freed.
App 18286 stderr:
App 18286 stderr:     Without these methods, you get the warning here.  This is to
App 18286 stderr:     prevent the following situation: if your (or the library's) code
App 18286 stderr:     relies on reference counting for prompt closing, then on PyPy, the
App 18286 stderr:     __del__ method will be called later than on CPython.  You can
App 18286 stderr:     easily end up in a situation where you open and close a lot of
App 18286 stderr:     (high-level) '_socketobject' or '_fileobject', but the (low-level)
App 18286 stderr:     custom objects will accumulate before their __del__ are called.
App 18286 stderr:     You quickly risk running out of file descriptors, for example.
App 18286 stderr: }}
App 18286 stderr:   return socket._fileobject(sock, 'rb', 512)
App 18286 stderr:
```

Is it possible to fix that somehow?

**Comment by bbatsche** [comment]
I'm having something similar, although it's also causing Passenger to send a 502 response.

```
App 16189 stderr: [ pid=16189, time=2016-02-01 21:30:33,741 ]: WSGI application raised an exception!
App 16189 stderr: Traceback (most recent call last):
App 16189 stderr:   File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 163, in main_loop
App 16189 stderr:     socket_hijacked = self.process_request(env, input_stream, client)
App 16189 stderr:   File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 235, in process_request
App 16189 stderr:     env['wsgi.input']        = self.wrap_input_socket(input_stream)
App 16189 stderr:   File "/usr/share/passenger/helper-scripts/wsgi-loader.py", line 222, in wrap_input_socket
App 16189 stderr:     return socket._fileobject(sock, 'rb', 512)
App 16189 stderr:   File "/usr/lib/pypy/lib-python/2.7/socket.py", line 300, in __init__
App 16189 stderr:     sock._reuse()
App 16189 stderr: AttributeError: '_socketobject' object has no attribute '_reuse'
[ 2016-02-01 21:30:33.7446 16066/7f747ac7c700 age/Cor/Con/InternalUtils.cpp:105 ]: [Client 1-2] Sending 502 response: application did not send a complete response
```

**Comment by msva** [comment]
is it any chance on progress on that issue? 😺

**Comment by CamJN** [comment]
You can try the patch at https://github.com/phusion/passenger/commit/42d92d62fe05e67ca6dc698cebc17c8c5850688b.patch and see if simply delegating to the unwrapped socket object is enough.

**Comment by msva** [comment]
@CamJN 
Unfortunatelly, it is either me doing something wrong, or it doesn't work:

Initially, it led to ***tons*** of such errors in the passenger.log:
```
App 842927 stdout:
App 842902 stderr: [ pid=842902, time=2017-09-09 08:10:32,936 ]: WSGI application raised an exception!
App 842902 stderr: Traceback (most recent call last):
App 842902 stderr:   File "/usr/libexec/passenger/helper-scripts/wsgi-loader.py", line 163, in main_loop                                                                                                                                                                       App 842902 stderr:     socket_hijacked = self.process_request(env, input_stream, client)                                                                                                                                                                                       App 842902 stderr:   File "/usr/libexec/passenger/helper-scripts/wsgi-loader.py", line 243, in process_request                                                                                                                                                                 App 842902 stderr:     env['wsgi.input']        = self.wrap_input_socket(input_stream)                                                                                                                                                                                         App 842902 stderr:   File "/usr/libexec/passenger/helper-scripts/wsgi-loader.py", line 223, in wrap_input_socket
App 842902 stderr:     socket = socket._fileobject(sock, 'rb', 512)                                                                                                                                                                                                            App 842902 stderr: UnboundLocalError: local variable 'socket' referenced before assignment                                                                                                                                                                                     
```

When I tried to rename `socket` variable to `s` - it was
```
App 843705 stderr: Traceback (most recent call last):                                                                                                                                                                                                                          App 843705 stderr:   File "/usr/libexec/passenger/helper-scripts/wsgi-loader.py", line 163, in main_loop                                                                                                                                                                       App 843705 stderr:     socket_hijacked = self.process_request(env, input_stream, client)
App 843705 stderr:   File "/usr/libexec/passenger/helper-scripts/wsgi-loader.py", line 243, in process_request                                                                                                                                                                 App 843705 stderr:     env['wsgi.input']        = self.wrap_input_socket(input_stream)
App 843705 stderr:   File "/usr/libexec/passenger/helper-scripts/wsgi-loader.py", line 224, in wrap_input_socket
App 843705 stderr:     s._reuse = types.MethodType( sock._reuse, sock )                                                                                                                                                                                                        App 843705 stderr: AttributeError: '_socketobject' object has no attribute '_reuse'
```

So, it seems, it needs something more 😕

**Comment by CamJN** [comment]
Ok if pypy's socket implementation doesn't have the necessary functions, then this will indeed take more work.
