### ISSUE TITLE
Could not spawn process if /home/<username>/.gem/ruby is missing

### ISSUE THREAD

**Issue by ricochet2200** [phusion/passenger#1740]
First off, thanks for the work on this projects.  I'm a big fan of the passenger rpm install.

I'm attempting to use `bundler --standalone`, passenger, apache, and a user without a home directory (service account) to deploy my application.  Everything appears to work great except for the following error:

> [ 2016-02-03 15:49:35.7662 12252/7fb292fa1700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/rails-app: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger.
>   Error ID: a5d039fa
>   Error details saved to: /tmp/passenger-error-l0Fus9.html
>   Message from application: An error occurred while starting up the preloader. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="https://github.com/phusion/passenger/wiki/Debugging-application-startup-problems">this article</a> for more information about this problem.<br>
> <h2>Raw process output:</h2>
> <pre>
> /usr/share/rubygems/rubygems/path_support.rb:69:in `path=&apos;: undefined method `+&apos; for nil:NilClass (NoMethodError)
> 	from /usr/share/rubygems/rubygems/path_support.rb:30:in `initialize&apos;
> 	from /usr/share/rubygems/rubygems.rb:357:in `new&apos;
> 	from /usr/share/rubygems/rubygems.rb:357:in `paths&apos;
> 	from /usr/share/rubygems/rubygems.rb:379:in `path&apos;
> 	from /usr/share/rubygems/rubygems/specification.rb:794:in `dirs&apos;
> 	from /usr/share/rubygems/rubygems/specification.rb:658:in `each_normal&apos;
> 	from /usr/share/rubygems/rubygems/specification.rb:669:in `_all&apos;
> 	from /usr/share/rubygems/rubygems/specification.rb:822:in `each&apos;
> 	from /usr/share/rubygems/rubygems/specification.rb:864:in `find&apos;
> 	from /usr/share/rubygems/rubygems/specification.rb:864:in `find_inactive_by_path&apos;
> 	from /usr/share/rubygems/rubygems.rb:175:in `try_activate&apos;
> 	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:132:in `rescue in require&apos;
> 	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:144:in `require&apos;
> 	from &lt;internal:abrt_prelude&gt;:2:in `&lt;compiled&gt;&apos;
> /home/username/.gem/ruby
> </pre>

Because I am using a user without a home directory, `/home/username/.gem/ruby` does not exist.  When I do `mkdir -p /home/username/.gem/ruby` passenger spawns correctly, so this appears to be the problem. 

While I appreciate the new features that allow passenger to read env variables from the home directory, I should also be allowed to not have a home directory so I view this as a bug.  I have a workaround for now (make the directory), but this should probably be fixed.

**Comment by FooBarWidget** [comment]
Where does /home/username/.gem/ruby come from? Is it referenced by your bash startup files? If so, you should remove such references.

**Comment by ricochet2200** [comment]
I have no bash startup files.  `/home/username` does not exist because the user is a system user like `apache` that you cannot log into.   Nothing in my code uses this path.

Calling `ruby /usr/share/rubygems/rubygems/path_support.rb` does not yield any errors.  When passenger calls `path_support.rb` it crashes.  `path_support.rb` does stuff with GEM_HOME and GEM_PATH.  It appears to me that passenger is doing something, possibly with these variables, that causes this function to expect `/home/username/.gem/ruby` to exist.  When it does not, it crashes.

I hope this helps answer your question.

**Comment by FooBarWidget** [comment]
That's strange, because the backtrace says that everything begun from /home/username/.gem/ruby, yet that file does not exist. Could you attach /tmp/passenger-error-l0Fus9.html?

**Comment by ricochet2200** [comment]
I was also interested in what this would say.  However I get this:

`/tmp/passenger-error-l0Fus9.html: No such file or directory`

I generated the error again and checked the new tmp file; it is also missing.  It is either not getting generated or is being deleted very quickly.

Also, as some sanity checks:
    `cd: /home/username/.gem/ruby: No such file or directory`
    `cd: /home/username/.gem/: No such file or directory`
    `cd: /home/username: No such file or directory`
    
`cd /home` works!

**Comment by FooBarWidget** [comment]
Are you on RHEL 7? If so then Apache is configured to use a private tmp directory, meaning that the /tmp as seen by Apache actually maps to a different directory on the filesystem -- something like /tmp/systemd-private-XXXX/tmp. So can you look for /tmp/systemd-private-*/tmp/passenger-error-l0Fus9.html?

**Comment by ricochet2200** [comment]
Thanks, that helped me find the file.  I am on RHEL 7 and it was where you said it was.  I've uploaded the file so you can see it.  I had to change the extension from .html to .txt because it wouldn't let me upload an .html file.


[passenger-error-vwNFgN.txt](https://github.com/phusion/passenger/files/122199/passenger-error-vwNFgN.txt)

**Comment by OnixGH** [comment]
@ricochet2200 In the error file I see the environment variable `HOME=/home/username`? I wouldn't expect that if you say that `/home/username` doesn't exist on your system?

**Comment by ricochet2200** [comment]
I also would not expect `HOME` to be set directory, especially one that does not exist, but that seems to be the case.  Good catch!

I created this error on a new install of CentOS 7.  I created the user with this command:

    # getent verifies the user doesn't already exist
    /usr/bin/getent passwd username || /usr/sbin/useradd --system --no-create-home -g username username

I don't know why `HOME` is set to a value, especially one that does not exist...but I **can** say that there is at least one case where it is happening.  For the sake of good defensive programming, phusion should probably verify directories extracted from `HOME` actually exist...just in case.
