### ISSUE TITLE
undefined method `os_name'

### ISSUE THREAD

**Issue by jancervinka** [phusion/passenger#1742]
I just installed passenger-enterprise 5.0.24-9.el7 on centos 7 and when I try to start it, i get this error:
```
/usr/share/ruby/vendor_ruby/phusion_passenger/standalone/start_command.rb:574:in `should_check_hosts_file?': undefined method `os_name' for PhusionPassenger::PlatformInfo:Module (NoMethodError)
	from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/start_command.rb:353:in `show_intro_message'
	from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/start_command.rb:48:in `run'
	from /usr/share/ruby/vendor_ruby/phusion_passenger/standalone/main.rb:35:in `run!'
	from /usr/bin/passenger:28:in `<main>'
```

Downgrading to 5.0.23-9.el7 solves the issue.

**Comment by FooBarWidget** [comment]
This bug has been confirmed and fixed. We'll release the fix as part of 5.0.26. Our apologies for the inconvenience.
