### ISSUE TITLE
deploy meteor app failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by wuyang910217** [phusion/passenger#1758]
i'm deploying the meteor app through the [Tutorial](https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/ownserver/nginx/oss/trusty/deploy_app.html) setp by setp,but finally i got a error:
```
/bundle/programs/server/node_modules/fibers/future.js:245
						throw(ex);
						      ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:74:15)
    at Object.&lt;anonymous&gt; (/bundle/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```
It seems that deploying process has no mistake. So i search Google and found i need remove and reinstall the `fibers` and `bcrypt` package, I tried, but it doesn't work. Any idea and help me? My meteor version is 1.2.1

**Comment by Dielz98** [comment]
What is the solution on this?
