### ISSUE TITLE
failed to deploy meteor app

### ISSUE THREAD

**Issue by yudhaprama** [phusion/passenger#1775]
I'm following this tutorial: https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/digital_ocean/nginx/oss/el7/deploy_app.html

Here the result: http://128.199.192.252/

MongoLab: mongodb://<dbuser>:<dbpassword>@ds01xxxx.mlab.com:113xx/xxx

Log:
```shell
  GNU nano 2.3.1                           File: /var/log/nginx/error.log

[ 2016-03-13 23:37:36.7846 10144/7f2c423dd880 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2016-03-13 23:37:36.7976 10147/7fc587a59880 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-03-13 23:37:36.7980 10147/7fc587a59880 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-03-13 23:37:36.8007 10147/7fc587a59880 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 10147
[ 2016-03-13 23:37:36.8112 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-03-13 23:37:36.8125 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 10154

[ 2016-03-13 23:39:43.6029 10147/7fc581c05700 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 $

[ 2016-03-13 23:39:43.6038 10154/7f9ecd844700 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send sign$
[ 2016-03-13 23:39:43.6039 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until $
[ 2016-03-13 23:39:43.6040 10154/7f9ecd043700 Ser/Server.h:817 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2016-03-13 23:39:43.6041 10154/7f9ecd043700 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2016-03-13 23:39:43.6041 10147/7fc587a59880 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all c$
[ 2016-03-13 23:39:43.6042 10147/7fc581404700 Ser/Server.h:817 ]: [ApiServer] Freed 0 spare client objects
[ 2016-03-13 23:39:43.6042 10147/7fc581404700 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2016-03-13 23:39:43.6046 10154/7f9ecd844700 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2016-03-13 23:39:43.6049 10147/7fc581c05700 Ser/Server.h:817 ]: [ServerThr.1] Freed 128 spare client objects
[ 2016-03-13 23:39:43.6050 10147/7fc581c05700 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2016-03-13 23:39:43.6056 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished

^G Get Help           ^O WriteOut           ^R Read File          ^Y Prev Page          ^K Cut Text           ^C Cur Pos
^X Exit               ^J Justify            ^W Where Is           ^V Next Page          ^U UnCut Text         ^T To Spell
  GNU nano 2.3.1                                           File: /var/log/nginx/error.log

[ 2016-03-13 23:37:36.7846 10144/7f2c423dd880 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2016-03-13 23:37:36.7976 10147/7fc587a59880 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-03-13 23:37:36.7980 10147/7fc587a59880 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-03-13 23:37:36.8007 10147/7fc587a59880 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 10147
[ 2016-03-13 23:37:36.8112 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-03-13 23:37:36.8125 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 10154

[ 2016-03-13 23:39:43.6029 10147/7fc581c05700 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)

[ 2016-03-13 23:39:43.6038 10154/7f9ecd844700 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2016-03-13 23:39:43.6039 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-13 23:39:43.6040 10154/7f9ecd043700 Ser/Server.h:817 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2016-03-13 23:39:43.6041 10154/7f9ecd043700 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2016-03-13 23:39:43.6041 10147/7fc587a59880 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-13 23:39:43.6042 10147/7fc581404700 Ser/Server.h:817 ]: [ApiServer] Freed 0 spare client objects
[ 2016-03-13 23:39:43.6042 10147/7fc581404700 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2016-03-13 23:39:43.6046 10154/7f9ecd844700 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2016-03-13 23:39:43.6049 10147/7fc581c05700 Ser/Server.h:817 ]: [ServerThr.1] Freed 128 spare client objects
[ 2016-03-13 23:39:43.6050 10147/7fc581c05700 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2016-03-13 23:39:43.6056 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2016-03-13 23:39:43.6084 10147/7fc587a59880 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2016-03-13 23:39:44.7092 10246/7f51370f7880 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2016-03-13 23:39:44.7217 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-03-13 23:39:44.7220 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-03-13 23:39:44.7247 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 10249
[ 2016-03-13 23:39:44.7356 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-03-13 23:39:44.7370 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 10256

[ 2016-03-14 00:36:44.0594 10249/7f0ebb859700 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)

[ 2016-03-14 00:36:44.0596 10256/7fbf8833d700 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2016-03-14 00:36:44.0597 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-14 00:36:44.0598 10256/7fbf87b3c700 Ser/Server.h:817 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2016-03-14 00:36:44.0598 10256/7fbf87b3c700 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2016-03-14 00:36:44.0599 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-14 00:36:44.0599 10249/7f0ebb058700 Ser/Server.h:817 ]: [ApiServer] Freed 0 spare client objects
[ 2016-03-14 00:36:44.0599 10249/7f0ebb058700 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2016-03-14 00:36:44.0602 10256/7fbf8833d700 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2016-03-14 00:36:44.0606 10249/7f0ebb859700 Ser/Server.h:817 ]: [ServerThr.1] Freed 128 spare client objects
[ 2016-03-14 00:36:44.0607 10249/7f0ebb859700 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished

^G Get Help                   ^O WriteOut                   ^R Read File                  ^Y Prev Page                  ^K Cut Text                   ^C Cur Pos
^X Exit                       ^J Justify                    ^W Where Is                   ^V Next Page                  ^U UnCut Text                 ^T To Spell
  GNU nano 2.3.1                                           File: /var/log/nginx/error.log

[ 2016-03-13 23:37:36.7846 10144/7f2c423dd880 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2016-03-13 23:37:36.7976 10147/7fc587a59880 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-03-13 23:37:36.7980 10147/7fc587a59880 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-03-13 23:37:36.8007 10147/7fc587a59880 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 10147
[ 2016-03-13 23:37:36.8112 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-03-13 23:37:36.8125 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 10154

[ 2016-03-13 23:39:43.6029 10147/7fc581c05700 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)

[ 2016-03-13 23:39:43.6038 10154/7f9ecd844700 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2016-03-13 23:39:43.6039 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-13 23:39:43.6040 10154/7f9ecd043700 Ser/Server.h:817 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2016-03-13 23:39:43.6041 10154/7f9ecd043700 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2016-03-13 23:39:43.6041 10147/7fc587a59880 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-13 23:39:43.6042 10147/7fc581404700 Ser/Server.h:817 ]: [ApiServer] Freed 0 spare client objects
[ 2016-03-13 23:39:43.6042 10147/7fc581404700 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2016-03-13 23:39:43.6046 10154/7f9ecd844700 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2016-03-13 23:39:43.6049 10147/7fc581c05700 Ser/Server.h:817 ]: [ServerThr.1] Freed 128 spare client objects
[ 2016-03-13 23:39:43.6050 10147/7fc581c05700 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2016-03-13 23:39:43.6056 10154/7f9ed30aa880 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2016-03-13 23:39:43.6084 10147/7fc587a59880 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2016-03-13 23:39:44.7092 10246/7f51370f7880 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2016-03-13 23:39:44.7217 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-03-13 23:39:44.7220 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-03-13 23:39:44.7247 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 10249
[ 2016-03-13 23:39:44.7356 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-03-13 23:39:44.7370 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 10256

[ 2016-03-14 00:36:44.0594 10249/7f0ebb859700 age/Cor/CoreMain.cpp:532 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)

[ 2016-03-14 00:36:44.0596 10256/7fbf8833d700 age/Ust/UstRouterMain.cpp:422 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ 2016-03-14 00:36:44.0597 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:492 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-14 00:36:44.0598 10256/7fbf87b3c700 Ser/Server.h:817 ]: [UstRouterApiServer] Freed 0 spare client objects
[ 2016-03-14 00:36:44.0598 10256/7fbf87b3c700 Ser/Server.h:464 ]: [UstRouterApiServer] Shutdown finished
[ 2016-03-14 00:36:44.0599 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:901 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ 2016-03-14 00:36:44.0599 10249/7f0ebb058700 Ser/Server.h:817 ]: [ApiServer] Freed 0 spare client objects
[ 2016-03-14 00:36:44.0599 10249/7f0ebb058700 Ser/Server.h:464 ]: [ApiServer] Shutdown finished
[ 2016-03-14 00:36:44.0602 10256/7fbf8833d700 Ser/Server.h:464 ]: [UstRouter] Shutdown finished
[ 2016-03-14 00:36:44.0606 10249/7f0ebb859700 Ser/Server.h:817 ]: [ServerThr.1] Freed 128 spare client objects
[ 2016-03-14 00:36:44.0607 10249/7f0ebb859700 Ser/Server.h:464 ]: [ServerThr.1] Shutdown finished
[ 2016-03-14 00:36:44.0612 10256/7fbf8dba4880 age/Ust/UstRouterMain.cpp:523 ]: Passenger UstRouter shutdown finished
[ 2016-03-14 00:36:44.0637 10249/7f0ec16ae880 age/Cor/CoreMain.cpp:967 ]: Passenger core shutdown finished
[ 2016-03-14 00:36:45.1606 19777/7f60bdc08880 age/Wat/WatchdogMain.cpp:1276 ]: Starting Passenger watchdog...
[ 2016-03-14 00:36:45.1735 19780/7f875c8e0880 age/Cor/CoreMain.cpp:982 ]: Starting Passenger core...
[ 2016-03-14 00:36:45.1737 19780/7f875c8e0880 age/Cor/CoreMain.cpp:235 ]: Passenger core running in multi-application mode.
[ 2016-03-14 00:36:45.1766 19780/7f875c8e0880 age/Cor/CoreMain.cpp:732 ]: Passenger core online, PID 19780
[ 2016-03-14 00:36:45.1877 19787/7f5746689880 age/Ust/UstRouterMain.cpp:529 ]: Starting Passenger UstRouter...
[ 2016-03-14 00:36:45.1892 19787/7f5746689880 age/Ust/UstRouterMain.cpp:342 ]: Passenger UstRouter online, PID 19787
App 19803 stdout:
App 19803 stderr:
App 19803 stderr: module.js:340
App 19803 stderr:     throw err;
App 19803 stderr:           ^
App 19803 stderr: Error: Cannot find module 'fibers'
App 19803 stderr:     at Function.Module._resolveFilename (module.js:338:15)
App 19803 stderr:     at Function.Module._load (module.js:280:25)
App 19803 stderr:     at Module.require (module.js:364:17)
App 19803 stderr:     at require (module.js:380:17)
App 19803 stderr:     at Object.<anonymous> (/var/www/myapp/bundle/programs/server/boot.js:1:75)
App 19803 stderr:     at Module._compile (module.js:456:26)
App 19803 stderr:     at Object.Module._extensions..js (module.js:474:10)
App 19803 stderr:     at Module.load (module.js:356:32)
App 19803 stderr:     at require (module.js:380:17)
App 19803 stderr:     at Object.<anonymous> (/var/www/myapp/bundle/programs/server/boot.js:1:75)
App 19803 stderr:     at Module._compile (module.js:456:26)
App 19803 stderr:     at Object.Module._extensions..js (module.js:474:10)
App 19803 stderr:     at Module.load (module.js:356:32)
App 19803 stderr:     at Function.Module._load (module.js:312:12)
App 19803 stderr:     at Module.require (module.js:364:17)
[ 2016-03-14 00:37:06.3257 19780/7f8755a8a700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/myapp/bundle: An error occurred while starting $
  Error ID: 01aa0f94
  Error details saved to: /tmp/passenger-error-FHTAgF.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="htt$
<h2>Raw process output:</h2>
<pre>

module.js:340
    throw err;
          ^
Error: Cannot find module &apos;fibers&apos;
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.&lt;anonymous&gt; (/var/www/myapp/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</pre>

[ 2016-03-14 00:37:06.3328 19780/7f8756a8c700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the e$
App 19827 stdout:
App 19827 stderr:
App 19827 stderr: module.js:340
App 19827 stderr:     throw err;
App 19827 stderr:           ^
App 19827 stderr: Error: Cannot find module 'fibers'
App 19827 stderr:     at Function.Module._resolveFilename (module.js:338:15)
App 19827 stderr:     at Function.Module._load (module.js:280:25)
App 19827 stderr:     at Module.require (module.js:364:17)
App 19827 stderr:     at require (module.js:380:17)
App 19827 stderr:     at Object.<anonymous> (/var/www/myapp/bundle/programs/server/boot.js:1:75)
App 19827 stderr:     at Module._compile (module.js:456:26)
App 19827 stderr:     at Object.Module._extensions..js (module.js:474:10)
App 19827 stderr:     at Module.load (module.js:356:32)
App 19827 stderr:     at Function.Module._load (module.js:312:12)
App 19827 stderr:     at Module.require (module.js:364:17)
[ 2016-03-14 00:37:06.8671 19780/7f8755a8a700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/myapp/bundle: An error occurred while starting $
  Error ID: 3f74716b
  Error details saved to: /tmp/passenger-error-BL62V4.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="htt$
<h2>Raw process output:</h2>
<pre>

module.js:340
    throw err;
          ^
Error: Cannot find module &apos;fibers&apos;
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.&lt;anonymous&gt; (/var/www/myapp/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</pre>

[ 2016-03-14 00:37:06.8747 19780/7f8756a8c700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the e$
App 19851 stdout:
App 19851 stderr:
App 19851 stderr: module.js:340
App 19851 stderr:     throw err;
App 19851 stderr:           ^
App 19851 stderr: Error: Cannot find module 'fibers'
App 19851 stderr:     at Function.Module._resolveFilename (module.js:338:15)
App 19851 stderr:     at Function.Module._load (module.js:280:25)
App 19851 stderr:     at Module.require (module.js:364:17)
App 19851 stderr:     at require (module.js:380:17)
App 19851 stderr:     at Object.<anonymous> (/var/www/myapp/bundle/programs/server/boot.js:1:75)
App 19851 stderr:     at Module._compile (module.js:456:26)
App 19851 stderr:     at Object.Module._extensions..js (module.js:474:10)
App 19851 stderr:     at Module.load (module.js:356:32)
App 19851 stderr:     at Function.Module._load (module.js:312:12)
App 19851 stderr:     at Module.require (module.js:364:17)
[ 2016-03-14 00:37:30.7411 19780/7f8755a8a700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/myapp/bundle: An error occurred while starting $
  Error ID: ebec4c6e
  Error details saved to: /tmp/passenger-error-Htsw2v.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="htt$
<h2>Raw process output:</h2>
<pre>

module.js:340
    throw err;
          ^
Error: Cannot find module &apos;fibers&apos;
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.&lt;anonymous&gt; (/var/www/myapp/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</pre>
[ 2016-03-14 00:37:30.7481 19780/7f8756a8c700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-3] Cannot checkout session because a spawning error occurred. The identifier of the e$
App 19875 stdout:
App 19875 stderr:
App 19875 stderr: module.js:340
App 19875 stderr:     throw err;
App 19875 stderr:           ^
App 19875 stderr: Error: Cannot find module 'fibers'
App 19875 stderr:     at Function.Module._resolveFilename (module.js:338:15)
App 19875 stderr:     at Function.Module._load (module.js:280:25)
App 19875 stderr:     at Module.require (module.js:364:17)
App 19875 stderr:     at require (module.js:380:17)
App 19875 stderr:     at Object.<anonymous> (/var/www/myapp/bundle/programs/server/boot.js:1:75)
App 19875 stderr:     at Module._compile (module.js:456:26)
App 19875 stderr:     at Object.Module._extensions..js (module.js:474:10)
App 19875 stderr:     at Module.load (module.js:356:32)
App 19875 stderr:     at Function.Module._load (module.js:312:12)
App 19875 stderr:     at Module.require (module.js:364:17)
[ 2016-03-14 00:37:31.0511 19780/7f8755a8a700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /var/www/myapp/bundle: An error occurred while starting $
  Error ID: 275e874b
  Error details saved to: /tmp/passenger-error-embhRY.html
  Message from application: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read <a href="htt$
<h2>Raw process output:</h2>
<pre>

module.js:340
    throw err;
          ^
Error: Cannot find module &apos;fibers&apos;
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.&lt;anonymous&gt; (/var/www/myapp/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</pre>

[ 2016-03-14 00:37:31.0544 19780/7f8756a8c700 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-4] Cannot checkout session because a spawning error occurred. The identifier of the e$
```

**Comment by Dielz98** [comment]
Related with https://github.com/phusion/passenger/issues/1758

Passenger not working with Meteor

**Comment by yudhaprama** [comment]
It seems I haven't install `fibers`

I did:
```shell
cd /var/www/myapp/bundle/programs/server
npm install --production
```

But got error:
```shell
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
npm WARN package.json meteor-dev-bundle@0.0.0 No license field.
-
> fibers@1.0.5 install /var/www/myapp/bundle/programs/server/node_modules/fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:116:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:49:11
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Linux 4.2.0-27-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /var/www/myapp/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v0.12.12
gyp ERR! node -v v0.12.12
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
Build failed
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--production"
npm ERR! node v0.12.12
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.5 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.5 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.
```

**Comment by OnixGH** [comment]
As the error message says "npm ERR! Tell the author that this fails on your system:"

You should contact the author / maintainer of fibers.

**Comment by yudhaprama** [comment]
@OnixGH 

That suggestion won't solve the issue as I build the system with your system configuration. But okay I close this issue.

**Comment by OnixGH** [comment]
@yudhaprama I'm not sure what you mean by "I build the system with your system configuration", I don't see anything being built by Passenger in your logs. It just runs your app which gives an error back that should be solved on the app side?

**Comment by yudhaprama** [comment]
I said I was following your tutorial until finished https://www.phusionpassenger.com/library/walkthroughs/deploy/meteor/aws/nginx/oss/launch_server.html

**Comment by yudhaprama** [comment]
Both AWS and DO gave the same result

**Comment by OnixGH** [comment]
Aha, you mean you were following our tutorial.

Fixing applications or configurations isn't something for the Passenger issue list, and the tutorial can't do much about that either, but you can definitely try the [support forum](https://groups.google.com/forum/?pli=1#!forum/phusion-passenger) for further suggestions.

**Comment by yudhaprama** [comment]
Meteor app require Node 0.10.40 or older

Below give me `0.10.43`:
```shell
sudo yum install -y epel-release curl
curl --fail -sSL -o setup-nodejs https://rpm.nodesource.com/setup
sudo bash setup-nodejs
sudo yum install -y nodejs gcc-c++ make
```

Below give me `0.12`:
```shell
sudo apt-get update
sudo apt-get install -y curl apt-transport-https ca-certificates &&
curl --fail -ssL -o setup-nodejs https://deb.nodesource.com/setup_0.12 &&
sudo bash setup-nodejs &&
sudo apt-get install -y nodejs build-essential
```

Incompatibility create above error. Please update your tutorial accordingly.

**Comment by OnixGH** [comment]
Already reported: https://github.com/phusion/passenger_library/issues/27
