### ISSUE TITLE
Invalid argument - connect(2)  running bundle exec passenger start

### ISSUE THREAD

**Issue by arsen91** [phusion/passenger#1789]
I have ubuntu server and rails app on it. 
Here is a Gemfile

```
source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '4.2.0'
gem 'pg'
gem 'active_model_serializers'
gem 'raddocs'
gem 'sorcery'
gem 's3'
gem 'mandrill-api', require: 'mandrill'
gem 'faker'
gem 'dalli'
gem 'pry'
gem 'newrelic_rpm'
gem 'rack-timeout'
gem 'browser'
gem 'redis-rails'
gem 'sidekiq'
gem 'whenever', :require => false

group :production do
  gem 'passenger'
  gem 'heroku-deflater'
  gem 'rails_12factor'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'rspec_api_documentation'
  gem 'database_cleaner'
  gem 'awesome_print'
end

group :test do
  gem 'factory_girl_rails'
  gem 'webmock'
end

group :development do
  gem 'spring'
  gem 'annotate'
  gem 'letter_opener'
  gem 'bullet'
end
```

Here is Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actionmailer (4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 1.0, >= 1.0.5)
    actionpack (4.2.0)
      actionview (= 4.2.0)
      activesupport (= 4.2.0)
      rack (~> 1.6.0)
      rack-test (~> 0.6.2)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    actionview (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 1.0, >= 1.0.5)
      rails-html-sanitizer (~> 1.0, >= 1.0.1)
    active_model_serializers (0.9.3)
      activemodel (>= 3.2)
    activejob (4.2.0)
      activesupport (= 4.2.0)
      globalid (>= 0.3.0)
    activemodel (4.2.0)
      activesupport (= 4.2.0)
      builder (~> 3.1)
    activerecord (4.2.0)
      activemodel (= 4.2.0)
      activesupport (= 4.2.0)
      arel (~> 6.0)
    activesupport (4.2.0)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.3.8)
    annotate (2.6.5)
      activerecord (>= 2.3.0)
      rake (>= 0.8.7)
    arel (6.0.0)
    awesome_print (1.6.1)
    bcrypt (3.1.10)
    browser (0.8.0)
    builder (3.2.2)
    bullet (4.14.7)
      activesupport (>= 3.0.0)
      uniform_notifier (~> 1.9.0)
    celluloid (0.16.0)
      timers (~> 4.0.0)
    chronic (0.10.2)
    coderay (1.1.0)
    connection_pool (2.2.0)
    crack (0.4.2)
      safe_yaml (~> 1.0.0)
    daemon_controller (1.2.0)
    dalli (2.7.4)
    database_cleaner (1.4.0)
    diff-lcs (1.2.5)
    erubis (2.7.0)
    excon (0.45.1)
    factory_girl (4.5.0)
      activesupport (>= 3.0.0)
    factory_girl_rails (4.5.0)
      factory_girl (~> 4.5.0)
      railties (>= 3.0.0)
    faker (1.4.3)
      i18n (~> 0.5)
    faraday (0.9.1)
      multipart-post (>= 1.2, < 3)
    globalid (0.3.0)
      activesupport (>= 4.1.0)
    haml (4.0.6)
      tilt
    heroku-deflater (0.5.3)
      rack (>= 1.4.5)
    hike (1.2.3)
    hitimes (1.2.2)
    i18n (0.7.0)
    json (1.8.2)
    jwt (1.2.1)
    launchy (2.4.3)
      addressable (~> 2.3)
    letter_opener (1.3.0)
      launchy (~> 2.2)
    loofah (2.0.1)
      nokogiri (>= 1.5.9)
    mail (2.6.3)
      mime-types (>= 1.16, < 3)
    mandrill-api (1.0.53)
      excon (>= 0.16.0, < 1.0)
      json (>= 1.7.7, < 2.0)
    method_source (0.8.2)
    mime-types (2.4.3)
    mini_portile (0.6.2)
    minitest (5.5.1)
    multi_json (1.10.1)
    multi_xml (0.5.5)
    multipart-post (2.0.0)
    mustache (0.99.8)
    newrelic_rpm (3.12.0.288)
    nokogiri (1.6.6.2)
      mini_portile (~> 0.6.0)
    oauth (0.4.7)
    oauth2 (1.0.0)
      faraday (>= 0.8, < 0.10)
      jwt (~> 1.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (~> 1.2)
    passenger (4.0.58)
      daemon_controller (>= 1.2.0)
      rack
      rake (>= 0.8.1)
    pg (0.18.1)
    proxies (0.2.1)
    pry (0.10.1)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.6.0)
    rack-protection (1.5.3)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rack-timeout (0.2.4)
    raddocs (0.4.0)
      haml (~> 4.0, >= 4.0.4)
      json (~> 1.8, >= 1.8.1)
      sinatra (~> 1.3, >= 1.3.0)
    rails (4.2.0)
      actionmailer (= 4.2.0)
      actionpack (= 4.2.0)
      actionview (= 4.2.0)
      activejob (= 4.2.0)
      activemodel (= 4.2.0)
      activerecord (= 4.2.0)
      activesupport (= 4.2.0)
      bundler (>= 1.3.0, < 2.0)
      railties (= 4.2.0)
      sprockets-rails
    rails-deprecated_sanitizer (1.0.3)
      activesupport (>= 4.2.0.alpha)
    rails-dom-testing (1.0.5)
      activesupport (>= 4.2.0.beta, < 5.0)
      nokogiri (~> 1.6.0)
      rails-deprecated_sanitizer (>= 1.0.1)
    rails-html-sanitizer (1.0.1)
      loofah (~> 2.0)
    rails_12factor (0.0.3)
      rails_serve_static_assets
      rails_stdout_logging
    rails_serve_static_assets (0.0.3)
    rails_stdout_logging (0.0.3)
    railties (4.2.0)
      actionpack (= 4.2.0)
      activesupport (= 4.2.0)
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (10.4.2)
    redis (3.2.1)
    redis-actionpack (4.0.0)
      actionpack (~> 4)
      redis-rack (~> 1.5.0)
      redis-store (~> 1.1.0)
    redis-activesupport (4.1.1)
      activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-namespace (1.5.2)
      redis (~> 3.0, >= 3.0.4)
    redis-rack (1.5.0)
      rack (~> 1.5)
      redis-store (~> 1.1.0)
    redis-rails (4.0.0)
      redis-actionpack (~> 4)
      redis-activesupport (~> 4)
      redis-store (~> 1.1.0)
    redis-store (1.1.6)
      redis (>= 2.2)
    rspec (3.1.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-rails (3.1.0)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      railties (>= 3.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)
    rspec_api_documentation (4.3.0)
      activesupport (>= 3.0.0)
      json (~> 1.4, >= 1.4.6)
      mustache (~> 0.99, >= 0.99.4)
      rspec (>= 3.0.0)
    s3 (0.3.22)
      proxies (~> 0.2.0)
    safe_yaml (1.0.4)
    sidekiq (3.4.2)
      celluloid (~> 0.16.0)
      connection_pool (~> 2.2, >= 2.2.0)
      json (~> 1.0)
      redis (~> 3.2, >= 3.2.1)
      redis-namespace (~> 1.5, >= 1.5.2)
    sinatra (1.4.5)
      rack (~> 1.4)
      rack-protection (~> 1.4)
      tilt (~> 1.3, >= 1.3.4)
    slop (3.6.0)
    sorcery (0.9.0)
      bcrypt (~> 3.1)
      oauth (~> 0.4, >= 0.4.4)
      oauth2 (>= 0.8.0)
    spring (1.3.6)
    sprockets (2.12.3)
      hike (~> 1.2)
      multi_json (~> 1.0)
      rack (~> 1.0)
      tilt (~> 1.1, != 1.3.0)
    sprockets-rails (2.2.4)
      actionpack (>= 3.0)
      activesupport (>= 3.0)
      sprockets (>= 2.8, < 4.0)
    thor (0.19.1)
    thread_safe (0.3.4)
    tilt (1.4.1)
    timers (4.0.1)
      hitimes
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uniform_notifier (1.9.0)
    webmock (1.21.0)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
    whenever (0.9.4)
      chronic (>= 0.6.3)

PLATFORMS
  ruby

DEPENDENCIES
  active_model_serializers
  annotate
  awesome_print
  browser
  bullet
  dalli
  database_cleaner
  factory_girl_rails
  faker
  heroku-deflater
  letter_opener
  mandrill-api
  newrelic_rpm
  passenger
  pg
  pry
  rack-timeout
  raddocs
  rails (= 4.2.0)
  rails_12factor
  redis-rails
  rspec-rails
  rspec_api_documentation
  s3
  sidekiq
  sorcery
  spring
  webmock
  whenever

BUNDLED WITH
   1.10.6
```

So when I run `bundle exec passenger status` it fairly says:
`Phusion Passenger Standalone is not running, according to PID file /home/ubuntu/lessonhub/backend/tmp/pids/passenger.3000.pid`

But when I try to start with `bundle exec passenger start` I have an error
```
/home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/start_command.rb:413:in `connect_nonblock': Invalid argument - connect(2) for 0.0.0.0:3000 (Errno::EINVAL)
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/start_command.rb:413:in `check_port_with_protocol'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/start_command.rb:440:in `check_port'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/start_command.rb:448:in `check_port_availability'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/start_command.rb:343:in `sanity_check_server_options'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/start_command.rb:64:in `run'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/main.rb:91:in `run_command'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/main.rb:61:in `run!'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/lib/phusion_passenger/standalone/main.rb:38:in `run!'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-4.0.58/bin/passenger:44:in `<top (required)>'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/bin/passenger:23:in `load'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/bin/passenger:23:in `<main>'

```

Ask any additional info, if you need.
Google does know almost nothing about it.. Please, help.

**Comment by FooBarWidget** [comment]
You are on version 4.0.58. That is not the latest version. Please try again using the latest version because there have been a lot of bug fixes since 4.0.58.

**Comment by arsen91** [comment]
Thank you for suggestion. I've updated everything and now have almost the same thing.. 
`bundle exec passenger status` says `Phusion Passenger Standalone is not running, according to PID file /home/ubuntu/{{app-name}}/backend/tmp/pids/passenger.3000.pid`, but when I run `bundle exec passenger start` I get this:
```
/home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:778:in `connect_nonblock': Invalid argument - connect(2) for 0.0.0.0:3000 (Errno::EINVAL)
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:778:in `ping_socket'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:805:in `ping_tcp_socket'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:712:in `run_ping_command'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:386:in `block (2 levels) in start_without_locking'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:501:in `wait_until'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:380:in `block in start_without_locking'
	from /home/ubuntu/.rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	from /home/ubuntu/.rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `call'
	from /home/ubuntu/.rubies/ruby-2.2.0/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:358:in `start_without_locking'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:220:in `block in start'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:68:in `block in exclusive_lock'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:63:in `open'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller/lock_file.rb:63:in `exclusive_lock'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/vendor/daemon_controller.rb:219:in `start'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/standalone/start_command/nginx_engine.rb:49:in `start_engine_real'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/standalone/start_command.rb:322:in `start_engine'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/standalone/start_command.rb:63:in `run'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/src/ruby_supportlib/phusion_passenger/standalone/main.rb:51:in `run!'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/gems/passenger-5.0.27/bin/passenger:45:in `<top (required)>'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/bin/passenger:23:in `load'
	from /home/ubuntu/lessonhub/backend/vendor/bundle/ruby/2.2.0/bin/passenger:23:in `<main>'
```

And now if I check the status it says: `Phusion Passenger Standalone is running on PID 1540, according to PID file /home/ubuntu/{{app-name}}/backend/tmp/pids/passenger.3000.pid`, which gives me clue that it started, but something when wrong. Also, if I try to make a request from the web-page I have passenger error in HTTP response which says Environment (value of RAILS_ENV, RACK_ENV, WSGI_ENV, NODE_ENV and PASSENGER_APP_ENV)
development

Not sure why this happens, because earlier I was able to start passenger the same way and everything worked ok, i.e. it was in production env.. Any help here? Thank you

**Comment by OnixGH** [comment]
I don't see anything that indicates an issue with Passenger, the most likely cause at this point is something in your configuration. Please post to our [Community support forum](https://groups.google.com/forum/#!forum/phusion-passenger) for help with your configuration.

We recommend posting your full config to avoid wasting time with guessing, as well as answering the 7 questions we asked you when you clicked new issue.
