### ISSUE TITLE
passenger-install-apache2-module  crashed by install

### ISSUE THREAD

**Issue by tbohr** [phusion/passenger#1813]
Hi,

i am using ruby 2.3.0p0, rails 4.1.2 and passenger-5.0.28.

I tried to install passenger - this error:
```
root@64-minimal /var/www # passenger-install-apache2-module  
/usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0xcda4d8 passenger-5.0.28> (NoMethodError)
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from /usr/local/rvm/gems/ruby-2.3.0/gems/passenger-5.0.28/bin/passenger-install-apache2-module:34:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/passenger-install-apache2-module:23:in `load'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/passenger-install-apache2-module:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by OnixGH** [comment]
It works for me, your ruby install is broken?

```
root@onix:~# rvm use 2.3.0
Using /usr/local/rvm/gems/ruby-2.3.0
root@onix:~# passenger-install-apache2-module
Welcome to the Phusion Passenger Apache 2 module installer, v5.0.28.

This installer will guide you through the entire installation process. It
shouldn't take more than 3 minutes in total.

...
```

**Comment by tbohr** [comment]
I removed ruby and rvm, after reinstalling it works fine. Thank you very much and sorry!
