### ISSUE TITLE
create_unix_socket_on_filesystem failures under Vagrant with direct/builtin

### ISSUE THREAD

**Issue by mwpastore** [phusion/passenger#1916]
## Issue report

**Question 1: What is the problem?**

I'm attempting to adapt the sinatra-sequel [FrameworkBenchmark](https://github.com/techempower/frameworkbenchmarks) to run on Phusion Passenger as well as Puma (and, hopefully, Unicorn). My fork/branch is [here](https://github.com/mwpastore/FrameworkBenchmarks/tree/add-passenger/frameworks/Ruby/sinatra-sequel), and the relevant files are:

* Gemfile
* config.ru
* hello_world.rb
* run_mri_passenger.sh

The crux of the issue is that when I run the benchmark (without `_PASSENGER_FORCE_HTTP_SESSION=true`) it passes the verification step, but under load it crashes with the following error:

```
Server sinatra-sequel-passenger-mri: App 31968 stderr: /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:302:in `initialize'
Server sinatra-sequel-passenger-mri: App 31968 stderr: : No such file or directory - connect(2) for /tmp/passenger.khWlzld/apps.s/ruby.6s9a7s4aWhxSv6DbUcJ2R3sIbho4VQCwblhSVWKHpcYYXljnqkmFWetEEabj4Pv (Errno::ENOENT)
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:302:in `new'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:302:in `block in create_unix_socket_on_filesystem'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/utils.rb:65:in `block in retry_at_most'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/utils.rb:63:in `times'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/utils.rb:63:in `retry_at_most'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:299:in `create_unix_socket_on_filesystem'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/ruby_supportlib/phusion_passenger/request_handler.rb:101:in `initialize'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/helper-scripts/rack-loader.rb:127:in `new'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/helper-scripts/rack-loader.rb:127:in `<module:App>'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/helper-scripts/rack-loader.rb:28:in `<module:PhusionPassenger>'
Server sinatra-sequel-passenger-mri: App 31968 stderr: 	from /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel/vendor/bundle/ruby/2.4.0/gems/passenger-5.1.1/src/helper-scripts/rack-loader.rb:27:in `<main>'
Server sinatra-sequel-passenger-mri: [ 2017-01-16 18:43:23.6318 31237/7ff450ee0700 age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel: An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger.
Server sinatra-sequel-passenger-mri:   Error ID: e203f24f
Server sinatra-sequel-passenger-mri:   Error details saved to: /tmp/passenger-error.CNgzjh
```

I've staged one of the error details [here](https://perlkour.pl/phusion.html).

Here's my passenger invocation, so you don't have to dig through my repo:

```
rvm ruby-2.4.0 do bundle exec passenger start \
  --engine builtin --disable-turbocaching --disable-security-update-check \
  --spawn-method direct --max-pool-size $instances --min-instances $instances --max-request-queue-size 500 \
  --address 0.0.0.0 --port 8080 --environment production
```

* Builtin engine for benchmarking (i.e. we want to test passenger, not nginx)
* Turbocaching disabled per benchmark requirements
* Security update check disabled because it's just a benchmark
* Direct spawning because Sequel connection pools aren't CoW safe
* Fixed number of instances scaled to available memory of system

The error still occurs with `instances=1` in `run_mri_passenger.sh`, so it doesn't *seem* to be a ulimit issue or anything like that. It occurs under both 2.3.3 and 2.4.0. Setting `_PASSENGER_FORCE_HTTP_SESSION=true` in the environment "solves" the problem.

The error is reproducible, but if you don't already have the TechEmpower FrameworkBenchmarks environment set up, it can be a little daunting. I'm happy to be the eyes and hands on the ground to sort this out.

**Question 2: Passenger version and integration mode**:

Open source 5.1.1 standalone

**Question 3: OS or Linux distro, platform (including version)**:

Vagrant 1.9.1
VirtualBox 5.1.12
ubuntu/trusty64 (virtualbox, 20170110.0.0)
Linux tfb-all 4.4.0-59-generic \#80~14.04.1-Ubuntu SMP Fri Jan 6 18:02:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Question 4: Passenger installation method**:

RubyGems + Gemfile

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

Ruby 2.3.3
Ruby 2.4.0
RVM

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

Vagrant/VirtualBox (local machine)

**Question 7: Anything else about your setup that we should know?**

http://frameworkbenchmarks.readthedocs.io/en/latest/

**Comment by CamJN** [comment]
Does this occur with a lighter load? What kind of device does `/tmp` reside on (network/ram/physical)? What filesystem are you using? Does your user have `rwx` permissions for `/tmp`?

**Comment by mwpastore** [comment]
@CamJN It's taking a `wrk` load and seems to fall over right away. `/tmp` is just a directory, mode 01777, on the ext4 root filesystem, which has 35G and 2.4M i-nodes free.

**Comment by CamJN** [comment]
Does the socket directory (`/tmp/passenger.*/apps.s/`) exist at all when this happens? Can you turn on log-level 7 (https://www.phusionpassenger.com/library/config/standalone/reference/#--log-level-log_level) and provide the logs from one "run"? You'll likely have to put them in a gist.

**Comment by mwpastore** [comment]
No, it doesn't appear to exist. Here's a [gist](https://gist.github.com/mwpastore/fda5b2c46e9694a7ae67b620efb89baf) with the log. Things seem to get interesting around line 4584.

**Comment by OnixGH** [comment]
@mwpastore the log suggests a crash while spawning. What happens if you try with a "warmup" request (e.g. with instance 1) and give the server time to spawn before unleashing wrk?

**Comment by mwpastore** [comment]
That's essentially how FWBM works: it starts the server, sleeps for 60 seconds, issues a few requests to verify the server is up and running and returning the correct results, then runs wrk against it. Are you suggesting it needs to sleep a second time, before running wrk? 

Doesn't setting  --max-pool-size and --min-instances to the same value force Passenger to "pre-spawn" the workers? I see the "Passenger RubyApp" processes idling before wrk fires up and causes them to crash. Is something else supposed to spawn?

**Comment by OnixGH** [comment]
> Doesn't setting --max-pool-size and --min-instances to the same value force Passenger to "pre-spawn" the workers? 

Technically no, that's what the [prestart](https://www.phusionpassenger.com/library/config/nginx/reference/#passenger_pre_start) option is for. However, in your case (Passenger standalone) the option should be added automatically.

Looking at the `Uptime: ` of the processes in the trace I think what is happening is that each process takes about 5-7 sec to launch, which makes 60 seconds too short for the spawning to be complete for the 15 processes you configured.

So increase the wait time or decrease the min/max to take the spawning out of the load test for now (you can verify with `passenger-status` if all processes are up). If you get a new crash we'll have more clues to look into, and if it doesn't we'll know to focus on spawning.

**Comment by mwpastore** [comment]
I am running with `instances=3` now and it's still presenting the same crash. Would you like a fresh log?

**Comment by OnixGH** [comment]
Yep.

**Comment by mwpastore** [comment]
Here is the output of passenger-status after the "warmup" requests and partway through the second 60-second sleep:

```
$ bundle exec passenger-status
Version : 5.1.1
Date    : 2017-01-23 17:37:27 +0000
Instance: mq1kAh7e (Phusion_Passenger/5.1.1)

----------- General information -----------
Max pool size : 3
App groups    : 1
Processes     : 3
Requests in top-level queue : 0

----------- Application groups -----------
/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel:
  App root: /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel
  Requests in queue: 0
  * PID: 16467   Sessions: 0       Processed: 15      Uptime: 1m 48s
    CPU: 2%      Memory  : 23M     Last used: 56s ago
  * PID: 16485   Sessions: 0       Processed: 0       Uptime: 1m 40s
    CPU: 2%      Memory  : 21M     Last used: 1m 40s ago
  * PID: 16506   Sessions: 0       Processed: 0       Uptime: 1m 35s
    CPU: 2%      Memory  : 21M     Last used: 1m 35s ago
```

After the crash, passenger-status says, "ERROR: Phusion Passenger doesn't seem to be running."

[Here](https://gist.githubusercontent.com/mwpastore/fda5b2c46e9694a7ae67b620efb89baf/raw/8c11d06774a03d9ca1389377f2fbbb2058b91c9b/3way.txt) is an updated log.

**Comment by OnixGH** [comment]
I started looking at the time of your status output (17:37:27):
- Around 17:37:30 the test seems to begin: "Benchmarking sinatra-sequel-postgres-passenger-mri"
- About a second later it seems that process 16485 has crashed:
```
[ 2017-01-23 17:37:31.5328 16429/7f25c4f10700 age/Cor/App/Socket.h:90 ]: Connecting to unix:/tmp/passenger.M5TQUzs/apps.s/ruby.b8jwMzAFFjEIX0LkStL3dorXKiMxren8viGwmBldjNFGl2FEc33AwFwBl2z9NiM
[ 2017-01-23 17:37:31.5329 16429/7f25c4f10700 age/Cor/App/Socket.h:91 ]: File descriptor opened: 59
[ 2017-01-23 17:37:31.5330 16429/7f25c4f10700 Uti/ScopeGuard.h:138 ]: File descriptor closed: 59
[ 2017-01-23 17:37:31.5328 16429/7f25c5711700 age/Cor/App/Poo/Miscellaneous.cpp:49 ]: asyncGet(appGroupName=/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel)
[ 2017-01-23 17:37:31.5332 16429/7f25c5711700 age/Cor/App/Poo/Miscellaneous.cpp:82 ]: Found existing Group
[ 2017-01-23 17:37:31.5332 16429/7f25c5711700 age/Cor/App/Gro/SessionManagement.cpp:330 ]: Session checked out from process (pid=16506, group=/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel)
[ 2017-01-23 17:37:31.5333 16429/7f25c5711700 age/Cor/App/Poo/Miscellaneous.cpp:87 ]: asyncGet() finished
[ 2017-01-23 17:37:31.5334 16429/7f25c5711700 age/Cor/Con/CheckoutSession.cpp:141 ]: [Client 1-13] Session checked out: pid=16506, gupid=179b43f-YgVcx0ZzBf
[ 2017-01-23 17:37:31.5335 16429/7f25c5711700 age/Cor/App/Socket.h:90 ]: Connecting to unix:/tmp/passenger.M5TQUzs/apps.s/ruby.Jv7wGMe9U6zMpBwA8RCyK7trQI6zBoKL2tFs9YRpk3QpSX6C74WaS60aCGyZWcW
[ 2017-01-23 17:37:31.5339 16429/7f25c5711700 age/Cor/App/Socket.h:91 ]: File descriptor opened: 59
[ 2017-01-23 17:37:31.5341 16429/7f25c5711700 Uti/ScopeGuard.h:138 ]: File descriptor closed: 59
[ 2017-01-23 17:37:31.5335 16429/7f25c4f10700 age/Cor/App/Gro/SessionManagement.cpp:132 ]: Could not initiate a session with process (pid=16485, group=/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel), detaching from pool if possible
[ 2017-01-23 17:37:31.5342 16429/7f25c4f10700 age/Cor/App/Gro/ProcessListManagement.cpp:483 ]: Detaching process (pid=16485, group=/FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel)
[ 2017-01-23 17:37:31.5343 16429/7f25c4f10700 age/Cor/CoreMain.cpp:907 ]: Checking whether to disconnect long-running connections for process 16485, application /FrameworkBenchmarks/frameworks/Ruby/sinatra-sequel
[ 2017-01-23 17:37:31.5344 16429/7f25c4f10700 age/Cor/App/Gro/ProcessListManagement.cpp:281 ]: Starting detached processes checker
```

So something about the test is apparently crashing your application, forcing passenger to respawn (that's why there is still a lot of spawning going on in your logs). Maybe it's the request, or maybe the tester is doing something extra? We can't really help with crashing app processes.

**Comment by mwpastore** [comment]
The app takes the benchmark fine under Puma (MRI and JRuby), TorqueBox, Unicorn, and Passenger when _PASSENGER_FORCE_HTTP_SESSION=true, and it's happening with Roda, Sinatra, and plain old Rack, so I don't think it's a problem with the app. You can browse the source code [here](https://github.com/mwpastore/FrameworkBenchmarks/tree/roda-sequel/frameworks/Ruby/roda-sequel) (Roda version). It's really quite simplistic.

**Comment by OnixGH** [comment]
I'm just going by the logs you provided, which demonstrate a problem communicating with all 3 initial processes (16485, 16506, 16467). This is almost always the result of an app process crash, or in a handful of cases a process that cleans up /tmp/.

I'm not saying the app code itself is causing the issue, it could be anything related to the app process, such as the Ruby version, or the system itself. 

Passenger is "special" in the sense that it uses UNIX domain sockets for performance (`_PASSENGER_FORCE_HTTP_SESSION=true` actually solved UNIX socket implementation issues in older JRuby versions), although I haven't heard about any reports of that vs. 2.3/2.4 you could try with a different Ruby version, and on a different system.

Just to be absolutely sure the /tmp folder is not the problem, you could also try [configuring it](https://www.phusionpassenger.com/library/config/standalone/reference/#--instance-registry-dir-instance_registry_dir) to a different location.

**Comment by mwpastore** [comment]
I'm having trouble reproducing the issue on a similarly-configured VPS so the issue may be specific to Vagrant or how this image is configured. I'll keep poking at it.

**Comment by mwpastore** [comment]
The socket directory definitely *does* exist after the warmup, but it goes away as soon as `wrk` gets going; presumably it gets cleaned up when the RubyApp processes die.

**Comment by OnixGH** [comment]
@mwpastore any updates on this?

**Comment by OnixGH** [comment]
Closing due to inactivity.
