### ISSUE TITLE
Apache 2.4, Passenger 5.1.12, Ruby 2.5.0 and Ruby 2.3.6- errors in log

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2013]
On one Apache-server used 2 versions of Ruby: 2.3.6 and 2.5.0
default is Ruby 2.5.0

```
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/preloader
_shared_helpers.rb:79:
App 10610 stderr: [BUG] Segmentation fault at 0x0000000000001246
App 10610 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 10610 stderr:
App 10610 stderr: -- Control frame information -----------------------------------------------
App 10610 stderr: c:0007 p:---- s:0034 e:000033 CFUNC  :detach_process
App 10610 stderr: c:0006 p:0270 s:0030 e:000029 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/preloader_shar
App 10610 stderr: c:0005 p:0288 s:0022 e:000021 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/preloader_shar
App 10610 stderr: c:0004 p:0143 s:0009 e:000008 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/helper
-scripts/rack-preloader.rb:157
App 10610 stderr: c:0003 p:0011 s:0006 e:000005 CLASS  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/helper
-scripts/rack-preloader.rb:30
App 10610 stderr: c:0002 p:0038 s:0004 E:001a10 EVAL   /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/helper
-scripts/rack-preloader.rb:29 [FINISH]
App 10610 stderr: c:0001
App 10610 stderr: p:0000 s:0002 E:000a60 (none) [FINISH]
App 10610 stderr:
App 10610 stderr: -- Ruby level backtrace information ----------------------------------------
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/helper-scripts/rack-preloader.rb:29:in `<ma
in>'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/helper-scripts/rack-preloader.rb:30:in `<mo
dule:PhusionPassenger>'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/helper-scripts/rack-preloader.rb:157:in `<m
odule:App>'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/preloader
_shared_helpers.rb:140:in `run_main_loop'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/preloader
_shared_helpers.rb:79:in `accept_and_process_next_client'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/preloader
_shared_helpers.rb:79:in `detach_process'
App 10610 stderr:
App 10610 stderr: -- Machine register context ------------------------------------------------
App 10610 stderr:  RIP: 0x0000000000001246 RBP: 0x00000000000053fd RSP: 0x00007fff222db528
App 10610 stderr:  RAX: 0x0000000000000000 RBX: 0x000055a78f6786d0 RCX: 0x00007fb93ae97108
App 10610 stderr:  RDX: 0x00007fb938bb6460 RDI: 0x000000000000001e RSI: 0x00000000000053fd
App 10610 stderr:   R8: 0x0000000000000003  R9: 0x000055a78fdadf68 R10: 0x000055a78fda3e90
App 10610 stderr:  R11: 0x0000000000000206 R12: 0x0000000000018000 R13: 0x000055a78fdadf68
App 10610 stderr:  R14: 0x000055a78fdae738 R15: 0x0000000000000001 EFL: 0x0000000000010206
App 10610 stderr:
App 10610 stderr: -- C level backtrace information -------------------------------------------
App 10750 stdout:
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/utils/nat
ive_support_utils.rb:38: [BUG]
App 10610 stderr: Segmentation fault at 0x0000000000001306
App 10610 stderr: ruby 2.3.6p384 (2017-12-14 revision 61254) [x86_64-linux]
App 10610 stderr:
App 10610 stderr: -- Control frame information -----------------------------------------------
App 10610 stderr: c:0008 p:---- s:0044 e:000043 CFUNC  :split_by_null_into_hash
App 10610 stderr: c:0007 p:0018 s:0040 e:000039 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/utils/native_s
App 10610 stderr: c:0006 p:0053 s:0036 e:000035 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/request_handle
App 10610 stderr: c:0005 p:0131 s:0027 e:000026
App 10610 stderr: METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/re
quest_handle
App 10610 stderr: c:0004 p:0098 s:0017 e:000016 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/request_handle
App 10610 stderr: c:0003 p:0065 s:0009 e:000008 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/request_handle
App 10610 stderr: c:0002 p:0030 s:0005 e:000004 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_s
upportlib/phusion_passenger/utils.rb:113 [FINISH]
App 10610 stderr: c:0001
App 10610 stderr: p:---- s:0002 e:000001 (none) [FINISH]
App 10610 stderr:
App 10610 stderr: -- Ruby level backtrace information ----------------------------------------
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/utils.rb:
113:in `block in create_thread_and_abort_on_exception'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_h
andler.rb:416:in `block (3 levels) in start_threads'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_h
andler/thread_handler.rb:113:in `main_loop'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_h
andler/thread_handler.rb:146:in `accept_and_process_next_request'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/request_h
andler/thread_handler.rb:224:in `parse_session_request'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/utils/nat
ive_support_utils.rb:38:in `split_by_null_into_hash'
App 10610 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/passenger-5.1.12/src/ruby_supportlib/phusion_passenger/utils/nat
ive_support_utils.rb:38:in `split_by_null_into_hash'
App 10610 stderr:
App 10610 stderr: -- Machine register context ------------------------------------------------
App 10610 stderr:  RIP: 0x0000000000001306 RBP: 0x00007fb930001b6b RSP: 0x00007fb92f7f63c8
App 10610 stderr:  RAX: 0x0000000000000000 RBX: 0x00007fb930001960
App 10610 stderr:  RCX: 0x00007fb934091158
App 10610 stderr:  RDX: 0x00007fb938bb6590 RDI: 0x000055a78fdae738 RSI: 0x000055a78fb15a30
App 10610 stderr:   R8: 0x0000000000000003  R9: 0x000055a78fdae1c0 R10: 0x000055a78fda3e90
App 10610 stderr:  R11: 0x00007fb934091198 R12: 0x00007fb930001960 R13: 0x000055a78fb15a30
App 10610 stderr:  R14: 0x000055a78fdae738 R15: 0x0000000000000001 EFL: 0x0000000000010202
App 10610 stderr:
App 10610 stderr: -- C level backtrace information -------------------------------------------
[ W 2017-12-27 21:15:43.7242 10579/T7 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-1] Sending 502 response: application did not send a comp
lete response
App 10765 stdout:
App 10676 stderr: WARN: tilt autoloading 'sass' in a non thread-safe way; explicit require 'sass' suggested.
[ W 2017-12-27 21:15:45.0108 10579/T3 age/Cor/App/Poo/AnalyticsCollection.cpp:102 ]: Process (pid=10750, group=/home/ruby/projects.old/znani
e) no longer exists! Detaching it from the pool.
[ N 2017-12-27 21:15:45.0108 10579/T3 age/Cor/CoreMain.cpp:994 ]: Checking whether to disconnect long-running connections for process 10750,
 application /home/ruby/projects.old/znanie
[ E 2017-12-27 21:15:45.0113 10579/Tt age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/ruby/projects.old/
znanie: An error occurred while starting the application. Unable to connect to the preloader's socket: Cannot connect to Unix socket '/tmp/p
assenger.dwRb8Ij/apps.s/preloader.tl96s2': Connection refused (errno=111)
  Error ID: 5641e197
  Error details saved to: /tmp/passenger-error-5wEvDZ.html
  Message from application: An error occurred while starting the application. Unable to connect to the preloader&apos;s socket: Cannot conne
ct to Unix socket &apos;/tmp/passenger.dwRb8Ij/apps.s/preloader.tl96s2&apos;: Connection refused (errno=111)<br>
<h2>Raw process output:</h2>
(empty)

[ W 2017-12-27 21:15:45.0114 10579/Tt age/Cor/Spa/SmartSpawner.h:750 ]: An error occurred while spawning a process: An error occurred while
starting the application. Unable to connect to the preloader's socket: Cannot connect to Unix socket '/tmp/passenger.dwRb8Ij/apps.s/preloade
r.tl96s2': Connection refused (errno=111)
[ W 2017-12-27 21:15:45.0114 10579/Tt age/Cor/Spa/SmartSpawner.h:751 ]: The application preloader seems to have crashed, restarting it and t
rying again...
```

**Comment by CamJN** [comment]
@Sega100500 Since this crash appears to have happened in a Passenger component could you please provide your Linux distro and version.

**Comment by Sega100500** [comment]
@CamJN 
Linux Debian 8.10 Jessie
Apache 2.4
I use 2 versions of Ruby - 2.3.6 and 2.5.0 - for different sites
Passenger compiled on both Ruby, but used from Ruby 2.5.0

**Comment by OnixGH** [comment]
Issue was filed as duplicate in #2022 and #2040, discussion continued in the latter, so closing this one.
