### ISSUE TITLE
5.2.0 Apache module won’t compile on FreeBSD 11.1

### ISSUE THREAD

**Issue by PeterMozesMerl** [phusion/passenger#2031]
I reinstalled RVM and Ruby as usual. The Ruby version is the same as I had with Passenger 5.1.12

```
c++ -o buildout/support-binaries/AgentMain.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Isrc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/agent/AgentMain.cpp
c++ -o buildout/support-binaries/AgentFundamentals.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Isrc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/agent/Shared/Fundamentals/Implementation.cpp
c++ -o buildout/support-binaries/WatchdogMain.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Isrc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/agent/Watchdog/WatchdogMain.cpp
c++ -o buildout/support-binaries/CoreMain.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Isrc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/agent/Core/CoreMain.cpp
c++ -o buildout/support-binaries/CoreApplicationPool.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Isrc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/agent/Core/ApplicationPool/Implementation.cpp
In file included from src/agent/Core/ApplicationPool/Implementation.cpp:39:
src/cxx_supportlib/Hooks.h:146:31: error: use of undeclared identifier 'WEXITSTATUS'
                        ") exited with status " << WEXITSTATUS(info.status));
                                                   ^
1 error generated.
rake aborted!
Command failed with status (1): [c++ -o buildout/support-binaries/CoreApplicationPool.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Isrc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Isrc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_ATTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -Wno-unused-local-typedefs -DHAS_UNORDERED_MAP -c src/agent/Core/ApplicationPool/Implementation.cpp]
/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.0/build/support/cplusplus.rb:53:in `run_compiler'
/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.0/build/support/cplusplus.rb:104:in `compile_cxx'
/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.0/build/support/cplusplus.rb:162:in `block in define_cxx_object_compilation_task'
/home/mage/.rvm/gems/ruby-2.4.2@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => apache2 => buildout/support-binaries/PassengerAgent => buildout/support-binaries/CoreApplicationPool.o
(See full trace by running task with --trace)

--------------------------------------------

It looks like something went wrong

Please read our documentation for troubleshooting tips:

   https://www.phusionpassenger.com/library/install/apache/
   https://www.phusionpassenger.com/library/admin/apache/troubleshooting/

If that doesn't help, please use our support facilities. We'll do our best to help you.

   https://www.phusionpassenger.com/support
mage@xxx ~ $ uname -a
FreeBSD xxx 11.1-RELEASE-p4 FreeBSD 11.1-RELEASE-p4 #0: Tue Nov 14 06:12:40 UTC 2017     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64
```

Everything is up-to-date. That’s why I reinstalled RVM and Ruby.

**Comment by CamJN** [comment]
Can you find `WEXITSTATUS` in the `apr` headers?

**Comment by PeterMozesMerl** [comment]
I’m not sure how to do that. If you mean the source code, the rest of the system was installed as binaries.

**Comment by CamJN** [comment]
Yes I do mean the headers from the source code, Passenger needs them to properly compile against the apache on your system. Please provide the output from `passenger-config about detect-apache2`.

**Comment by reicheltd** [comment]
Same error for me on FreeBSD 10.3 using the `passenger-install-nginx-module` installer

**Comment by CamJN** [comment]
@reicheltd You get an error saying `WEXITSTATUS` isn't declared when compiling for nginx?

**Comment by reicheltd** [comment]
```In file included from src/agent/Core/ApplicationPool/Implementation.cpp:39:
src/cxx_supportlib/Hooks.h:146:31: error: use of undeclared identifier 'WEXITSTATUS'
                        ") exited with status " << WEXITSTATUS(info.status));
                                                   ^
src/cxx_supportlib/LoggingKit/Logging.h:95:51: note: expanded from macro 'P_INFO'
        Passenger::LoggingKit::INFO, __FILE__, __LINE__, expr)
                                                         ^
src/cxx_supportlib/LoggingKit/Logging.h:48:16: note: expanded from macro 'P_LOG'
                        _ostream << expr << "\n"; \
                                    ^
1 error generated.
rake aborted!
Command failed with status (1): [c++ -o buildout/support-binaries/CoreApplicationPool.o  -Isrc/agent -Isrc/cxx_supportlib -Isrc/cxx_supportlib/vendor-copy -Is
rc/cxx_supportlib/vendor-modified -Isrc/cxx_supportlib/vendor-modified/libev -Wno-ambiguous-member-template -Isrc/cxx_supportlib/vendor-copy/libuv/include -Is
rc/cxx_supportlib/vendor-copy/websocketpp -I/usr/local/include -DHAS_CURL_EASY_RESET -D_REENTRANT -I/usr/local/include -Wall -Wextra -Wno-unused-parameter -Wn
o-parentheses -Wpointer-arith -Wwrite-strings -Wno-long-long -Wno-missing-field-initializers -Wno-ambiguous-member-template -fvisibility=hidden -DVISIBILITY_A
TTRIBUTE_SUPPORTED -DHAVE_ACCEPT4 -DHAS_SFENCE -DHAS_LFENCE -DPASSENGER_DEBUG -DBOOST_DISABLE_ASSERTS -g -fno-limit-debug-info -DHAS_UNORDERED_MAP -c src/agen
t/Core/ApplicationPool/Implementation.cpp]

Tasks: TOP => nginx => nginx_without_native_support => buildout/support-binaries/PassengerAgent => buildout/support-binaries/CoreApplicationPool.o
(See full trace by running task with --trace)
--------------------------------------------

It looks like something went wrong```

**Comment by reicheltd** [comment]
Sorry I did not see the "Apache" title. But the error occured when I used `passenger-install-nginx-module`. I dont use Apache.

**Comment by CamJN** [comment]
Yes, that's actually incredibly helpful, it seems that there's a non-apr defined `WEXITSTATUS` from `sys/wait.h` that I didn't know about, so I've been looking in the wrong place. can you run the following command and reply with the output?

`fgrep -RH WEXITSTATUS /usr/include/`

**Comment by reicheltd** [comment]
`/usr/include/sys/wait.h:#define WEXITSTATUS(x)  (_W_INT(x) >> 8)`

**Comment by CamJN** [comment]
Awesome, thanks. This should be much easier to figure out now.

**Comment by reicheltd** [comment]
Thank you too. Glad I can help

**Comment by reicheltd** [comment]
You can always contact me for testings in FreeBSD. I've been using FreeBSD, nginx, passenger for some time now.

**Comment by PeterMozesMerl** [comment]
FreeBSD 11.1 gives the same output as the one in @reicheltd’s comment.

For FreeBSD + Apache testing, you can contact me.

**Comment by CamJN** [comment]
Ok there's a branch at https://github.com/phusion/passenger/tree/GH2031-fix_freebsd_compilation could you both try and compile it on your systems?

**Comment by PeterMozesMerl** [comment]
It didn’t compile.

```
rm -rf buildout/apache2/module_libpassenger_common
rm -rf buildout/apache2/mod_passenger.o buildout/apache2/CBindings.o buildout/apache2/Config.o buildout/apache2/Bucket.o buildout/apache2/Hooks.o buildout/apache2/mod_passenger.so
rake aborted!
LoadError: cannot load such file -- /usr/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.1/build/support/vendor/cxxcodebuilder/lib/cxxcodebuilder
/usr/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.1/Rakefile:42:in `require_build_system_file'
/usr/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.1/build/support/general.rb:28:in `initialize'
/usr/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.1/build/common_library.rb:265:in `new'
/usr/home/mage/.rvm/gems/ruby-2.4.2/gems/passenger-5.2.1/build/common_library.rb:265:in `block in <top (required)>'
/home/mage/.rvm/gems/ruby-2.4.2/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => apache2 => buildout/apache2/mod_passenger.so => buildout/apache2/module_libpassenger_common/LoggingKit.o => src/cxx_supportlib/Constants.h
(See full trace by running task with --trace)
```

This is a CI machine. Its config is similar to my productions servers. 5.1.12 compiles on it.

I tried to install the specific branch both with Gemfile + bundler and git clone + gem build + gem install. The vendor directory was not there when I ran passenger-install-apache2-module.

**Comment by CamJN** [comment]
@PeterMozesMerl it looks like you didn't checkout the submodules. `git submodule init && git submodule update` should clear that up.

**Comment by PeterMozesMerl** [comment]
@CamJN Thank you. It has been compiled.

As far as I can tell you from a few page loads, it works fine.
