### ISSUE TITLE
RuntimeError: Illegal character ‘&#5;’ in raw string “&#5;“

### ISSUE THREAD

**Issue by armanadhitama** [phusion/passenger#2039]
Hi,

I having problem when restarting Passenger on my VPS (both using `passenger-config restart-app /` or through capistrano using deploy command). Sometimes restarting nginx multiple times fixing this issue, but sometimes don't. Have someone experiencing same issue with this?

I'm using version 5.1.8
```
DEBUG [358f9ead]     /usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:96:in `rescue in parse’
DEBUG [358f9ead]     : #<RuntimeError: Illegal character ‘&#5;’ in raw string “&#5;“> (REXML::ParseException
DEBUG [358f9ead]     )
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/text.rb:162:in `block in check’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/text.rb:154:in `scan’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/text.rb:154:in `check’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/text.rb:121:in `initialize’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:47:in `new’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:47:in `parse’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/document.rb:288:in `build’
/usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/document.rb:45:in `initialize’
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:257:in `new’
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:257:in `query_pool_xml’
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:207:in `select_app_group_name_by_app_root_regex’
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:146:in `select_app_group_name’
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:46:in `run’
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/main.rb:78:in `run!'
/usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/bin/passenger-config:38:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.4/bin/passenger-config:23:in `load’
/usr/local/rvm/gems/ruby-2.3.4/bin/passenger-config:23:in `<main>'
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval’
/usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
...
Illegal character ‘&#5;’ in raw string “&#5;”
Line: 2
Position: 24953
Last 80 unconsumed characters:
</code_revision>
   from /usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/parsers/treeparser.rb:21:in `parse’
   from /usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/document.rb:288:in `build’
   from /usr/local/rvm/rubies/ruby-2.3.4/lib/ruby/2.3.0/rexml/document.rb:45:in `initialize’
DEBUG [358f9ead]         from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:257:in `new’
   from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:257:in `query_pool_xml’
   from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:207:in `select_app_group_name_by_app_root_regex’
   from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:146:in `select_app_group_name’
   from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/restart_app_command.rb:46:in `run’
   from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/src/ruby_supportlib/phusion_passenger/config/main.rb:78:in `run!'
   from /usr/local/rvm/gems/ruby-2.3.4/gems/passenger-5.1.8/bin/passenger-config:38:in `<top (required)>'
   from /usr/local/rvm/gems/ruby-2.3.4/bin/passenger-config:23:in `load’
   from /usr/local/rvm/gems/ruby-2.3.4/bin/passenger-config:23:in `<main>'
   from /usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `eval’
   from /usr/local/rvm/gems/ruby-2.3.4/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by CamJN** [comment]
The invalid character is coming from your app's output, perhaps check the character encoding is consistent in your app. On an unrelated note you shouldn't use 5.1.8 there have been vulnerabilities fixed in Passenger since then, so you should try and upgrade to the latest version.

**Comment by armanadhitama** [comment]
@CamJN thanks for your help, i'll check them :)
