### ISSUE TITLE
Passenger + Nginx

### ISSUE THREAD

**Issue by vitorgamer58** [phusion/passenger#2050]
I Get this erro
```
[ E 2018-03-27 19:53:05.5809 12549/T6 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is f2ea4699. Please see earlier logs for details about the $
App 12665 stdout:
App 12665 stdout:
[ E 2018-03-27 19:55:17.1362 12549/Te age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/deploy/peatio/current: An error occurred while starting up the preloader.
  Error ID: aae18d67
  Error details saved to: /tmp/passenger-error-Zh7kky.html
  Message from application: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse'
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
  /home/deploy/peatio/current/config/application.rb:15:in `<module:Peatio>'
  /home/deploy/peatio/current/config/application.rb:14:in `<top (required)>'
  /home/deploy/peatio/current/config/environment.rb:2:in `require'
  /home/deploy/peatio/current/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'

  Message from application: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse'
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:318:in `parse'
  /home/deploy/.rbenv/versions/2.2.1/lib/ruby/2.2.0/psych.rb:245:in `load'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:21:in `raw'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro.rb:17:in `env'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/figaro-0.7.0/lib/figaro/railtie.rb:7:in `block in <class:Railtie>'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `call'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:36:in `execute_hook'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `each'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/activesupport-4.0.12/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/railties-4.0.12/lib/rails/application.rb:67:in `inherited'
  /home/deploy/peatio/current/config/application.rb:15:in `<module:Peatio>'
  /home/deploy/peatio/current/config/application.rb:14:in `<top (required)>'
  /home/deploy/peatio/current/config/environment.rb:2:in `require'
  /home/deploy/peatio/current/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
  /home/deploy/peatio/current/vendor/bundle/ruby/2.2.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'


[ E 2018-03-27 19:55:17.1546 12549/T6 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-2] Cannot checkout session because a spawning error occurred. The identifier of the error is aae18d67. Please see earlier logs for details about the $

```
Ubuntu 14.04
VPS VULTR

**Comment by OnixGH** [comment]
This is an error message from your application:
```Message from application: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1 (Psych::SyntaxError)
```

Passenger can't start your app until you fix it.
