### ISSUE TITLE
Passenger 5.3.2 start BUG in log

### ISSUE THREAD

**Issue by Sega100500** [phusion/passenger#2091]
Linux Debian 8 Jessie
Server version: Apache/2.4.10 (Debian)
Passenger 5.3.2
Ruby 2.5.1 & 2.3.7

afte start Apache-server in passenger log:

```
App 22393 output: /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:134: [BUG]
App 22393 output: Segmentation fault at 0x0000000000001246
App 22393 output: ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
App 22393 output:
App 22393 output: -- Control frame information -----------------------------------------------
App 22393 output: c:0008 p:---- s:0042 e:000041 CFUNC  :detach_process
App 22393 output: c:0007 p:0191 s:0038 e:000037 METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 22393 output: c:0006 p:0081 s:0030 e:000029 METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 22393 output: c:0005 p:0081 s:0022 e:000021 METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_su
pportlib/phusion_passenger/preloader_share
App 22393 output: c:0004 p:0243 s:0011 e:000010 CLASS  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/helper-
scripts/rack-preloader.rb:207
App 22393 output: c:0003 p:0011 s:0006 e:000005 CLASS  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/helper-
scripts/rack-preloader.rb:30
App 22393 output: c:0002 p:0038 s:0004 E:001e70 EVAL   /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/helper-
scripts/rack-preloader.rb:29 [FINISH]
App 22393 output:
App 22393 output: c:0001 p:0000 s:0002 E:0017d0 (none) [FINISH]
App 22393 output:
App 22393 output: -- Ruby level backtrace information ----------------------------------------
```

```
App 22393 output: /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_passenger/preloader_
shared_helpers.rb:134:in `detach_process'
App 22393 output:
App 22393 output: -- Machine register context ------------------------------------------------
App 22393 output:  RIP: 0x0000000000001246
App 22393 output:  RBP: 0x000000000000b08f RSP: 0x00007ffdef5ce648
App 22393 output:  RAX: 0x0000000000000000 RBX: 0x00005574e94856d0 RCX: 0x00007f87b4edd148
App 22393 output:  RDX: 0x00007f87b2bfc460 RDI: 0x000000000000001e RSI: 0x000000000000b08f
App 22393 output:   R8: 0x0000000000000003  R9: 0x00005574e99465c0 R10: 0x00005574e9ca6590
App 22393 output:  R11: 0x0000000000000246 R12: 0x0000000000018000 R13: 0x00005574e99465c0
App 22393 output:  R14: 0x00005574e9946f70 R15: 0x0000000000000001 EFL: 0x0000000000010206
App 22393 output:
App 22393 output: -- C level backtrace information -------------------------------------------
App 22599 output: /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38:
App 22599 output: [BUG] Segmentation fault at 0x0000000000001306
App 22599 output: ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux]
App 22599 output:
App 22599 output: -- Control frame information -----------------------------------------------
App 22599 output: c:0008 p:----
App 22599 output: s:0044 e:000043 CFUNC  :split_by_null_into_hash
App 22599 output: c:0007 p:0018 s:0040 e:000039 METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_su
pportlib/phusion_passenger/utils/native_su
App 22599 output: c:0006
App 22599 output: p:0053 s:0036 e:000035 METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportli
b/phusion_passenger/request_handler
App 22599 output: c:0005 p:0131 s:0027 e:000026
App 22599 output: METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_passenger/req
uest_handler
App 22599 output: c:0004 p:0085 s:0017
App 22599 output: e:000016 METHOD /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_pass
enger/request_handler
App 22599 output: c:0003
App 22599 output: p:0065 s:0009 e:000008 BLOCK  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportli
b/phusion_passenger/request_handler
App 22599 output: c:0002 p:0030 s:0005 e:000004
App 22599 output: BLOCK  /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_passenger/uti
ls.rb:113 [FINISH]
```

```
App 22599 output: /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/src/ruby_supportlib/phusion_passenger/utils/nati
ve_support_utils.rb:38:in `split_by_null_into_hash'
App 22599 output:
App 22599 output: -- Machine register context ------------------------------------------------
App 22599 output:  RIP: 0x0000000000001306
App 22599 output:  RBP: 0x00007f87a8001950 RSP: 0x00007f87adacd3b8
App 22599 output:  RAX: 0x0000000000000000 RBX: 0x00007f87a8001820 RCX: 0x00007f87adacf158
App 22599 output:  RDX: 0x00007f87b2bfc590 RDI: 0x00005574e9946f70 RSI: 0x00005574ea0a1748
App 22599 output:   R8: 0x0000000000000003  R9: 0x00005574e9946840 R10: 0x00005574e9ca6590
App 22599 output:  R11: 0x00007f87adacf198 R12: 0x00007f87a8001820 R13: 0x00005574ea0a1748
App 22599 output:  R14: 0x00005574e9946f70 R15: 0x0000000000000001 EFL: 0x0000000000010206
App 22599 output:
App 22599 output: -- C level backtrace information -------------------------------------------
[ W 2018-06-13 14:56:43.3815 22341/T7 age/Cor/Con/InternalUtils.cpp:96 ]: [Client 1-1] Sending 502 response: application did not send a comp
lete response
```

**Comment by CamJN** [comment]
Do you have any of the env vars described [here](https://github.com/rbenv/ruby-build#custom-build-configuration) set? 

Would it be possible to check the hash of the ruby interpreter and native extensions with these commands:
`openssl sha256 < /home/ruby/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/passenger-5.3.2/buildout/ruby/ruby-2.5.1-x86_64-linux/passenger_native_support.so`
`openssl sha256 < /home/ruby/.rbenv/versions/2.5.1/bin/ruby`

**Comment by CamJN** [comment]
dup of https://github.com/phusion/passenger/issues/2141
