### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by kevinshirley** [phusion/passenger#2111]
I uploaded my node.js app on the server and I got the error below. The server runs Ubuntu 14.04 . I have updated the node version on the server to v10.9.0 and it still gives me this error:
---------
```
An error occurred while starting the web application. It exited before signalling successful startup back to Phusion Passenger. Please read this article for more information about this problem.
Raw process output:
/home/kevinshirley/tripimagine.com/node_modules/mongoose/lib/index.js:7
const Schema = require('./schema');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/kevinshirley/tripimagine.com/node_modules/mongoose/index.js:7:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by CamJN** [comment]
This is more of a stackoverflow question, closing unless there's more to go on.
