### ISSUE TITLE
The Phusion Passenger application server tried to start the web application. But the application itself (and not Passenger) encountered an operating system error.  The error reported by the operating system is:

### ISSUE THREAD

**Issue by dipesh989** [phusion/passenger#2185]
The Phusion Passenger application server tried to start the web application. But the application itself (and not Passenger) encountered an operating system error.  The error reported by the operating system is:
```
Permission denied @ rb_sysopen - /var/www/ambeetech/html/tmp/cache/bootsnap-load-path-cache.25095.48042.tmp (Errno::EACCES)
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:77:in `binwrite'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:77:in `dump_data'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:137:in `push_paths_locked'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:120:in `block in reinitialize'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:114:in `synchronize'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:114:in `reinitialize'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache.rb:38:in `new'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache.rb:38:in `setup'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap.rb:24:in `setup'
  /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/setup.rb:27:in `<top (required)>'
  /var/www/ambeetech/html/config/boot.rb:4:in `require'
  /var/www/ambeetech/html/config/boot.rb:4:in `<top (required)>'
  /var/www/ambeetech/html/config/application.rb:1:in `require_relative'
  /var/www/ambeetech/html/config/application.rb:1:in `<top (required)>'
  /var/www/ambeetech/html/config/environment.rb:2:in `require_relative'
  /var/www/ambeetech/html/config/environment.rb:2:in `<top (required)>'
  config.ru:3:in `require_relative'
  config.ru:3:in `block in <main>'
  /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

The stdout/stderr output of the subprocess so far is:

 [passenger_native_support.so] trying to compile for the current user (nobody) and Ruby interpreter...
     (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
     Warning: compilation didn't succeed. To learn why, read this file:
     /tmp/passenger_native_support-13gk9n8.log
 [passenger_native_support.so] finding downloads for the current Ruby interpreter...
     (set PASSENGER_DOWNLOAD_NATIVE_SUPPORT_BINARY=0 to disable)
     # tar xzf rubyext-ruby-2.6.1-x86_64-linux.tar.gz
     # rm -f rubyext-ruby-2.6.1-x86_64-linux.tar.gz
     Checking whether downloaded binary is usable...
     # /usr/local/bin/ruby -I. test.rb
     /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': libruby.so.2.6: cannot open shared object file: No such file or directory - /tmp/passenger-native-support-1oigjaw/passenger_native_support.so (LoadError)
     	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
     	from test.rb:2:in `<main>'
     Binary is not usable.
 [passenger_native_support.so] will not be used (can't compile or download) 
  --> Passenger will still operate normally.
Error: The application encountered the following error: Permission denied @ rb_sysopen - /var/www/ambeetech/html/tmp/cache/bootsnap-load-path-cache.25095.48042.tmp (Errno::EACCES)
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:77:in `binwrite'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:77:in `dump_data'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:55:in `commit_transaction'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/store.rb:47:in `transaction'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:137:in `push_paths_locked'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:120:in `block in reinitialize'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:114:in `synchronize'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:114:in `reinitialize'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache/cache.rb:14:in `initialize'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache.rb:38:in `new'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/load_path_cache.rb:38:in `setup'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap.rb:24:in `setup'
    /usr/local/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.1/lib/bootsnap/setup.rb:27:in `<top (required)>'
    /var/www/ambeetech/html/config/boot.rb:4:in `require'
    /var/www/ambeetech/html/config/boot.rb:4:in `<top (required)>'
    /var/www/ambeetech/html/config/application.rb:1:in `require_relative'
    /var/www/ambeetech/html/config/application.rb:1:in `<top (required)>'
    /var/www/ambeetech/html/config/environment.rb:2:in `require_relative'
    /var/www/ambeetech/html/config/environment.rb:2:in `<top (required)>'
    config.ru:3:in `require_relative'
    config.ru:3:in `block in <main>'
    /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
    /usr/local/lib/ruby/gems/2.6.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `<main>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:380:in `run_block_and_record_step_progress'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by CamJN** [comment]
The application encountered the following error: Permission denied @ rb_sysopen - /var/www/ambeetech/html/tmp/cache/bootsnap-load-path-cache.25095.48042.tmp (Errno::EACCES)
