### ISSUE TITLE
Unable to install Apache Portable Runtime (APR) development headers

### ISSUE THREAD

**Issue by idknox** [phusion/passenger#2193]
Using Passenger version 4.0.41 or 5.1.1, I get the following output when running `passenger-install-apache2-module`.
```
 * Checking for Apache Portable Runtime (APR) development headers...
--------------------------------------------
*** EXCEPTION: No such file or directory - /usr/local/Cellar/apr/1.6.3/bin/apr-1-config (Errno::ENOENT)
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/platform_info/depcheck_specs/apache2.rb:72:in ``'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/platform_info/depcheck_specs/apache2.rb:72:in `block (2 levels) in load'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/platform_info/depcheck.rb:77:in `check'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/platform_info/depcheck.rb:321:in `block in check_all'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/platform_info/depcheck.rb:317:in `each'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/platform_info/depcheck.rb:317:in `check_all'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/abstract_installer.rb:149:in `check_dependencies'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/bin/passenger-install-apache2-module:126:in `run_steps'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/lib/phusion_passenger/abstract_installer.rb:71:in `run'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/gems/passenger-4.0.41/bin/passenger-install-apache2-module:863:in `<top (required)>'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/bin/passenger-install-apache2-module:23:in `load'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/bin/passenger-install-apache2-module:23:in `<main>'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/bin/ruby_executable_hooks:24:in `eval'
    /Users/knoxid/.rvm/gems/ruby-2.4.0@mbi/bin/ruby_executable_hooks:24:in `<main>'

--------------------------------------------

Oops, something went wrong :-(
```
Google has yielded no answers. Could you please assist?

**Comment by CamJN** [comment]
Apple removed `apr-1-config` a while back, and we've made some attempts to work around that. What version of macOS are your running? Also are your installing from the gem?

**Comment by CamJN** [comment]
Passenger 5.1.3 has some improvements in the apache detection on macOS, for example.

**Comment by idknox** [comment]
Mojave (OSX 10.14).

I was attempting to install from the gem. However, after installing via brew and following the instructions for the conf file, I was able to get up and running with no problems. Thanks for following up, you can close this I think.
