### ISSUE TITLE
nginx segfaults when locations.ini has comments 

### ISSUE THREAD

**Issue by johrstrom** [phusion/passenger#2256]
## Issue report

Hi, I self inflicted this issue and while debugging couldn't find anything here about it, so I thought I'd let you know.  When the `locations.ini` has a simple comment in it, nginx segfaults with the stack trace below. The comment that triggered this specifically was `# Ansible`. 

Obviously the fix was just to remove the commented line and if you want to close this as `wontfix` or `not a problem` or similar, that's completely OK with me - I just wanted to let someone know that this can happen and maybe provide a searchable error for the next person who may run into it.

**Question 1: What is the problem?**
- What is the expected behavior?
Passenger can read an `locations.ini` with a comment in it.

- What is the actual behavior?
Nginx segfualts with this line in journalctl

```text
kernel: nginx[20380]: segfault at 18 ip 000055fe8c71c2aa sp 00007fff016eed10 error 4 in nginx-1.17.3[55fe8c5db000+3f9000]
```
When I built a debug enabled version of Nginx I found this to be the stack trace (looking at a core dump in gdb)
```text
#0  0x000055f0b628f43e in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_begin() const ()
#1  0x000055f0b628e4cb in std::_Rb_tree<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#2  0x000055f0b628d319 in std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::find(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#3  0x000055f0b6286956 in Passenger::IniFileSection::hasKey(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const ()
#4  0x000055f0b628880c in Passenger::ResourceLocator::getOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, boost::shared_ptr<Passenger::IniFileSection> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#5  0x000055f0b6288c85 in Passenger::ResourceLocator::ResourceLocator(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#6  0x000055f0b628b7d4 in Passenger::WatchdogLauncher::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Passenger::Json::Value const&, boost::function<void ()> const&) ()
#7  0x000055f0b6286254 in psg_watchdog_launcher_start ()
#8  0x000055f0b6201523 in start_watchdog ()
#9  0x000055f0b62018f3 in init_module ()
#10 0x000055f0b611c022 in ngx_init_modules ()
#11 0x000055f0b611623c in ngx_init_cycle ()
#12 0x000055f0b60f38b0 in main ()
```

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.

Have a `# commented string` at the top of a `locations.ini` file, then try to start nginx with a passenger configuration that looks at that ini file.

**Question 2: Passenger version and integration mode**:

This was tested with both open source 5.3.26 standalone/1.14.0 nginx and 6.0.4/1.17.3 nginx. 

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[x] Other, please specify:
tar.gz(s) pulled from the releases tab of this repository.  The nginx tar.gz and the passenger tar.gz (versions given above).

**Question 7: Anything else about your setup that we should know?**

I think it's a fairly straight forward issue and I've already found the root cause and resolution. I'm happy to provide anything else you would want though.

---

We strive for quality and appreciate you taking the time to submit a report! Please note that if you want guaranteed response times and priority issue support we encourage you to join our [enterprise customer](https://www.phusionpassenger.com/enterprise) base. They also provide us with the means to continue our high level of open source support!

**Comment by CamJN** [comment]
Thanks for the report
