### ISSUE TITLE
Running the RubyMine debugger with Passenger as the app server leads to the debugger being unable to connect.

### ISSUE THREAD

**Issue by MattDahEpic** [phusion/passenger#2302]
## Issue report

**Question 1: What is the problem?**
Running the RubyMine debugger with Passenger as the app server leads to the debugger being unable to connect.
- What is the expected behavior?
I would expect Passenger to be a drop in replacement for a freshly generated rails app and that I could run any way that I could run with the default Puma.
- What is the actual behavior?
Running the debugger produces the following error (ports will change):
```
Fast Debugger (ruby-debug-ide 0.8.0.beta24, debase 0.3.0.beta34, file filtering is supported, block breakpoints supported, smart steps supported, obtaining return values supported, partial obtaining of instance variables supported) listens on 0.0.0.0:56057
=> Booting Passenger application server
=> Rails 6.0.3.2 application starting in development http://0.0.0.0:3000
=> Run `rails server --help` for more startup options
762: connection failed(1)
Exception: Connection refused - connect(2) for "127.0.0.1" port 56058
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `initialize'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `open'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `block in notify_dispatcher_if_needed'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:166:in `times'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:166:in `notify_dispatcher_if_needed'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:123:in `block in start_control'
762: connection failed(2)
Exception: Connection refused - connect(2) for "127.0.0.1" port 56058
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `initialize'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `open'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `block in notify_dispatcher_if_needed'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:166:in `times'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:166:in `notify_dispatcher_if_needed'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:123:in `block in start_control'
762: connection failed(3)
Exception: Connection refused - connect(2) for "127.0.0.1" port 56058
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `initialize'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `open'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:168:in `block in notify_dispatcher_if_needed'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:166:in `times'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:166:in `notify_dispatcher_if_needed'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:123:in `block in start_control'
Fatal exception in DebugThread loop: undefined method `accept' for 3:Integer
Backtrace:
/home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ruby-debug-ide-0.8.0.beta24/lib/ruby-debug-ide.rb:131:in `block in start_control'
Exiting
Uncaught exception: Error starting Passenger
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/passenger-6.0.6/src/ruby_supportlib/phusion_passenger/rack_handler.rb:47:in `run'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:327:in `start'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:39:in `start'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:147:in `block in perform'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `tap'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands/server/server_command.rb:138:in `perform'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/command/base.rb:69:in `perform'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/command.rb:46:in `invoke'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/railties-6.0.3.2/lib/rails/commands.rb:18:in `<main>'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `block in require'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:291:in `load_dependency'
        /home/matt/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies.rb:324:in `require'
        /mnt/s/Code/Ruby/example_app/bin/rails:9:in `<top (required)>'

Process finished with exit code 1
```
- How can we reproduce it? 
1. Install a fresh WSL version 2 Ubuntu 20.04 installation with rbenv and the latest available ruby (2.7.1).
2. Create a new rails app on a WSL mounted windows drive (/mnt/c)
3. Load the project in the latest version of RubyMine, add rbenv as the version manager  and try running the default Run and Debug profiles, installing the debugging gems if it asks.
4. Change `gem 'puma', '~> 4.1'` to `gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"` in the gemfile and bundle install.
5. Run the Run and Debug configurations again, noticing that Run acts as expected and Debug presents the above error.

The issue occurs on both a new and existing Rails codebase, does not occur with Puma or on a plain ruby script (ruling out debugger problems), whether or not any firewall is enabled (ruling out https://github.com/microsoft/WSL/issues/4139), on prerelease versions of RubyMine, whether or not the codebase is on the windows disk or not, whether or not the debugger command is issued from bash or ubuntu.exe  via cmd, and whether or not the debugger command is issued from within RubyMine or not.

**Question 2: Passenger version and integration mode**:
 - open source 6.0.6 standalone

**Question 3: OS or Linux distro, platform (including version)**:
- Windows 10 2004 (19041.450) with Ubuntu 20.04 installed on WSL 2.

**Question 4: Passenger installation method**:

Your answer:
[x] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
- Ruby 2.7.1, rbenv, Rails 6.0.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
- WSL2 but otherwise no

**Question 7: Anything else about your setup that we should know?**
- In case anyone from JetBrains needs to get involved, I've been working under ticket number 2814023.

**Comment by mronian** [comment]
@MattDahEpic were you able to find a solution? I'm getting the same error.

**Comment by MattDahEpic** [comment]
> @MattDahEpic were you able to find a solution? I'm getting the same error.

I was not able to resolve this issue. Went back to using puma so I could continue working on the project.
