### ISSUE TITLE
Passenger Won't Connect

### ISSUE THREAD

**Issue by daBee** [phusion/passenger#2411]
## Issue report

**Question 1: What is the problem?**

Expected behaviour is that it serves the site properly.  It is not.  I am getting an `nginx` error report of no connection to `Passenger`.  The error shows up in the log, so I can't separate them.  

    2022/01/29 17:11:11 [error] 53638#0: *8212 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: hq3.local, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core:", host: "hq3.local"

**Question 2: Passenger version and integration mode**:

```
Open Source:
passenger: stable 6.0.12 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
/opt/homebrew/Cellar/passenger/6.0.12_2 (5,008 files, 245.3MB) *
  Poured from bottle on 2022-01-29 at 17:05:00
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/passenger.rb
License: MIT
==> Dependencies
Build: nginx ✔ (nginx version: nginx/1.21.6)
Required: openssl@1.1 ✔, pcre ✔
==> Options
--HEAD
```

Not sure why, but apparently `passenger-config` is now gone:

```
passenger-config validate-install
rbenv: passenger-config: command not found

The `passenger-config' command exists in these Ruby versions:
  2.7.4
```

**Question 3: OS or Linux distro, platform (including version)**:
```
ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
Software:

    System Software Overview:

      System Version: macOS 12.1 (21C52)
      Kernel Version: Darwin 21.2.0
      Boot Volume: Primer
      Boot Mode: Normal
      Computer Name: HQ3
      User Name: Rich (rich)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 18 days 2 minutes
```

**Question 4: Passenger installation method**:
[x] OS X Homebrew

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
`ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]`

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
No

**Question 7: Anything else about your setup that we should know?**
Not that I know of at this time.

**Comment by daBee** [comment]
In fact, passenger doesn't work at all.  Commands are all gone.  

```
>>> 0:57:35 rich@HQ3 ~ ➜ sudo passenger-status
rbenv: passenger-status: command not found

The `passenger-status' command exists in these Ruby versions:
  2.7.4

>>> 0:57:53 rich@HQ3 ~ ➜
```

**Comment by daBee** [comment]
I found `passenger-config` at `/Users/rich/.rbenv/versions/2.7.4/bin/passenger-config` and added that into the the `$PATH`.  But it's looking for a `gem`.  Should I be using the gem instead of `homebrew`?  My setup is for `standalone` using `nginx`.  
```
>>> 8:39:16 rich@HQ3 crons ➜ passenger-config validate-install
Traceback (most recent call last):
	2: from /Users/rich/.rbenv/versions/2.7.4/bin/passenger-config:25:in `<main>'
	1: from /Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/rubygems.rb:297:in `activate_bin_path'
/Users/rich/.rbenv/versions/2.7.4/lib/ruby/site_ruby/2.7.0/rubygems.rb:278:in `find_spec_for_exe': can't find gem passenger (>= 0.a) with executable passenger-config (Gem::GemNotFoundException)
```

**Comment by daBee** [comment]
OK, uninstalled the `homebrew` version.  I'm using `nginx` and assuming I can use the `gem` for standalone.  

```
RF: Passenger Standalone Info
_____ Passenger Installation Test: _____

/users/rich/RF/RFS/Dev/passenger_info.sh:14: command not found: passenger-config
_____ Passenger Stats: _____

/users/rich/RF/RFS/Dev/passenger_info.sh:18: command not found: passenger-memory-stats
_____ brew info nginx --with-passenger _____

------------

_____ brew info passenger _____

passenger: stable 6.0.12 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/passenger.rb
License: MIT
==> Dependencies
Build: nginx ✔
Required: openssl@1.1 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
```  

Says it's `Not installed`, but Gemfile has `gem "passenger", "~> 6.0"`.  `bundle --list` also shows   `* passenger (6.0.12)`.

So both validated problematic...`gem` version and `homebrew` version both don't work.

**Comment by daBee** [comment]
Is there a way that I can roll back using `homebrew`?  The last episode I had with all this took over a month, and I simply cannot afford that anymore.  `Passenger` has seriously gone awry with a single update and I now see a very long time to get this looked at or commented on.  If I can get this back working, then I can `pin` it for the rest of the year so that I can get some work done.

**Comment by CamJN** [comment]
I don't think homebrew supports going backwards. Anyway, from the errors you are seeing it looks like a PATH problem, did you perhaps either switch shells (bash -> zsh for example) or has anything been installed / setup that might have changed your PATH variable or shell init files?

I'd recommend uninstalling the gem version(s) of passenger, having rbenv rehash to remove the stubs it makes for passenger, and then reinstalling the homebrew version to ensure that install isn't broken.

**Comment by daBee** [comment]
No switching.  `Mac Mini M1's`, with `Monterey 12.1` come standard with `zsh`.  Nothing has changed.  The only thing that's changed was an update where I update `gems`.  I will post later today when I try your recommendations.

**Comment by daBee** [comment]
Same errors.  I will be trying `ruby 3.1.0` overnight, but here is the `ruby 3.0.2` errors.  I rehashed after both `passenger` versions were uninstalled.  

```
>>> 17:58:58 rich@HQ3 ~ ➜ passinfo						# a script I made myself
RF: Passenger Standalone Info
_____ Passenger Installation Test: _____

rbenv: passenger-config: command not found

The `passenger-config' command exists in these Ruby versions:
  2.7.4

_____ Passenger Stats: _____

rbenv: passenger-memory-stats: command not found

The `passenger-memory-stats' command exists in these Ruby versions:
  2.7.4

_____ brew info nginx --with-passenger _____

nginx: stable 1.21.6 (bottled), HEAD
HTTP(S) server and reverse proxy, and IMAP/POP3 proxy server
https://nginx.org/
/opt/homebrew/Cellar/nginx/1.21.6 (26 files, 2.2MB) *
  Poured from bottle on 2022-01-29 at 15:56:41
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/nginx.rb
License: BSD-2-Clause
==> Dependencies
Required: openssl@1.1 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
Docroot is: /opt/homebrew/var/www

The default port has been set in /opt/homebrew/etc/nginx/nginx.conf to 8080 so that
nginx can run without sudo.

nginx will load all files in /opt/homebrew/etc/nginx/servers/.

To restart nginx after an upgrade:
  brew services restart nginx
Or, if you don't want/need a background service you can just run:
  /opt/homebrew/opt/nginx/bin/nginx -g daemon off;
==> Analytics
install: 36,902 (30 days), 115,398 (90 days), 493,296 (365 days)
install-on-request: 36,829 (30 days), 115,183 (90 days), 492,204 (365 days)
build-error: 5 (30 days)


_____ brew info passenger _____

passenger: stable 6.0.12 (bottled), HEAD
Server for Ruby, Python, and Node.js apps via Apache/NGINX
https://www.phusionpassenger.com/
/opt/homebrew/Cellar/passenger/6.0.12_2 (5,008 files, 245.3MB) *
  Poured from bottle on 2022-01-31 at 17:58:54
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/passenger.rb
License: MIT
==> Dependencies
Build: nginx ✔
Required: openssl@1.1 ✔, pcre ✔
==> Options
--HEAD
	Install HEAD version
==> Caveats
To activate Phusion Passenger for Nginx, run:
  brew install nginx
And add the following to /opt/homebrew/etc/nginx/nginx.conf at the top scope (outside http{}):
  load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
And add the following to /opt/homebrew/etc/nginx/nginx.conf in the http scope:
  passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
  passenger_ruby /usr/bin/ruby;

To activate Phusion Passenger for Apache, create /etc/apache2/other/passenger.conf:
  LoadModule passenger_module /opt/homebrew/opt/passenger/libexec/buildout/apache2/mod_passenger.so
  PassengerRoot /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini
  PassengerDefaultRuby /usr/bin/ruby
==> Analytics
install: 397 (30 days), 1,365 (90 days), 6,083 (365 days)
install-on-request: 369 (30 days), 1,253 (90 days), 5,649 (365 days)
build-error: 0 (30 days)

##### Homebrew installation passenger_files_comparator.rb #####
Suggested / current / suggested exists?:
load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
load_module /opt/homebrew/opt/passenger/libexec/modules/ngx_http_passenger_module.so;
true

passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
passenger_root /opt/homebrew/opt/passenger/libexec/src/ruby_supportlib/phusion_passenger/locations.ini;
true

passenger_ruby /usr/bin/ruby;
passenger_ruby /Users/rich/.rbenv/shims/ruby; 			DIFFERENT
true



_____ Ruby Info (programming language): _____

/Users/rich/.rbenv/shims/ruby
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [arm64-darwin21]
_____ nginx version: _____

nginx version: nginx/1.21.6
_____ OS Version: _____

ProductName:	macOS
ProductVersion:	12.1
BuildVersion:	21C52
Software:

    System Software Overview:

      System Version: macOS 12.1 (21C52)
      Kernel Version: Darwin 21.2.0
      Boot Volume: Primer
      Boot Mode: Normal
      Computer Name: HQ3
      User Name: Rich (rich)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 20 days 7 minutes
```

    2022/01/31 18:03:26 [crit] 53636#0: *8366 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core failed (2: No such file or directory) while connecting to upstream, client: 192.168.1.4, server: hq3.local, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core:", host: "hq3.local"

**Comment by daBee** [comment]
OK, rebooted and tried to refresh `nginx`.  Some references to `passenger` in here:

```

2022/02/01 07:34:44 [notice] 520#0: signal 1 (SIGHUP) received from 93173, reconfiguring
2022/02/01 07:34:44 [notice] 520#0: reconfiguring
2022/02/01 07:34:44 [emerg] 520#0: mkdir() "/opt/homebrew/Cellar/nginx/1.21.5/passenger_temp" failed (2: No such file or directory)
2022/02/01 07:34:48 [crit] 53634#0: *8379 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: hq3.local, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core:", host: "hq3.local"
2022/02/01 07:35:42 [crit] 53634#0: *8379 connect() to unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core failed (2: No such file or directory) while connecting to upstream, client: 127.0.0.1, server: hq3.local, request: "GET / HTTP/1.1", upstream: "passenger:unix:/var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger.8cRkthk/agents.s/core:", host: "hq3.local"
2022/02/01 07:36:16 [notice] 520#0: signal 15 (SIGTERM) received from 1, exiting
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53631
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53632
2022/02/01 07:36:16 [notice] 53632#0: exiting
2022/02/01 07:36:16 [notice] 53631#0: exiting
2022/02/01 07:36:16 [notice] 53633#0: exiting
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53633
2022/02/01 07:36:16 [notice] 53631#0: exit
2022/02/01 07:36:16 [notice] 53632#0: exit
2022/02/01 07:36:16 [notice] 53633#0: exit
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53634
2022/02/01 07:36:16 [notice] 53634#0: exiting
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53636
2022/02/01 07:36:16 [notice] 53636#0: exiting
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53637
2022/02/01 07:36:16 [notice] 53637#0: exiting
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53635
2022/02/01 07:36:16 [notice] 53635#0: exiting
2022/02/01 07:36:16 [notice] 53634#0: exit
2022/02/01 07:36:16 [notice] 53637#0: exit
2022/02/01 07:36:16 [notice] 53635#0: exit
2022/02/01 07:36:16 [notice] 53636#0: exit
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received from 53638
2022/02/01 07:36:16 [notice] 53638#0: exiting
2022/02/01 07:36:16 [notice] 53638#0: exit
2022/02/01 07:36:16 [notice] 520#0: signal 20 (SIGCHLD) received from 53633
2022/02/01 07:36:16 [notice] 520#0: worker process 53633 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: worker process 53632 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received
2022/02/01 07:36:16 [notice] 520#0: signal 20 (SIGCHLD) received from 53635
2022/02/01 07:36:16 [notice] 520#0: worker process 53635 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received
2022/02/01 07:36:16 [notice] 520#0: signal 20 (SIGCHLD) received from 53634
2022/02/01 07:36:16 [notice] 520#0: worker process 53634 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received
2022/02/01 07:36:16 [notice] 520#0: signal 23 (SIGIO) received
2022/02/01 07:36:16 [notice] 520#0: signal 20 (SIGCHLD) received from 53631
2022/02/01 07:36:16 [notice] 520#0: worker process 53638 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: worker process 53637 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: worker process 53636 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: worker process 53631 exited with code 0
2022/02/01 07:36:16 [notice] 520#0: exit
2022/02/01 07:37:23 [notice] 556#0: using the "kqueue" event method
[ N 2022-02-01 07:37:27.1426 700/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2022-02-01 07:37:27.1835 710/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-02-01 07:37:27.1837 710/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-02-01 07:37:27.4926 710/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 710
2022/02/01 07:37:23 [notice] 556#0: nginx/1.21.6
2022/02/01 07:37:23 [notice] 556#0: built by clang 13.0.0 (clang-1300.0.29.3)
2022/02/01 07:37:23 [notice] 556#0: OS: Darwin 21.2.0
2022/02/01 07:37:23 [notice] 556#0: hw.ncpu: 8
2022/02/01 07:37:23 [notice] 556#0: net.inet.tcp.sendspace: 131072
2022/02/01 07:37:23 [notice] 556#0: kern.ipc.somaxconn: 128
2022/02/01 07:37:23 [notice] 556#0: getrlimit(RLIMIT_NOFILE): 256:9223372036854775807
2022/02/01 07:37:23 [notice] 556#0: start worker processes
2022/02/01 07:37:23 [notice] 556#0: start worker process 720
2022/02/01 07:37:23 [notice] 556#0: start worker process 721
2022/02/01 07:37:23 [notice] 556#0: start worker process 722
2022/02/01 07:37:23 [notice] 556#0: start worker process 723
2022/02/01 07:37:23 [notice] 556#0: start worker process 724
2022/02/01 07:37:23 [notice] 556#0: start worker process 725
2022/02/01 07:37:23 [notice] 556#0: start worker process 726
2022/02/01 07:37:23 [notice] 556#0: start worker process 728
2022/02/01 07:37:27 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:37:27 [notice] 556#0: signal 23 (SIGIO) received from 726
[ E 2022-02-01 07:37:31.2989 710/T5 age/Cor/SecurityUpdateChecker.h:507 ]: Security update check failed: error in server response (unparseable data). If this error persists, check your connection security and try upgrading Passenger (next check in 24 hours)
App 8475 output:  [passenger_native_support.bundle] trying to compile for the current user (rich) and Ruby interpreter...
App 8475 output:      (set PASSENGER_COMPILE_NATIVE_SUPPORT_BINARY=0 to disable)
App 8475 output:      Compilation successful. The logs are here:
App 8475 output:      /var/folders/_k/t5tdgpd93_d6vstpk4678lhh0000gn/T/passenger_native_support-1r4tamm.log
App 8475 output:  [passenger_native_support.bundle] successfully loaded.
App 8728 output: 192.168.1.4 - - [01/Feb/2022:07:43:09 -0500] "GET /favicon.ico HTTP/1.1" 404 498 0.0100
2022/02/01 07:43:36 [notice] 556#0: signal 1 (SIGHUP) received from 9135, reconfiguring
2022/02/01 07:43:36 [notice] 556#0: reconfiguring

[ N 2022-02-01 07:43:36.1053 710/T8 age/Cor/CoreMain.cpp:671 ]: Signal received. Gracefully shutting down... (send signal 2 more time(s) to force shutdown)
[ N 2022-02-01 07:43:36.1054 710/T1 age/Cor/CoreMain.cpp:1246 ]: Received command to shutdown gracefully. Waiting until all clients have disconnected...
[ N 2022-02-01 07:43:36.1055 710/T1 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 8728, application /Users/rich/Sites/HQ (production)
[ N 2022-02-01 07:43:36.1058 710/T8 Ser/Server.h:901 ]: [ServerThr.1] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1061 710/T8 Ser/Server.h:558 ]: [ServerThr.1] Shutdown finished
[ N 2022-02-01 07:43:36.1058 710/Ta Ser/Server.h:901 ]: [ServerThr.2] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1062 710/Ta Ser/Server.h:558 ]: [ServerThr.2] Shutdown finished
[ N 2022-02-01 07:43:36.1063 710/Tc Ser/Server.h:901 ]: [ServerThr.3] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1064 710/Tc Ser/Server.h:558 ]: [ServerThr.3] Shutdown finished
[ N 2022-02-01 07:43:36.1064 710/Tg Ser/Server.h:901 ]: [ServerThr.5] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1065 710/Tg Ser/Server.h:558 ]: [ServerThr.5] Shutdown finished
[ N 2022-02-01 07:43:36.1065 710/Tk Ser/Server.h:901 ]: [ServerThr.7] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1063 710/Te Ser/Server.h:901 ]: [ServerThr.4] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1066 710/Te Ser/Server.h:558 ]: [ServerThr.4] Shutdown finished
[ N 2022-02-01 07:43:36.1065 710/Tm Ser/Server.h:901 ]: [ServerThr.8] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1066 710/Tk Ser/Server.h:558 ]: [ServerThr.7] Shutdown finished
[ N 2022-02-01 07:43:36.1067 710/Tm Ser/Server.h:558 ]: [ServerThr.8] Shutdown finished
[ N 2022-02-01 07:43:36.1064 710/Ti Ser/Server.h:901 ]: [ServerThr.6] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1068 710/Ti Ser/Server.h:558 ]: [ServerThr.6] Shutdown finished
[ N 2022-02-01 07:43:36.1070 710/To Ser/Server.h:901 ]: [ApiServer] Freed 0 spare client objects
[ N 2022-02-01 07:43:36.1070 710/To Ser/Server.h:558 ]: [ApiServer] Shutdown finished
[ N 2022-02-01 07:43:36.1074 710/T1 age/Cor/CoreMain.cpp:1147 ]: Checking whether to disconnect long-running connections for process 8728, application /Users/rich/Sites/HQ (production)
2022/02/01 07:43:36 [notice] 556#0: using the "kqueue" event method
[ N 2022-02-01 07:43:36.2035 9138/T1 age/Wat/WatchdogMain.cpp:1373 ]: Starting Passenger watchdog...
[ N 2022-02-01 07:43:36.2410 9140/T1 age/Cor/CoreMain.cpp:1340 ]: Starting Passenger core...
[ N 2022-02-01 07:43:36.2411 9140/T1 age/Cor/CoreMain.cpp:256 ]: Passenger core running in multi-application mode.
[ N 2022-02-01 07:43:36.2673 9140/T1 age/Cor/CoreMain.cpp:1015 ]: Passenger core online, PID 9140
2022/02/01 07:43:36 [notice] 556#0: start worker processes
2022/02/01 07:43:36 [notice] 556#0: start worker process 9142
2022/02/01 07:43:36 [notice] 556#0: start worker process 9143
2022/02/01 07:43:36 [notice] 556#0: start worker process 9144
2022/02/01 07:43:36 [notice] 556#0: start worker process 9145
2022/02/01 07:43:36 [notice] 556#0: start worker process 9146
2022/02/01 07:43:36 [notice] 556#0: start worker process 9147
2022/02/01 07:43:36 [notice] 556#0: start worker process 9148
2022/02/01 07:43:36 [notice] 556#0: start worker process 9149
2022/02/01 07:43:36 [notice] 720#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 728#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 724#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 721#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 556#0: signal 20 (SIGCHLD) received from 700
2022/02/01 07:43:36 [notice] 725#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 722#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 723#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 720#0: exiting
2022/02/01 07:43:36 [notice] 721#0: exiting
2022/02/01 07:43:36 [notice] 728#0: exiting
2022/02/01 07:43:36 [notice] 723#0: exiting
2022/02/01 07:43:36 [notice] 725#0: exiting
2022/02/01 07:43:36 [notice] 722#0: exiting
2022/02/01 07:43:36 [notice] 723#0: exit
2022/02/01 07:43:36 [notice] 728#0: exit
2022/02/01 07:43:36 [notice] 726#0: gracefully shutting down
2022/02/01 07:43:36 [notice] 721#0: exit
2022/02/01 07:43:36 [notice] 720#0: exit
2022/02/01 07:43:36 [notice] 722#0: exit
2022/02/01 07:43:36 [notice] 724#0: exiting
2022/02/01 07:43:36 [notice] 725#0: exit
2022/02/01 07:43:36 [notice] 556#0: signal 20 (SIGCHLD) received from 722
2022/02/01 07:43:36 [notice] 556#0: worker process 728 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: worker process 723 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: worker process 722 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: worker process 720 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 724#0: exit
2022/02/01 07:43:36 [notice] 556#0: signal 20 (SIGCHLD) received from 721
2022/02/01 07:43:36 [notice] 556#0: worker process 725 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: worker process 721 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 20 (SIGCHLD) received from 725
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received from 724
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 20 (SIGCHLD) received from 724
2022/02/01 07:43:36 [notice] 556#0: worker process 724 exited with code 0
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:43:36 [notice] 556#0: signal 23 (SIGIO) received from 9146
[ N 2022-02-01 07:43:37.2453 710/T1 age/Cor/CoreMain.cpp:1325 ]: Passenger core shutdown finished
[ E 2022-02-01 07:43:38.8844 9140/T5 age/Cor/SecurityUpdateChecker.h:507 ]: Security update check failed: error in server response (unparseable data). If this error persists, check your connection security and try upgrading Passenger (next check in 24 hours)
2022/02/01 07:44:00 [notice] 726#0: exiting
2022/02/01 07:44:00 [notice] 726#0: exit
2022/02/01 07:44:00 [notice] 556#0: signal 20 (SIGCHLD) received from 726
2022/02/01 07:44:00 [notice] 556#0: worker process 726 exited with code 0
2022/02/01 07:44:00 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:44:00 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:44:00 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:44:00 [notice] 556#0: signal 23 (SIGIO) received
2022/02/01 07:44:00 [notice] 556#0: signal 23 (SIGIO) received from 9148
```

**Comment by daBee** [comment]
Reboot.  Works now.  The previous error was post reboot, in fact.  Keeping an eye on it.
