### ISSUE TITLE
How to remove multiple Passenger installs

### ISSUE THREAD

**Issue by FractiekamerSplinter** [phusion/passenger#2474]
I installed Passenger with nginx through apt

But when I validate the install I get

 * Checking whether this Passenger install is in PATH... ✓
 * Checking whether there are no other Passenger installations... (!)

   You are currently validating against Phusion Passenger(R) 6.0.17, located in:
   
     /usr/bin/passenger
   
   Besides this Passenger installation, the following other
   Passenger installations have also been detected:
   
     /usr/local/bin/passenger
   
   Please uninstall these other Passenger installations to avoid
   confusion or conflicts.

How can I delete one of them? Using apt uninstall -y passenger does not do the job because when I reinstall I get the same install validation error and a possible rack.db conflict

**Comment by FractiekamerSplinter** [comment]
This is the output of my nginx error log:
```
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1]   
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] Errno::EACCES (Permission denied @ dir_s_mkdir - /home/decidim/decidim-app/tmp/cache/10D):
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1]   
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:253:in `mkdir'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:253:in `fu_mkdir'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:231:in `block (2 levels) in mkdir_p'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:229:in `reverse_each'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:229:in `block in mkdir_p'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:211:in `each'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /home/decidim/.rbenv/versions/3.0.5/lib/ruby/3.0.0/fileutils.rb:211:in `mkdir_p'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache/file_store.rb:164:in `ensure_cache_path'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache/file_store.rb:87:in `write_entry'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache/strategy/local_cache.rb:165:in `write_entry'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache.rb:476:in `block in write'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache.rb:726:in `block in instrument'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/notifications.rb:205:in `instrument'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache.rb:726:in `instrument'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache.rb:474:in `write'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack/cache.rb:80:in `do_count'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack/cache.rb:27:in `count'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack/throttle.rb:31:in `matched_by?'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack/configuration.rb:91:in `block in throttled?'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack/configuration.rb:90:in `any?'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack/configuration.rb:90:in `throttled?'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-attack (6.6.1) lib/rack/attack.rb:118:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/strategy.rb:202:in `call!'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/strategy.rb:169:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] omniauth (2.1.0) lib/omniauth/builder.rb:44:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] warden (1.2.9) lib/warden/manager.rb:34:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] decidim-core (0.27.1) lib/decidim/middleware/strip_x_forwarded_host.rb:12:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] decidim-core (0.27.1) lib/decidim/middleware/current_organization.rb:25:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/tempfile_reaper.rb:15:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/etag.rb:27:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/conditional_get.rb:27:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/head.rb:12:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/http/permissions_policy.rb:22:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/http/content_security_policy.rb:19:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/session/abstract/id.rb:266:in `context'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/session/abstract/id.rb:260:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/cookies.rb:689:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/callbacks.rb:98:in `run_callbacks'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] railties (6.1.6) lib/rails/rack/logger.rb:37:in `call_app'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] railties (6.1.6) lib/rails/rack/logger.rb:26:in `block in call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `block in tagged'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/tagged_logging.rb:37:in `tagged'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/tagged_logging.rb:99:in `tagged'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] railties (6.1.6) lib/rails/rack/logger.rb:26:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/request_id.rb:26:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/method_override.rb:24:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] activesupport (6.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/executor.rb:14:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack (2.2.3.1) lib/rack/sendfile.rb:110:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/ssl.rb:77:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] actionpack (6.1.6) lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] railties (6.1.6) lib/rails/engine.rb:539:in `call'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] Processing by Decidim::ErrorsController#internal_server_error as */*
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] Redirected to https://212.227.171.106/system/
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] Filter chain halted as :verify_organization rendered or redirected
App 9636 output: [7437ad79-4f7a-43c8-b417-983a4a2edec1] Completed 302 Found in 1ms (ActiveRecord: 0.0ms | Allocations: 292)
```

**Comment by CamJN** [comment]
Permission denied making a directory in: `/home/decidim/decidim-app/tmp/cache/`, fix the permissions so your app user can create directories there. As for fixing having two passenger's installed, you probably put one in your gemfile and installed one with apt, don't do that. Only install from one of those sources, remove the other and don't reinstall it.

**Comment by FractiekamerSplinter** [comment]
Hi CamJN, I removed the gem file and kept the apt install, but then I get the following error:
[ E 2023-02-14 00:32:11.4307 10855/Tn age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /home/decidim/decidim-app: The application encountered the following error: Could not find passenger-6.0.17 in locally installed gems (Bundler::GemNotFound)

**Comment by FractiekamerSplinter** [comment]
But when I re-install that I get an server 500 error as stated above, even with the permissions 

My error log states:
App 11158 output:   /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/sendfile.rb:110:in `call'
App 11158 output:   /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/ssl.rb:77:in `call'
App 11158 output:   /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/actionpack-6.1.6/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
App 11158 output:   /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
App 11158 output:   /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/engine.rb:539:in `call'
App 11158 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
App 11158 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
App 11158 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 11158 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
App 11158 output:   /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by FractiekamerSplinter** [comment]
It should be right as I am using it in nginx?

passenger-config about ruby-command
passenger-config was invoked through the following Ruby interpreter:
  Command: /home/decidim/.rbenv/versions/3.0.5/bin/ruby
  Version: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
  To use in Apache: PassengerRuby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
  To use in Nginx : passenger_ruby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
  To use with Standalone: /home/decidim/.rbenv/versions/3.0.5/bin/ruby /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/bin/passenger start

The following Ruby interpreter was found first in $PATH:
  Command: /home/decidim/.rbenv/versions/3.0.5/bin/ruby
  Version: ruby 3.0.5p211 (2022-11-24 revision ba5cf0f7c5) [x86_64-linux]
  To use in Apache: PassengerRuby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
  To use in Nginx : passenger_ruby /home/decidim/.rbenv/versions/3.0.5/bin/ruby
  To use with Standalone: /home/decidim/.rbenv/versions/3.0.5/bin/ruby /home/decidim/.rbenv/versions/3.0.5/lib/ruby/gems/3.0.0/gems/passenger-6.0.17/bin/passenger start
