### ISSUE TITLE
Dependency strscan breaks passenger-status command

### ISSUE THREAD

**Issue by Gbeschbacher** [phusion/passenger#2556]
**Gem `strscan` on version `3.1.0` breaks `passenger-status` command**
---

## Issue report

**Question 1: What is the problem?**
I've got a project with passenger and some dependencies. Updated a single dependency (`strscan`) from version `3.0.9` to `3.1.0`.

- What is the expected behavior?
Command `passenger-status` should still work as usual.

- What is the actual behavior?
```
root@123:/usr/src/app# passenger-status
Traceback (most recent call last):
        14: from /usr/sbin/passenger-status:38:in `<main>'
        13: from /usr/lib/ruby/vendor_ruby/phusion_passenger.rb:243:in `require_passenger_lib'
        12: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        11: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
        10: from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance_registry.rb:27:in `<top (required)>'
         9: from /usr/lib/ruby/vendor_ruby/phusion_passenger.rb:243:in `require_passenger_lib'
         8: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         7: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         6: from /usr/lib/ruby/vendor_ruby/phusion_passenger/admin_tools/instance.rb:29:in `<top (required)>'
         5: from /usr/lib/ruby/vendor_ruby/phusion_passenger.rb:243:in `require_passenger_lib'
         4: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         3: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
         2: from /usr/lib/ruby/vendor_ruby/phusion_passenger/utils/json.rb:28:in `<top (required)>'
         1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': incompatible library version - /usr/local/bundle/gems/strscan-3.1.0/lib/strscan.so (LoadError)
```

- How can we reproduce it? Please try to provide a sample application (or Virtual Machine) demonstrating the issue. Otherwise, if we can't reproduce it, we might have to ask you a number of followup questions or run certain commands to try and figure out the problem.
```
# DebugDockerfile
FROM ruby:3.3.3-bullseye
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates \
    && apt-key adv --no-tty --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 561F9B9CAC40B2F7 \
    && echo deb https://oss-binaries.phusionpassenger.com/apt/passenger bullseye main >> /etc/apt/sources.list.d/passenger.list \
    && apt-get update \
    && apt-get install -y \
      libnginx-mod-http-passenger \
    && rm -rf /var/lib/apt/lists/*
```
Building the image and running it with bash like this:
```
docker build -t debug_image -f DebugDockerfile .
docker run -it --rm --name debug_container debug_image  bash
```

Now calling the following commands:
``` 
passenger-status # works as expected
gem install strscan -v 3.1.0
passenger-status # broken
```

**Question 2: Passenger version and integration mode**:
```
root@123:/usr/src/app# passenger --version
Phusion Passenger(R) 6.0.22
```

**Question 3: OS or Linux distro, platform (including version)**:
```
$ lsb_release -d
Description:    Ubuntu 22.04.4 LTS
```

**Question 4: Passenger installation method**:

Your answer:
[ ] RubyGems + Gemfile
[ ] RubyGems, no Gemfile
[ ] Phusion APT repo
[ ] Phusion YUM repo
[ ] OS X Homebrew
[ ] source tarball
[x] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:
Ruby 3.3.3

**Question 6: Are you using a PaaS and/or containerization? If so which one?**
```
docker --version
Docker version 26.1.3, build b72abbb
```

**Comment by CamJN** [comment]
https://github.com/phusion/passenger/commit/1ba2f1be504425d3470835e52167ee3180c270fd
