### ISSUE TITLE
Phusion Passenger issues with auth0 issues

### ISSUE THREAD

**Issue by RailsCod3rFuture** [phusion/passenger#2574]
## Issue report

**Question 1: What is the problem?**
- What is the expected behavior?
Cookie should generate without issue and store session data for user
- What is the actual behavior?
Cookie stores data but overflows when being fetched during redirect
- How can we reproduce it?
  1. create a rails 7.1.3.3 application
  2. setup auth0 with an application that stores the profile in the cookie
  3. attempt to login to auth0 and redirect
  4. Cookie overflow should cause the view to fail

**Question 2: Passenger version and integration mode**:
passenger 6.0.23/nginx

**Question 3: OS or Linux distro, platform (including version)**:

Debian 8

**Question 4: Passenger installation method**:

Your answer:
- [ ] RubyGems + Gemfile
- [ ] RubyGems, no Gemfile
- [x] Phusion APT repo
- [ ] Phusion YUM repo
- [ ] OS X Homebrew
- [ ] source tarball
- [ ] Other, please specify:

**Question 5: Your app's programming language (including any version managers) and framework (including versions)**:

- ruby 3.2.4
- rails 7.1.3.3
- RVM

**Question 6: Are you using a PaaS and/or containerization? If so which one?**

deploying directly to server / no containerization

**Question 7: Anything else about your setup that we should know?**

**Comment by CamJN** [comment]
Please answer question 2, also please elaborate a little more about the problem. At what size does the cookie overflow? A rails session is very often larger than the size limit on cookies, so this may not have anything to do with Passenger.

**Comment by RailsCod3rFuture** [comment]
Just updating this thread with the log from my rails console.....Seems to fail at some point for phusion @CamJN 

```
Processing by AccountsController#jwt_callback as */*
  Parameters: {"code"=>"Nq6uS4IHYQluERdg_rZHhl6ZWJeg1m9bK3943wEHw3t33t3YmSE"}
  UserWebAccount Load (1.9ms)  SELECT `user_web_accounts`.* FROM `user_web_accounts` WHERE `user_web_accounts`.`client_number` = '000-001-59' LIMIT 1
  ↳ app/controllers/accounts_controller.rb:31:in `block (2 levels) in jwt_callback'
  CACHE UserWebAccount Load (1.8ms)  SELECT `user_web_accounts`.* FROM `user_web_accounts` WHERE `user_web_accounts`.`client_number` = '000-001-59' LIMIT 1
  ↳ app/helpers/application_helper.rb:31:in `fetch_current_user'
Completed 200 OK in 929ms (ActiveRecord: 4.6ms | Allocations: 13099)
  
ActionDispatch::Cookies::CookieOverflow (_web_signin_rails_session cookie overflowed with size 4336 bytes):
  
actionpack (7.1.3.3) lib/action_dispatch/middleware/cookies.rb:597:in `check_for_overflow!'
actionpack (7.1.3.3) lib/action_dispatch/middleware/cookies.rb:679:in `commit'
actionpack (7.1.3.3) lib/action_dispatch/middleware/cookies.rb:515:in `[]='
actionpack (7.1.3.3) lib/action_dispatch/middleware/session/cookie_store.rb:116:in `set_cookie'
rack (2.2.4) lib/rack/session/abstract/id.rb:403:in `commit_session'
actionpack (7.1.3.3) lib/action_dispatch/middleware/session/abstract_store.rb:72:in `commit_session'
rack (2.2.4) lib/rack/session/abstract/id.rb:268:in `context'
rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/cookies.rb:689:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (7.1.3.3) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (7.1.3.3) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'
airbrake (13.0.4) lib/airbrake/rack/middleware.rb:34:in `call!'
airbrake (13.0.4) lib/airbrake/rack/middleware.rb:23:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (7.1.3.3) lib/rails/rack/logger.rb:37:in `call_app'
railties (7.1.3.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (7.1.3.3) lib/active_support/tagged_logging.rb:135:in `block in tagged'
activesupport (7.1.3.3) lib/active_support/tagged_logging.rb:39:in `tagged'
activesupport (7.1.3.3) lib/active_support/tagged_logging.rb:135:in `tagged'
activesupport (7.1.3.3) lib/active_support/broadcast_logger.rb:240:in `method_missing'
railties (7.1.3.3) lib/rails/rack/logger.rb:24:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/request_id.rb:28:in `call'
rack (2.2.4) lib/rack/method_override.rb:24:in `call'
rack (2.2.4) lib/rack/runtime.rb:22:in `call'
activesupport (7.1.3.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (7.1.3.3) lib/action_dispatch/middleware/static.rb:25:in `call'
rack (2.2.4) lib/rack/sendfile.rb:110:in `call'
rack-cors (2.0.2) lib/rack/cors.rb:102:in `call'
railties (7.1.3.3) lib/rails/engine.rb:536:in `call'
/usr/share/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:149:in `accept_and_process_next_request'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
/usr/share/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
/usr/share/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
Started GET "/" for 10.15.14.87 at 2024-11-15 20:53:09 -0500
Processing by AccountsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.6ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 2.0ms | Allocations: 729)
Completed 200 OK in 4ms (Views: 2.5ms | ActiveRecord: 0.0ms | Allocations: 1267)
Started GET "/" for 10.15.4.103 at 2024-11-15 20:53:14 -0500
Processing by AccountsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 1.6ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.3ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 3.6ms | Allocations: 729)
Completed 200 OK in 6ms (Views: 4.3ms | ActiveRecord: 0.0ms | Allocations: 1266)
Started GET "/" for 10.15.3.102 at 2024-11-15 20:53:15 -0500
Processing by AccountsController#index as */*
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.6ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 2.0ms | Allocations: 729)
Completed 200 OK in 4ms (Views: 2.8ms | ActiveRecord: 0.0ms | Allocations: 1274)
Started GET "/" for 10.15.13.41 at 2024-11-15 20:53:18 -0500
Processing by AccountsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.6ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 2.0ms | Allocations: 729)
Completed 200 OK in 4ms (Views: 2.8ms | ActiveRecord: 0.0ms | Allocations: 1266)
Started GET "/" for 10.15.3.102 at 2024-11-15 20:53:25 -0500
Processing by AccountsController#index as */*
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.6ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 2.1ms | Allocations: 729)
Completed 200 OK in 3ms (Views: 2.6ms | ActiveRecord: 0.0ms | Allocations: 1274)
Started GET "/" for 94.188.207.240 at 2024-11-15 20:53:34 -0500
Processing by AccountsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.1ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.9ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.3ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 3.7ms | Allocations: 729)
Completed 200 OK in 7ms (Views: 4.3ms | ActiveRecord: 0.0ms | Allocations: 1269)
Started GET "/" for 10.15.3.129 at 2024-11-15 20:53:35 -0500
Processing by AccountsController#index as HTML
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.0ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.8ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 2.8ms | Allocations: 729)
Completed 200 OK in 4ms (Views: 3.1ms | ActiveRecord: 0.0ms | Allocations: 1266)
Started GET "/" for 10.15.3.102 at 2024-11-15 20:53:35 -0500
Processing by AccountsController#index as */*
  Rendering layout layouts/application.html.erb
  Rendering accounts/index.html.erb within layouts/application
  Rendered accounts/shared/_simple_view_header.html.erb (Duration: 0.1ms | Allocations: 15)
  Rendered accounts/index.html.erb within layouts/application (Duration: 0.8ms | Allocations: 169)
  Rendered shared/_header.html.erb (Duration: 0.1ms | Allocations: 44)
  Rendered accounts/partials/_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered identity/partials/_ln_message_modal.html.erb (Duration: 0.0ms | Allocations: 8)
  Rendered shared/_footer.html.erb (Duration: 0.1ms | Allocations: 8)
  Rendered layout layouts/application.html.erb (Duration: 2.5ms | Allocations: 729)
Completed 200 OK in 4ms (Views: 3.2ms | ActiveRecord: 0.0ms | Allocations: 1274)

```

**Comment by CamJN** [comment]
I'm sorry to disagree but the backtrace indicates that passenger passed the cookie to the webapp, and the action_dispatch middleware detected an overflow and threw an error. Regardless though, your cookie is too big, you need to make it smaller. The standard limit for cookie size is 4096B yours is 4336B.

**Comment by RailsCod3rFuture** [comment]
@CamJN Thank you again for your review. I'm looking closely -- I do see that the past developer added many fields to the cookie itself and rails 7 is having a hard time with managing the volume.
