### ISSUE TITLE
multiple signals for soft shutdown triggers SecurityError

### ISSUE THREAD

**Issue by FooBarWidget** [phusion/passenger#800]
_From [brettbender](https://code.google.com/u/106341205500697748597/) on September 01, 2011 01:01:33_

What steps will reproduce the problem? 1. Create a long-running controller action, like "sleep 30"
2. Make a request for this action
3. Signal USR1 to the Passenger / Rails process, and then a second USR1 What is the expected output? What do you see instead? I expect the long-running request to finish, and then the Rails process should stop.

Instead, the process continues after the first signal, but dies on the second with a SecurityError. What version of Phusion Passenger are you using? Which version of Rails? On what operating system? Ubuntu 11.04
Ruby 1.9.1p378
Passenger 3.0.8 Please provide any additional information below. Based on stack trace and poking around in the source...

SecurityError (unix:/tmp/passenger.1.0.5351/generation-0/socket):
  passenger (3.0.8) lib/phusion_passenger/message_client.rb:60:in `initialize'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:337:in`new'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:337:in `soft_shutdown'
  passenger (3.0.8) lib/phusion_passenger/abstract_request_handler.rb:433:in`block in install_useful_signal_handlers'

AbstractRequestHander#soft_shutdown is not idempotent. On each call we create a MessageClient and then detach() -- but a successful detach causes our account record to be deleted from the AccountsDatabase. Then if the signal handler is called a second time, we get a SecurityError b/c our credentials are no longer valid.

Instead if soft_shutdown was:

def soft_shutdown
  return if @did_soft_shutdown
  # ...
  @did_soft_shutdown = true
end

then we could signal repeatedly w/out error.

_Original issue: http://code.google.com/p/phusion-passenger/issues/detail?id=701_

**Comment by FooBarWidget** [comment]
We don't have a soft shutdown mechanism anymore, so closing this issue.
